### ISSUE TITLE
tracing-subscriber: big RAM usage

### ISSUE THREAD

**Issue by vorot93** [tokio-rs/tracing#1005]
```
fn main() {
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::from_default_env().add_directive("scratchpad=info".parse().unwrap()),
        )
        .init();

    std::thread::park();
}
```

This short program consumes 9 MB of residential memory on my Mac. It really shouldn't.

**Comment by hawkw** [comment]
@vorot93 were you looking at virtual memory or RSS when you observed this issue? I think I have a potential fix, but while verifying it, I noticed that on my machine (running linux), your repro uses about 12kb resident set size, and 15mb of virtual memory. Is that in line with your observations on the Mac?

**Comment by vorot93** [comment]
For me it's 8MB residential and 4GB virtual.
