### ISSUE TITLE
[tracing-subscriber] Custom global additional fields

### ISSUE THREAD

**Issue by DCjanus** [tokio-rs/tracing#1092]
### Crates

tracing-subscriber

### Motivation

In most distribute system, we output logs to log agent, with level, timestamp and instance_id, and looks like that tracing-subscriber doesn't support add global custom fields to all event/log.

For now, I'm hacking `JsonVisitor` and insert fields that I need to, which is really tricky, is there a better way to achieve this?

### Proposal

No idea

**Comment by hawkw** [comment]
@DCjanus one option for how to do this without any new APIs is to just create a span with your instance ID in `main`, enter it, and never exit it for the lifetime of the program. Then, it will be the parent of all spans and events for which the parent is not explicitly set to `None`.

For example:
```rust
fn main() {
    tracing::subscriber::set_global_default(/* configure your subscriber here */).unwrap();
    let app_span = tracing::info_span!("my_app", instance_id = /* however your instance IDs are generated... */);
    let _enter = app_span.enter();
    // ... all the rest of your application code ...
}
```

If something like that isn't sufficient for your use case, we could definitely consider adding a new API to add global fields, I just thought I'd propose this as an option.

**Comment by davidbarsky** [comment]
I think @hawkw's suggestion resolves the immediate issue. I'll close this, but feel free to re-open as needed.
