### ISSUE TITLE
`example/echo.rs` doesn't work concurrently

### ISSUE THREAD

**Issue by giraffate** [tokio-rs/tracing#1097]
## Bug Report
https://github.com/tokio-rs/tracing/blob/a8cc977e01ec4e1dce4137e37cfc1bfba7ebbed8/examples/examples/echo.rs doesn't work concurrently. It seems that the commit a8cc977e01ec4e1dce4137e37cfc1bfba7ebbed8 changed the behavior.

**Comment by davidbarsky** [comment]
I'm able to reproduce this issue with two instances of netcat. It seems like adding [this `.await?`](https://github.com/tokio-rs/tracing/blob/a8cc977e01ec4e1dce4137e37cfc1bfba7ebbed8/examples/examples/echo.rs#L120) caused the echo example to no longer be concurrent.
