### ISSUE TITLE
Allow for synthesized events on created/closed

### ISSUE THREAD

**Issue by markhildreth** [tokio-rs/tracing#1136]
### Crates

* tracing_subscriber

### Motivation

The typical example for a span is something like an HTTP request. If a span is performed in this way, it may be desirable to have the span synthesize an event. I could see using `FmtSpan::CLOSE`, which gives you a single event for the entire request. However, if I want two requests (one at the start, one at the end) there aren't really good options: both `ACTIVE` and `FULL` will give me an event at the start of the request, but potentially even more if I am polling some futures during the request handling.

### Proposal

Add another item to the enum, `FmtSpan::???`. When used, synthesized events will be emitted on only new and drop events.

### Alternatives

Or perhaps I'm not understanding the full purpose of the `FmtSpan` type, and it's maybe better in this case to use some other way of filtering this out?

**Comment by zicklag** [comment]
I have had the same need for a while now. I feel like the `FULL` option is too verbose, but the `CLOSE` option doesn't include the starting point. As an alternative proposal, we could do a bitflag that allows you to arbitrarily combine the different messages you want to receive such as

```rust
let fmt_layer = fmt::layer().with_span_events(FmtSpan::START | FmtSpan::END);
```

**Comment by hawkw** [comment]
> I have had the same need for a while now. I feel like the `FULL` option is too verbose, but the `CLOSE` option doesn't include the starting point. As an alternative proposal, we could do a bitflag that allows you to arbitrarily combine the different messages you want to receive such as
> 
> ```rust
> let fmt_layer = fmt::layer().with_span_events(FmtSpan::START | FmtSpan::END);
> ```
> 
> This doesn't preclude us from having "preset" bit patterns so that you could still just do:
> 
> ```rust
> let fmt_layer = fmt::layer().with_span_events(FmtSpan::FULL);
> ```
> 
> If I can get approval for the idea I could potentially find time to do the implementation, if a quick check of the internals looks simple enough. We could even make the change backward compatible by keeping the existing constant names representing the same flags.

Yup, the bitflags approach sounds good to me; if you want to work on it, I'd happily merge a PR. Let's make sure it's backwards-compatible. We should probably also avoid exposing the internal bitflag implementation details publicly (e.g., I don't think we want to add conversions to/from integers to the public API, unless there's a compelling reason to).

**Comment by zicklag** [comment]
Sounds good! I opened #1277 with the changes.
