### ISSUE TITLE
Put the date for rolling logs BEFORE the extension

### ISSUE THREAD

**Issue by mamcx** [tokio-rs/tracing#1184]
## Feature Request

I wanna use rolling files for logs, and found the default very weird looking:

`server.log.2021-01-11`

### Motivation

Is the default for opening files and searching for them to keep the .ext at the end. If I just click the `server.log.2021-01-11` the OS will ask for an app to use. And because the date change, will ask N times. 

Instead:

`server.2021-01-11.log`

will work fine.

**Comment by mamcx** [comment]
Can I send a PR with this as an option?

**Comment by hawkw** [comment]
I'd love to merge a PR to make this configurable.

**Comment by hawkw** [comment]
This is now possible using the `filename_suffix` builder parameter added by PR #2225. This should be released shortly.
