### ISSUE TITLE
fmt: JSON formatter failing to parse formatted fields

### ISSUE THREAD

**Issue by hawkw** [tokio-rs/tracing#1192]
### Version

- `tracing-subscriber` 0.2.15
### Crates

- `tracing-subscriber`

### Description

Spotted in the wild: https://github.com/linkerd/linkerd2/issues/5520#issuecomment-759654897

Apparently, when using Linkerd 2 with the JSON formatter, users are seeing `field_error`s in the logs. The JSON formatter emits this error when a previously formatted field set does not parse as valid JSON.

The fields in question should be `SocketAddr`s formatted with `fmt::Display`.

Curiously, the following simple repro attempt works as expected:
```rust
use std::net::SocketAddr;

fn main() {
    tracing_subscriber::fmt().json().with_span_list(true).init();

    // Some fake socket addrs.
    let peer = "127.0.0.1:666".parse::<SocketAddr>().unwrap();
    let local = "127.0.0.1:420".parse::<SocketAddr>().unwrap();

    // Create a span with those addrs as fields.
    let span = tracing::info_span!("accept", peer.addr = %peer, local.addr = %local);
    let _e = span.enter();
    // This WORKS --- fields are formatted correctly
    tracing::info!("accepted connection!");
}
```
so there's probably some more complex interaction going on here...

**Comment by hawkw** [comment]
...oh, never mind: this one's PEBCAK. Running `linkerd2-proxy` tests with the subscriber configured to use the JSON formatter gets us this: 
```
test tests::transparency::inbound_http1 ... thread 'main' panicked at 'span 'test_server' had malformed fields! this is a bug.
  error: expected value at line 1 column 1
  fields: FormattedFields { fields: "version=Http1 addr=127.0.0.1:43367 test=main" }', /home/eliza/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-subscriber-0.2.15/src/fmt/format/json.rs:162:49
```
Looks like I forgot to set the JSON field formatter, and just set the JSON event formatter. This isn't a `tracing-subscriber` bug.

**Comment by JakubKoralewski** [comment]
Same exact situation as reporter above, did not find the `.json()` method because rust-analyzer didn't load it for me yet, and tried to enable it myself thinking `json()` does not exist. Works with `.json()`
