### ISSUE TITLE
tracing-opentelemetry: Docs for otel.kind are unclear about capitalisation

### ISSUE THREAD

**Issue by nikclayton-dfinity** [tokio-rs/tracing#1209]
### Version

Git version https://github.com/tokio-rs/tracing/blob/705613c3ef04e334b90a49a60676ff7de8e495bd/tracing-opentelemetry/src/lib.rs

### Description

The documentation is unclear / inconsistent about the capitalisation of values for the `otel.kind` field.

https://github.com/tokio-rs/tracing/blob/705613c3ef04e334b90a49a60676ff7de8e495bd/tracing-opentelemetry/src/lib.rs#L25-L28 lists the values in ALL-CAPS.

The example code, a few lines below, at https://github.com/tokio-rs/tracing/blob/705613c3ef04e334b90a49a60676ff7de8e495bd/tracing-opentelemetry/src/lib.rs#L36 is all lower-case.

The test code in https://github.com/tokio-rs/tracing/blob/705613c3ef04e334b90a49a60676ff7de8e495bd/tracing-opentelemetry/src/layer.rs#L660-L682 uses Initial case / Sentence case.

The actual implementation appears to be case insensitive, https://github.com/tokio-rs/tracing/blob/705613c3ef04e334b90a49a60676ff7de8e495bd/tracing-opentelemetry/src/layer.rs#L87-L101.

**Comment by morigs** [comment]
I believe the best option is to replace string with enum. According to [OTel spec](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/api.md#spankind) spankind has a fixed number of variants. And the most actual implementation [uses ](https://github.com/open-telemetry/opentelemetry-go/blob/c066f15ed74fec52c4755014bfcf2bdfb8e0e661/trace/trace.go#L484)enums.

Type system is the best documentation 😄

**Comment by nikclayton-dfinity** [comment]
Completely agree -- the equivalent Rust enum is https://github.com/open-telemetry/opentelemetry-rust/blob/45da275bd4d66cf8816eb9f3c7c15961ae2595f0/opentelemetry/src/trace/span.rs#L168-L238. Maybe the documentation could be updated to reflect this as best practice?

**Comment by hawkw** [comment]
cc @jtescher

**Comment by jtescher** [comment]
Yeah these docs should be updated to use the enum. E.g. `trace_span!("request", "otel.kind" = %SpanKind::Client, "http.url" = ..)` is a better choice.
