### ISSUE TITLE
`#[instrument(fields(...))]` does not support dotted field names

### ISSUE THREAD

**Issue by nikclayton-dfinity** [tokio-rs/tracing#1210]
### Version

tracing-attributes v0.1.8

### Platform

Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64 i386 MacBookPro15,1 Darwin

### Description

I want to set `otel.kind` in a function instrumented using `#[instrument]`.

Reading the docs I figured

```
#[instrument(fields(otel.kind="server"))]
```

would do it, but that results in:

```
error: expected `,`
   --> redacted/mod.rs:168:41
    |
168 | #[instrument(fields(otel.kind="server"))]
                                   ^
```

You get the same error if `otel.kind` is quoted.

**Comment by nikclayton-dfinity** [comment]
I checked out the code to prepare a PR to fix this, and saw that the code does actually support this now. Looks like https://github.com/tokio-rs/tracing/commit/d24a43aaee201bcddbaf1cd8bf1d1cff72f2de12#diff-9cbd60b122df9aadd01f63b729cf92e850d39bbb6ba8bb58c1d1d5c8be0e4e3c was the change that landed this.

With a `Cargo.toml` file that contains:

```
tracing = "0.1"
```

cargo fetched tracing-attributes 0.1.8, which is the version immediately before this support landed. I had to explicitly add `tracing-attributes` like so:

```
tracing = "0.1"
tracing-attributes = "0.1"
```

before cargo would update to the latest version (0.1.11 at time of writing).

The documentation is still out of date -- https://github.com/tokio-rs/tracing/blob/master/tracing-attributes/src/lib.rs#L117-L118 notes that dotted identifiers are not supported, and should be updated.

**Comment by hawkw** [comment]
> With a `Cargo.toml` file that contains:
> 
> ```
> tracing = "0.1"
> ```
> 
> cargo fetched tracing-attributes 0.1.8, which is the version immediately before this support landed. I had to explicitly add `tracing-attributes` like so:
> 
> ```
> tracing = "0.1"
> tracing-attributes = "0.1"
> ```
> 
> before cargo would update to the latest version (0.1.11 at time of writing).

Seems like a good fix would be to just bump the minimum version for `tracing`'s `tracing-attributes`  dependency, then --- I can do that right away!

**Comment by hawkw** [comment]
`tracing` v0.1.23 updates the minimum dependency on `tracing-attributes` to v0.1.12, and that release of `tracing-attributes` updates the docs to no longer claim that dotted field names are no longer supported --- which should fix this. Thanks for the report!
