### ISSUE TITLE
`#[instrument(fields(...))]` does not support `field::Empty`

### ISSUE THREAD

**Issue by nikclayton-dfinity** [tokio-rs/tracing#1211]
### Version

```
│   │   ├── tracing v0.1.15
│   │   │   ├── tracing-attributes v0.1.8
│   │   │   └── tracing-core v0.1.10
│   │   │       │   │   │   │   │   └── tracing v0.1.15 (*)
│   │   └── tracing v0.1.15 (*)
├── tracing v0.1.15 (*)
├── tracing-futures v0.2.4
│   └── tracing v0.1.15 (*)
├── tracing-opentelemetry v0.10.0
│   ├── tracing v0.1.15 (*)
│   ├── tracing-core v0.1.10 (*)
│   ├── tracing-log v0.1.1
│   │   └── tracing-core v0.1.10 (*)
│   └── tracing-subscriber v0.2.9
│       ├── tracing-core v0.1.10 (*)
│       ├── tracing-log v0.1.1 (*)
│       └── tracing-serde v0.1.2
│           └── tracing-core v0.1.1
```

### Platform

Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64 i386 MacBookPro15,1 Darwin

### Description

Since you can't record a new field on a span after it's been created (per the docs) I wanted to pre-create some fields on the `#[instrument(fields(...))]`.

The documentation doesn't suggest this is possible, but gives the example:

```
let span = trace_span!("my_span", greeting = "hello world", parting = field::Empty);
```

Given that, I figured that

```
#[instrument(fields(foo = tracing::field::Empty))]
```

would make sense.

Sadly, that results in

```
error: expected literal
   --> redacted/mod.rs:168:36
    |
168 | #[instrument(fields(foo = tracing::field::Empty), err, skip(registry_client, metrics))]
    |                           ^^^^^^^
```

**Comment by nikclayton-dfinity** [comment]
I checked out the code to prepare a PR to fix this, and saw that the code does actually support this now. Looks like d24a43a#diff-9cbd60b122df9aadd01f63b729cf92e850d39bbb6ba8bb58c1d1d5c8be0e4e3c was the change that landed this.

With a Cargo.toml file that contains:

```
tracing = "0.1"
```

cargo fetched tracing-attributes 0.1.8, which is the version immediately before this support landed. I had to explicitly add tracing-attributes like so:

```
tracing = "0.1"
tracing-attributes = "0.1"
```

before cargo would update to the latest version (0.1.11 at time of writing).

With that change the syntax to specify an empty field is just to list the field name without any value. For example:

```
#[instrument(fields(otel.kind = "server", http.url))]
fn handle(request: Request<Body>) {
    let span = Span::current();
    span.record("http.url", &request.uri().to_string().as_str());

    // handle the request
}
```

Perhaps this example, or something like it, could be added to the documentation?

**Comment by hawkw** [comment]
`tracing` v0.1.23 updates the minimum dependency on `tracing-attributes` to v0.1.12, and that release of `tracing-attributes` updates the docs to add examples with empty fields. Thanks for the report!
