### ISSUE TITLE
tracing-nursery repository doesn't exist

### ISSUE THREAD

**Issue by waywardmonkeys** [tokio-rs/tracing#125]
There are references to a `tracing-nursery` repository, but it doesn't seem to exist.

**Comment by hawkw** [comment]
This is my fault --- it's a find-and-replace mishap from when this library was called `tokio-trace` and there was a `tokio-trace-nursery` repository. Those crates now live in this repository. The docs should be fixed.

**Comment by hawkw** [comment]
#142 removes all the references to the `tracing-nursery` repository in the `tracing` readme and RustDoc. #141 removes mentions of it from `CONTRIBUTING.md` I'm going to make sure there aren't any other references to a `tracing-nursery`, and if that's all of them, I think this is fixed.
