### ISSUE TITLE
tracing subscriber has a lot of default features

### ISSUE THREAD

**Issue by matklad** [tokio-rs/tracing#1258]
I see that `tracing-subscriber` has a lot default features. This feels a bit wrong to me: I understand that this is the crate which should be used by libraries implementing subscribers. Ie, it's an intermediate library. In this context, authors of subscribers might forget to include `default-features = false`, and induce deps on final consumers. See https://github.com/rust-lang/chalk/issues/686#issuecomment-783510341 for an example of this. 

I wonder if maybe this is wrong crate factoring? Maybe `subscriber` should be just a `cfg`ed non-default module of the `tracing` crate? 

Super unclear about what's the best solution here, but it's definitely a problem that rust-analyzer pulls in chrono, and I need to investigate which of my dependencies done this :)

**Comment by hawkw** [comment]
I think it's definitely worth reconsidering this as part of the Tracing 0.2 work — for the next breaking change, I think we may want to factor out all of the subscriber _implementations_ into a separate crate from the core trait definitions.
