### ISSUE TITLE
Backport #1103 to `tracing-subscriber` `0.2.x`?

### ISSUE THREAD

**Issue by thomaseizinger** [tokio-rs/tracing#1271]
Hi there!

Was about to open a PR that fixes the trailing space in the `ChronoLocal` time formatter only to see that it is already fixed in master! :)

Is there a chance we can get #1103 backported to a `0.2.x` release of `tracing-subscriber`?

Thank you!

**Comment by hawkw** [comment]
Whoops, I thought this one had already been backported. I'll take care of it --- thanks for letting us know!

**Comment by davidbarsky** [comment]
Realized that we can close this issue now!
