### ISSUE TITLE
Example in tracing_subscriber/src/fmt/format/mod.rs

### ISSUE THREAD

**Issue by Gore55** [tokio-rs/tracing#1287]
The example in the mentioned file uses the trait Collect, but that trait is named Subscriber now.

**Comment by Folyd** [comment]
> The example in the mentioned file uses the trait Collect, but that trait is named Subscriber now.

No, I think the current example is correct since we renamed the old `Subscribe` and `Layer`  to `Collect` and `Subscriber` respectively. See #922.
