### ISSUE TITLE
[tracing-opentelemetry] Option to set status of span similar kind/name

### ISSUE THREAD

**Issue by kstasik** [tokio-rs/tracing#1346]
### Crates

tracing-opentelemetry

### Motivation

Right now all correct spans/traces are left without status codes and status messages. I want to be able to set custom span status to follow opentelemetry semantic conventions.

### Proposal

Add option to pass status code and message similarly to span kind and name:

https://github.com/tokio-rs/tracing/blob/master/tracing-opentelemetry/src/subscriber.rs#L206

### Alternatives

Mark all traces without errors as OK:

https://github.com/tokio-rs/tracing/blob/master/tracing-opentelemetry/src/subscriber.rs#L529

@jtescher please let me know what do you think. It looks like you are main contributor of this crate

**Comment by jtescher** [comment]
Sounds like a good idea 👍
