### ISSUE TITLE
Tracking issue for composing multiple subscribers

### ISSUE THREAD

**Issue by hawkw** [tokio-rs/tracing#135]
### Crates

`tracing-subscriber`

### Motivation

In many cases, it is valuable to compose multiple consumers for trace events. However, certain aspects of `tracing`'s design --- in particular, that span IDs are assigned by the subscriber, and that a single subscriber collects events from multiple threads --- make it difficult to compose the `Subscriber` trait directly. 

### Proposal

I think it should be possible to implement subscriber composition in the `tracing-subscriber` crate without making changes to `tracing-core`. Here's how I think we should do this:

- Provide a `Layer`/`Middleware`-like approach for composing multiple _consumers_ (which don't get to assign span IDs) around a single core subscriber that does assign IDs. I have a work in progress implementation of this, and will open a draft PR for discussion.
- Provide a similar interface for composing _filters_, based on logical combinators, that slots into the `Layer` interface.
- Provide an optimized concurrent structure for subscriber implementations to use for storing span data. I have some thoughts on this, which I described in #157. This will give subscriber layers an alternative to `Mutex<HashMap<Id, MyPerSpanData>>` and similar bad ideas.
- Update existing subscriber implementations to be compatible with this API.
- Investigate combinators like tees as well.

### Alternatives

There are other potential ways to implement subscriber fan-out. 

In the past, I've considered an approach where there is a central registry that manages per-span data and provides it to multiple consumers. I think this introduces a lot of complexity and is hard to come up with a design that satisfies the needs of various subscribers --- this is a big part of why tools for subscriber composition haven't landed sooner.

@davidbarsky proposed modifying the `Dispatch` type in `tracing-core` to take a slice of subscribers and iterate over them. I don't think this is the right approach for the following reasons:
 - It's a change in `tracing-core`, which I really don't think is necessary to implement this. IMO, if we can do it in a crate on top of `-core`, we should.
 - This approach does not solve the problem that all spans must have a single ID. If the dispatcher iterates over multiple implementations of the `Subscriber` trait, we would need a method for determining whose ID is the authoritative one. This could lead to very surprising behaviour when implementations expect _their_ IDs to be used.
- Similarly, it is difficult to reason about whether or not a span is enabled in such a world.

Finally, we could do nothing. Many implementations are already writing ad-hoc versions of the layered/stacked subscriber I described above (@LucioFranco's experiments w/ this was part of the inspiration behind the design I proposed). However there are several pitfalls/gotchas that ad-hoc implementations need to avoid, while if we provide a principled implementation in a library, it is only necessary to solve these problems once.

**Comment by LucioFranco** [comment]
@hawkw this sounds really good. I think the layer approach will work well for decorating subscribers. I'm curious to see how composing filters might work. I think the most valuable thing we can provide right now is the data structure for tracking state. This is something ive rewritten three times. So I think by far the first step here is to produce that. Then continue to learn how wrapper subs work.

**Comment by hawkw** [comment]
#136 is a draft proposal for a layer trait for subscriber composition.

**Comment by hawkw** [comment]
currently in progress: 
- [ ] `Subscriber::try_close` (#153)
- [ ] `tracing-subscriber::Layer` API for composing layers (#136/#149 , depends on #153)
