### ISSUE TITLE
Invalid additional space when using without_time

### ISSUE THREAD

**Issue by ririsoft** [tokio-rs/tracing#1354]
### Version

tracing v0.1.25
tracing-subscriber v0.2.17

### Platform

Windows 64

### Description

When using `tracing-subscriber::fmt::SubscriberBuilder::without_time` an unexpected additional space character is added at the beginning of the output.

I tried this code:

```rust
use tracing::info;

fn main() {
    tracing_subscriber::fmt()
        .without_time()
        .with_level(false)
        .with_target(false)
        .init();
    info!("Hello, world!");
}
```

I expected to see this happen: no space at the beginning of the line

```text
❯ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.09s
     Running `target\debug\proximum.exe`
Hello, world!
```

Instead, this happened: space at the beginning of the line
```text
❯ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.09s
     Running `target\debug\proximum.exe`
 Hello, world!
```

Am I missing something or this is a bug ?
Cheers !

**Comment by hawkw** [comment]
Yup, that's definitely a bug, and we should fix that. Thanks for the report!
