### ISSUE TITLE
tracing-subscriber prevents vscode debugger from finding sources

### ISSUE THREAD

**Issue by danielzfranklin** [tokio-rs/tracing#1363]
## Bug Report

I haven't tried to reproduce this outside of vscode with rust-analyzer.

### Version

```
└── tracing-subscriber v0.2.17
    ├── tracing v0.1.25
    │   └── tracing-core v0.1.17
    ├── tracing-core v0.1.17 (*)
    ├── tracing-log v0.1.2
    │   └── tracing-core v0.1.17 (*)
    └── tracing-serde v0.1.2
        └── tracing-core v0.1.17 (*)
```

### Platform

```
> uname -a
Linux daniel-darter 5.11.0-7612-generic #13~1617215757~20.10~97a8d1a-Ubuntu SMP Thu Apr 1 21:09:17 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```

### Crates

* tracing-subscriber

### Description

I created a blank project `cargo new --lib` and added the dependency `tracing-subscriber = "0.2.17"`. I add the test:

```rust
    #[test]
    fn it_breaks() {
        tracing_subscriber::fmt::init();
        assert_eq!(2 + 2, 4);
    }
```

I set a breakpoint on the line with the assert statement and ran the test under vscode's debugger. The breakpoint wasn't hit. I know my debugger works because if I remove the call to `fmt::init` the breakpoint is hit.

I then replaced the assertion with a panic

```rust
    #[test]
    fn it_breaks() {
        tracing_subscriber::fmt::init();
        panic!();
    }
```

My debugger is set to break on panic, which happens. If I select the stack frame for `it_breaks` I see disassembly and the message "Source location: unknown" ([screenshot](https://gist.github.com/danielzfranklin/51abc23bdc24c14f8893581f58b2c401#file-with_tracing_subscriber-png)).

If I remove the call to `fmt::init` and select the stack frame for `it_breaks` I see the source code. ([screenshot](https://gist.github.com/danielzfranklin/51abc23bdc24c14f8893581f58b2c401#file-without_tracing_subscriber-png)).

**Comment by hawkw** [comment]
Hmm, this is quite weird, I'm not totally sure what's going on here!

Some additional questions that could be useful to answer:
 - Do you know what debugger VS Code is using internally? Is it LLDB?
 - What happens if you replace `tracing_subscriber::fmt::init()` with something like
   ```rust
    use tracing_subscriber::prelude::*;
    tracing_subscriber::registry().init();
    ```

**Comment by hawkw** [comment]
Hmm, interesting --- my understanding (although I'm not really an LLDB user) is that one should always use the `rust-lldb` wrapper when debugging Rust code with LLDB in order to get correct output from the debugger? Is it possible that, when invoking `lldb` directly rather than using `rust-lldb`, you might see similar results with another non-inlined function call, or with another function call from an external crate?

**Comment by jtougas** [comment]
Yeah this was working for me up until recently, so some regression in the tooling is the likely culprit.

I found this -> https://github.com/vadimcn/vscode-lldb/issues/424 and installed the suggested pre-release which worked.

Hope this helps!

**Comment by hawkw** [comment]
Am I correct that this is not a `tracing` bug and we can close this issue?

**Comment by danielzfranklin** [comment]
Yes. Thank you for the debugging suggestions.
