### ISSUE TITLE
`Level` is not `Hash` – can I make it so?

### ISSUE THREAD

**Issue by dvdplm** [tokio-rs/tracing#1376]
I was trying to use [`Level`](https://docs.rs/tracing-core/0.1.17/tracing_core/metadata/struct.Level.html) as part of the key to a `HashSet` and realized that it is not `Hash`. Given that `LevelInner` **is** `Hash` I wonder if the outer type can be too. 

Happy to open a PR.

**Comment by hawkw** [comment]
I think it would be fine to derive `Hash` for `Level`, please feel free to open a PR :)
