### ISSUE TITLE
Allow setting event names in macros

### ISSUE THREAD

**Issue by seanmonstar** [tokio-rs/tracing#1426]
### Crates

- `tracing`

### Motivation

Sometimes it would be useful to be able to specify the `name` part of an event's metadata, just like we can with spans.

### Proposal

Add support to the event macros (`trace!`, `debug!`, etc) to set the event name specifically, similar to target.

```rust
debug!(name: "waker.clone", my.other = stuff);
```

That would set the `Metadata::name()` to `"waker.clone"` for that event.

**Comment by ileixe** [comment]
@hawkw it seems to be simple enough to change, but are you alined to support this change? If then, I will take this issue as we need to introduce this change as well.

**Comment by cijothomas** [comment]
The issue is quite old, but wondering if people are still interested in this or found an alternative? (We are leveraging tracing in our company and this is something we could use!)

**Comment by hawkw** [comment]
@cijothomas I would merge a PR adding a `name:` argument to the `event!` macros, if anyone is interested in opening one!
