### ISSUE TITLE
[tracing-journald] Redundant log entry prefexes?

### ISSUE THREAD

**Issue by khionu** [tokio-rs/tracing#1440]
### Versions

```
├── tracing v0.1.26
│   ├── tracing-attributes v0.1.15 (proc-macro)
│   └── tracing-core v0.1.18
├── tracing-appender v0.1.2
│   └── tracing-subscriber v0.2.18
│       ├── tracing v0.1.26 (*)
│       ├── tracing-core v0.1.18 (*)
│       ├── tracing-log v0.1.2
│       │   └── tracing-core v0.1.18 (*)
│       └── tracing-serde v0.1.2
│           └── tracing-core v0.1.18 (*)
├── tracing-journald v0.1.0
│   ├── tracing-core v0.1.18 (*)
│   └── tracing-subscriber v0.2.18 (*)
└── tracing-subscriber v0.2.18 (*)
```

### Platform

`Linux <SNIP:HOSTNAME> 5.10.5-1951-amd+ #1 SMP Fri Feb 5 11:12:07 IST 2021 x86_64 x86_64 x86_64 GNU/Linux`

### Crates

`tracing-journald`

### Description

I'm initializing the logging with this code at the very beginning of `main`
```rs
let registry =
    tracing_subscriber::registry().with(tracing_subscriber::fmt::layer().with_target(false));

let _log_guard;

match tracing_journald::layer() {
    Ok(x) => registry.with(x).init(),
    Err(err) => {
        let srv_log_file = OpenOptions::new()
            .append(true)
            .read(true)
            .open("/var/log/<SNIP>.log")
            .unwrap();

        let (non_blocking, guard) = tracing_appender::non_blocking(srv_log_file);

        _log_guard = guard;

        registry.with(tracing_subscriber::fmt::layer().with_writer(non_blocking)).init();

        tracing::warn!("Failed to connect to journald, falling back to file logging: {}", err);
    }
}
```
The following is a single line from journald. Note that `launch.sh` is not the same as `<SNIP:SERVICE>`
```
Jun 18 20:21:12 <SNIP:HOSTNAME> <SNIP:SERVICE>[4047266]: Line did not match: Jun 18 20:21:11 <SNIP:HOSTNAME> <SNIP:SERVICE>[4047266]: Line did not match: Jun 18 20:21:11 <SNIP:HOSTNAME> <SNIP:SERVICE>[4047266]: Line did not match: Jun 18 20:21:10 <SNIP:HOSTNAME> launch.sh[4047266]: Jun 18 20:21:10.968 DEBUG Error output: error at 1:1: expected <unreported>
```
I would expect `launch.sh` to not be mentioned here at all because it's what is invoking the binary, and I'd not expect the redundant prefixes or information. It looks here that there might be multiple things contributing to the log line, noting that there are two different datetimes, one with and one without the milliseconds.

**Comment by hawkw** [comment]
ccing @Ralith

**Comment by Ralith** [comment]
Looks like you're writing to both stdout (via the `fmt` layer) and journald. When systemd runs a service, it automatically forwards stdout to journald so that non-journald-aware services get logged. This is probably causing duplication in your output. I recommend only enabling the `fmt` layer if `isatty` returns 1 for stdout.

"launch.sh" is probably what systemd thinks your unit is named. Refer to systemd documentation for how unit names are computed.

**Comment by hawkw** [comment]
> When systemd runs a service, it automatically forwards stdout to journald so that non-journald-aware services get logged. This is probably causing duplication in your output. I recommend only enabling the `fmt` layer if `isatty` returns 1 for stdout.

Hmm, could be worth adding something to the docs about this if we don't already have a note?

**Comment by khionu** [comment]
I don't think that quite explains why there are 5 datetimes there.

**Comment by Ralith** [comment]
If you think there's something else going on, post a self-contained repro that demonstrates it.
