### ISSUE TITLE
[Question] what's the relationship between span level and event level?

### ISSUE THREAD

**Issue by danieleades** [tokio-rs/tracing#1451]
Just started playing around with this crate, and i'm seeing some behaviour that i don't fully understand.

I have an asynchronous function decorated with `#[instrument(level="info")]` (yes i know that 'info' is *currently* the default). I would expect to see that span logged at the 'info' level. I'm using 'tracing_subscriber' with the default setup (`tracing_subscriber::fmt::init();`), and running the binary with `RUST_LOG=info cargo run`. With this setup I don't see any log output to stdout.

- if i make the logging more verbose (`RUST_LOG=debug cargo run`) I can see that entering and exiting the span are logged at debug level
- if i create `event`s inside the span at info level they are logged at info level.
- is there any relationship between the level of the event and the the level of the enclosing span?

I feel like i'm probably just misunderstanding the expected behaviour here

**Comment by danieleades** [comment]
i *think* i've answered my own question- ['span events'](https://docs.rs/tracing-subscriber/0.2.19/tracing_subscriber/fmt/struct.SubscriberBuilder.html#method.with_span_events) seems to do what i'm looking for

**Comment by davidbarsky** [comment]
`tracing_subscriber::fmt::Subscriber`, by default, only emits span data when an event occurs. If you want to emit span data independent of events occurring, I suggest using looking at [`tracing_subscriber::fmt::SubscriberBuilder::with_span_events`](https://docs.rs/tracing-subscriber/0.2.19/tracing_subscriber/fmt/struct.SubscriberBuilder.html#method.with_span_events).

And yup, apologies. I forgot to post my response.
