### ISSUE TITLE
tracing-telemetry wasn't released alongside all the other crates

### ISSUE THREAD

**Issue by Eijebong** [tokio-rs/tracing#1462]
`tracing-opentelemetry` has been bumped to 0.14 (with the dependency on opentelemetry 0.15 bump) in the repository but it wasn't published on crates.io. Is that intentional?

**Comment by hawkw** [comment]
nope, i think we just forgot to publish the release --- i'll get it out today!

**Comment by Eijebong** [comment]
Looks like it's been released, let's close this :)
