### ISSUE TITLE
tracing-journald pulling in default features of dependencies

### ISSUE THREAD

**Issue by themaxdavitt** [tokio-rs/tracing#1465]
### Version

```
├── tracing v0.1.26
│   ├── tracing-attributes v0.1.15 (proc-macro)
│   └── tracing-core v0.1.18
├── tracing-journald v0.1.0
│   ├── tracing-core v0.1.18 (*)
│   └── tracing-subscriber v0.2.19
│       ├── tracing v0.1.26 (*)
│       ├── tracing-core v0.1.18 (*)
│       ├── tracing-log v0.1.2
│       │   └── tracing-core v0.1.18 (*)
│       └── tracing-serde v0.1.2
│           └── tracing-core v0.1.18 (*)
└── tracing-subscriber v0.2.19 (*)
```

### Platform

Not relevant.

### Description

I was looking to reduce the size of my dependency tree and noticed that [`tracing-journald` is pulling in the default features of `tracing-core` and `tracing-subscriber`](https://github.com/tokio-rs/tracing/blob/master/tracing-journald/Cargo.toml#L18-L19), which adds many unneeded dependencies (this can be partially seen in the version section, e.g. I don't need `tracing-serde`). I'm not the most familiar with the `tracing` ecosystem but I believe this is unnecessary.

**Comment by hawkw** [comment]
Yup, we should fix that --- good catch, thanks for reporting!

**Comment by lunaryorn** [comment]
@hawkw Could you make a release of tracing-journald with this change included?

**Comment by lunaryorn** [comment]
@hawkw Ping 😊
