### ISSUE TITLE
Explore whether to use syn-md

### ISSUE THREAD

**Issue by davidbarsky** [tokio-rs/tracing#15]
[syn-mid](https://github.com/taiki-e/syn-mid) seems like an interesting library that provides constructs such as “functions whose bodies aren't parsed” and “blocks whose bodies aren't parsed”. This might help with some of the attribute macros.

**Comment by yaahallo** [comment]
I'm interested in taking a look at this.

**Comment by davidbarsky** [comment]
@yaahallo That'd be great! I also tried out [Darling](https://github.com/TedDriggs/darling/) in another library which treats procedural macros like Serde attributes—it might be a worthwhile thing to consider. The best examples I've seen for Darling were in their [integration tests folder](https://github.com/TedDriggs/darling/tree/master/tests).

**Comment by hawkw** [comment]
I'm unsure if this is still relevant, since in order to support async functions, I think we _do_ need to actually interact with function bodies?

**Comment by yaahc** [comment]
I say CLOSE IT
