### ISSUE TITLE
tracing-subscriber: `self.subscribe` called twice

### ISSUE THREAD

**Issue by bigdogs** [tokio-rs/tracing#1515]
## Bug Report

https://github.com/tokio-rs/tracing/blob/master/tracing-subscriber/src/subscribe.rs
![image](https://user-images.githubusercontent.com/20614926/129922604-1f002f68-0a17-4c80-8db0-c22f36c9d19c.png)

seems it should be `self.inner.enabled(metadata, ctx)` according to the comments

**Comment by hawkw** [comment]
Yup, that definitely looks wrong to me. Are you interested in opening a PR to fix this?

**Comment by davidbarsky** [comment]
Whoops, `git blame` says that it's my fault. Hold on, sending a PR.
