### ISSUE TITLE
`tracing_subscriber::filter::ParseError` no longer publicly visible with version 0.2.21

### ISSUE THREAD

**Issue by adoerr** [tokio-rs/tracing#1557]
This might be a regression.

`tracing_subscriber::filter::ParseError` stopped to be publicly visible/accessible with version `0.2.21`. It was with version `0.2.20` and below.

This can also easily be checked by looking at the Doc

[0.2.20](https://docs.rs/tracing-subscriber/0.2.20/tracing_subscriber/filter/index.html)

vs

[0.2.21](https://docs.rs/tracing-subscriber/0.2.21/tracing_subscriber/filter/index.html)

**Comment by hawkw** [comment]
Yup, that's definitely a regression. I accidentally renamed this type in PR #1550 after getting confused by a renaming import...sorry about that. We'll get a new release out that fixes that right away!

**Comment by hawkw** [comment]
Okay, I've [released v0.2.22](https://crates.io/crates/tracing-subscriber/0.2.22) and [yanked v0.2.21](https://crates.io/crates/tracing-subscriber/0.2.21) to hopefully minimize the breakage for other users. Thanks for the bug report, and sorry for any inconvenience!
