### ISSUE TITLE
subscriber: High performance span store

### ISSUE THREAD

**Issue by hawkw** [tokio-rs/tracing#157]
### Crates

`tracing-subscriber`

### Motivation

In many use cases, `Subscriber` implementations will need to store data for each span over the course of that span's lifetime. Since the `Subscriber` interface is based on `&self` references, and a single subscriber is shared across multiple threads, storing mutable per-span data requires some kind of locking.

The naïve approach is to store spans in a `RwLock<HashMap<Id, PerSpanData>>` or similar structure, but this is not ideal; introducing a global lock means that any access to the span store by the subscriber is a global synchronization point. Instead, it's almost certainly better to use more granular locking, so that modifying the data for unrelated spans on two different threads need not cause the whole program to synchronize.

More granular approaches can be more complex to implement than using a simple global lock. So that subscriber implementations need not reinvent the wheel, the `tracing-subscriber` crate ought to provide batteries-included structures for storing per-span data.

### Proposal

The tokio threadpool (and other work-stealing executors) try hard to ensure that individual tasks remain on the same worker thread, and that spans are often attached to a task, we should consider optimizing for a case where span accesses from the same thread are common but spans move across threads infrequently. Given this, a good approach might be one where the locking of span data is sharded by the thread where the span was created, in order to make access fast in the common case. When a span's data is used from another thread, we can "steal" the span from the thread where its data was previously used, a slower operation that's okay for the less common case.

### Alternatives

There are other potential solutions to a fast span store. For example, tracing-fmt uses a slab where each entry (span) has its own lock. This may also be worth investigating.

**Comment by davidbarsky** [comment]
From a discussion on Gitter with @hawkw. The current front-runner for the global span store is: `Arc<RwLock<Vec<RwLock<T>>>`. Annotated, each type handles:
- `Arc`: global atomic access.
- first `RwLock`: has contention on the span store. One optimization avenue is that the span store is  sharded per-thread to reduce contention. If we are sharing per-thread, there might be an optimization opportunity to replace `Arc` with `Rc`.
- `Vec`: the span store with fast indexing approach where Span Ids are stored out of band. See http://www.ilikebigbits.com/2014_04_21_myth_of_ram_1.html for more details.
- second `RwLock`:  Maintains a lock on the span where contention is, in practice, is _extremely_ rare.
- `T`: the span itself.

**Comment by davidbarsky** [comment]
The entire store might not need to be refcounted, as the store would live in a subscriber that is already refcounted by a Dispatcher.

**Comment by hawkw** [comment]
For those of you following along at home, I _am_ still working on this. I know it's been pretty silent, but I just published an experimental first release of a [lock-free slab](https://github.com/hawkw/sharded-slab) that I believe should offer the right performance characteristics to serve as the core for a span store abstraction. 

My plan is to replace the storage layer in `tracing-subscriber`'s `fmt` module with `sharded-slab`, do some benchmarking, and then put together a span store abstraction on top of that which should be suitable for use in subscriber implementations.
