### ISSUE TITLE
Documents on docs.rs does not work well

### ISSUE THREAD

**Issue by EFanZh** [tokio-rs/tracing#1571]
### Version

0.1.27

### Description

See <https://docs.rs/tracing/0.1.27/tracing/>, there are two problems:

1. The search text box does not work:

  ![](https://user-images.githubusercontent.com/2160692/133580815-0a750a68-f4d2-4e25-b91d-1f2d24987bba.png)
2. The layout of the bottom part seems broken.

  ![](https://user-images.githubusercontent.com/2160692/133580841-67170f9c-bad5-40ef-b7e1-9be5cd6b7314.png)

**Comment by hawkw** [comment]
[fixed in 0.1.28](https://docs.rs/tracing/0.1.28/tracing/), sorry about that!
