### ISSUE TITLE
Please add a big, noticeable warning to tracing.rs that says, that the docs are not up-to-date

### ISSUE THREAD

**Issue by d4h0** [tokio-rs/tracing#1592]
Hi,

Today I tried to set up `tracing` for a project and ran into a strange problem:

I used [tracing::collect::set_global_default](https://tracing.rs/tracing/collect/fn.set_global_default.html) to set up a custom subscriber, but I always got a "could not find `collect` in `tracing`" error.

I tried everything I could think of (checking if I use the latest version, `cargo clear`, checking Cargo.lock, searching the internet, etc.), but nothing resolved the problem.

At some point I thought: "Maybe the docs on tracing.rs differ from the docs on docs.rs..."

(Please note, that the link above points to tracing.rs, which I found via Google)

...and that was exactly the case.

On docs.rs I found [tracing::subscriber::set_global_default](https://docs.rs/tracing/0.1.28/tracing/subscriber/fn.set_global_default.html), which works.

While writing this issue, I noticed the "Version 0.2.0" in the sidebar of the linked tracing.rs link. I think that is not noticeable enough. Normally, there is "Go to the last version" link at the top (which I'm pretty sure, I have clicked on tracing.rs when I first arrived).

I'm wondering if it would be possible to add a big warning to tracing.rs that says, that the docs are not up-to-date. Or even better, to either remove the docs from tracing.rs, or to redirect to the docs on docs.rs.

This problem was pretty frustration, and took me some time to figure out, so I think it would be great to resolve the issue so nobody else runs into it.

**Comment by hawkw** [comment]
Yeah, the `tracing.rs` docs are automatically generated from the `master` branch, which is currently a development branch for the upcoming v0.2 version; they are not for the current release version. You're not the first person to be confused by this,  and we've been discussing changing it.

One change we've been considering is not hosting the `master` branch documentation at `tracing.rs/`, and instead moving them to a path like `tracing.rs/docs/master` or `tracing.rs/docs/v0_2/` or something. The main `tracing.rs/` would either redirect to the `docs.rs` documentation for the latest _released_ version, or eventually have a page listing the various crates and linking to their docs, and mentioning that documentation for the latest dev builds from the master branch are also available.

It would also be nice to have a way to add a warning or something to the generated docs from `master`, like you've mentioned. I'm not sure if there is an easy way to get RustDoc to do that, though, so we'd need to figure out a manual way of adding that warning.

**Comment by d4h0** [comment]
> One change we've been considering is not hosting the master branch documentation at tracing.rs/, and instead moving them to a path like tracing.rs/docs/master or tracing.rs/docs/v0_2/ or something. The main tracing.rs/ would either redirect to the docs.rs documentation for the latest released version, or eventually have a page listing the various crates and linking to their docs, and mentioning that documentation for the latest dev builds from the master branch are also available.

That sounds good. I think, something like `tracing.rs/docs/master/` would be a bit more obvious, as not everyone has memorized the current version of the `tracing` crate. It probably also would make sense to not let Google index the docs of the master branch (see [Block Search indexing with 'noindex'](https://developers.google.com/search/docs/advanced/crawling/block-indexing)).

> It would also be nice to have a way to add a warning or something to the generated docs from master, like you've mentioned. I'm not sure if there is an easy way to get RustDoc to do that, though, so we'd need to figure out a manual way of adding that warning.

The [--html-before-content](https://doc.rust-lang.org/rustdoc/command-line-arguments.html#--html-before-content-include-more-html-before-the-content) command line option of `RustDoc` looks like the way to go.

The `noindex` meta tag could be added via the [--html-in-header](https://doc.rust-lang.org/rustdoc/command-line-arguments.html#--html-in-header-include-more-html-in-head) to the `head` element of every page.

**Comment by hawkw** [comment]
> The [--html-before-content](https://doc.rust-lang.org/rustdoc/command-line-arguments.html#--html-before-content-include-more-html-before-the-content) command line option of `RustDoc` looks like the way to go.

Oh, today I learned that this exists! That's exactly what we would want!

**Comment by hawkw** [comment]
@davidbarsky have you had time to look into this?
