### ISSUE TITLE
proc-macros: fix dependency upon `#[macro_use] extern crate tracing;`

### ISSUE THREAD

**Issue by yaahc** [tokio-rs/tracing#162]
Right now you cannot use `tracing-proc-macros` without a macro use statement for the main tracing crate. Otherwise you run into some hidden items that it assumes are exported while they are not.

Alternatively, it would be nice to add a prelude to `tracing`

**Comment by hawkw** [comment]
A prelude is probably worth having at this point, but that is maybe a separate issue.

**Comment by hawkw** [comment]
I think just changing the proc-macro generated code to use `tracing`'s macro as `tracing::MACRO_NAME` rather than `MACRO_NAME` is sufficient to fix this.

**Comment by hawkw** [comment]
(btw, I opened #167 for adding a prelude)
