### ISSUE TITLE
The provenance of tracing-subscriber/src/fmt/time/datetime.rs appears to be troubled

### ISSUE THREAD

**Issue by krasimirgg** [tokio-rs/tracing#1644]
### Version
Crate tracing-subscriber, AFAICT versions since https://github.com/tokio-rs/tracing/commit/56b841de2cc5d5d181336edb5c11e340ac05c43e, including the current master branch.
### Description
The provenance of the code in datetime.rs appears to be troubled: per comments on code etc, it appears to have started as musl code (MIT license), gone through c2rust and been given manual edits (those edits in the scope of an Apache-2.0 licensed project, so presumably those edits are Apache-2.0), and then been copied into this codebase as MIT. Could we replace that code with something that has a clearly MIT-licensed provenance, or switch this package to explicitly be MIT AND Apache-2.0 licensing?
https://github.com/tokio-rs/tracing/blob/56b841de2cc5d5d181336edb5c11e340ac05c43e/tracing-subscriber/src/fmt/time/datetime.rs#L16

**Comment by hawkw** [comment]
Copying the code from `kudu-rs` (the Apache-2.0 project) was suggested by @danburkert, the maintainer of that project: https://github.com/tokio-rs/tracing/issues/791#issuecomment-656482155

Because it was Dan's suggestion, I didn't take the time to double-check that the two projects were compatibly licensed. My bad.

**Comment by danburkert** [comment]
My opinion (and I'm far from having a sophisticated understanding of copyright) is that `datetime.rs` is entirely derivative of musl's `__secs_to_tm.c`, and therefore I don't believe I hold copyright on it.  If that's wrong and I do hold copyright on it, I release it under as ASL 2.0 or MIT.

**Comment by danburkert** [comment]
Thanks for fixing @krasimirgg.  This has got me thinking, this code is now copied into tracing which itself is a dependency of `rustc`.  It'd be really nice if it were upstreamed as a Display impl on SystemTime.  I personally have copied it to another closed-source codebase (in addition to kudu-rs), and I'm considering copying it into `prost-types` as well.  I'd love if it were upstreamed, time willing I may start an internals thread to do so, but if anyone wants to take the torch then by all means.

**Comment by krasimirgg** [comment]
Thank you for updating the 0.3 version! Could you also cherry pick this into the 0.2.x version of [the crate over at crates.io](https://crates.io/crates/tracing-subscriber/versions) if possible? This will be handy since the 0.2.x version [is still a dependency of some rustc components](https://github.com/rust-lang/rust/search?q=tracing-subscriber) and [of tracing-tree](https://github.com/davidbarsky/tracing-tree/blob/4f5635ec0e79f78e49d321ec8df208c879c76afb/Cargo.toml#L13), which is itself a rustc dependency.

**Comment by davidbarsky** [comment]
@krasimirgg it's going to be somewhat painful for us to update 0.2. I can, however, spend some time on updating `tracing-tree` so that rustc can move to `tracing-subscriber 0.3`.

**Comment by krasimirgg** [comment]
> @krasimirgg i suspect that it's going to be somewhat painful for us to update 0.2. I can, however, spend some time on updating `tracing-tree` so that rustc can move to `tracing-subscriber 0.3`. Would that work for you?

This sounds good! It would leave us with just [the rustc_driver](https://github.com/rust-lang/rust/blob/8b954910c59a7a362c60959e93110892b6e9a691/compiler/rustc_driver/Cargo.toml#L13) (and some additional rustc tools) that directly depend on `tracing-subscriber 0.2`, which I guess will be OK to bump to `tracing-subscriber 0.3`.
