### ISSUE TITLE
Support Local timezone config from tracing_appender 

### ISSUE THREAD

**Issue by 18601673727** [tokio-rs/tracing#1645]
Dear fellas,

Using below configuration giving me hard time to figure out what was the correct hour it supposed to mean.
```rs
let file_appender = tracing_appender::rolling::hourly("/path/to/my/logs", "prefix");
```
So I'm wondering anybody here could kindly add one more option like this for me?
```rs
let file_appender = tracing_appender::rolling::hourly("/path/to/my/logs", "prefix", ChronoLocal);
```
Thanks in advance!

**Comment by 18601673727** [comment]
@davidbarsky Sorry to bother you again, encountered a strange situation by using following code:
```rs
tracing_subscriber::fmt()
    .with_env_filter(EnvFilter::from_default_env())
    .with_timer(LocalTime::rfc_3339())
    .init();
```
The `stdout` could print logs on Windows, but not on MacOS tried following toolchains:
```
➜ rustup toolchain list
stable-x86_64-apple-darwin (default)
nightly-x86_64-apple-darwin
```

**Comment by davidbarsky** [comment]
@18601673727 not bothering! I think the issues that you're running into with `LocalTime` stem from https://github.com/tokio-rs/tracing/pull/1699. Can you try passing `--cfg unsound_local_offset` to your Cargo build?

**Comment by 18601673727** [comment]
Thank you @davidbarsky! 

Don't know if I was doing this correctly but it seems not working  
```
➜ cargo build --cfg unsound_local_offset
error: Found argument '--cfg' which wasn't expected, or isn't valid in this context
```

**Comment by Borber** [comment]
Is this still expected to be supported?

**Comment by curtiseng** [comment]
Is tracing_appender suppoert split file use localtime?

**Comment by Borber** [comment]
> Is tracing_appender suppoert split file use localtime?

yes https://docs.rs/tracing-appender/latest/tracing_appender/index.html#non-blocking-rolling-file-appender

**Comment by cbbb8533** [comment]
> > Is tracing_appender suppoert split file use localtime?
> 
> yes https://docs.rs/tracing-appender/latest/tracing_appender/index.html#non-blocking-rolling-file-appender

still rely on utc！！！forbid misleading the public

**Comment by Borber** [comment]
> > > Is tracing_appender suppoert split file use localtime?
> > 
> > 
> > yes https://docs.rs/tracing-appender/latest/tracing_appender/index.html#non-blocking-rolling-file-appender
> 
> still rely on utc！！！forbid misleading the public

so sorry

**Comment by kokokobe** [comment]
two years past. this log file name hour time error fixed yet?

**Comment by davidbarsky** [comment]
I don't think we can reasonably support this feature in `tracing-appender` for the following reasons:
- I'm not sure how to expose this in a way that is independent over `time` or `chrono`. We don't want to pick one or bump `tracing-appender`'s version because chrono/time bumped _their_ version—we want to minimize public dependencies.
- Logging in the local time, instead of UTC, is probably an anti-feature. Every place I've worked at regretted that decision and either spent *years* moving to UTC or gave up entirely.
    - I don't want to make this potential misstep easier for people, _especially_ when semi-durable state is involved.
    - As an example, how would this feature handle daylight savings? What should we with the file corresponding to the hour that [got turned back](https://en.wikipedia.org/wiki/Daylight_saving_time#Procedure)?
- Given that none of the current `tracing` maintainers use `tracing-appender` at our jobs, it's difficult to justify to spend a decent amount of time working on this. If, despite the concerns I've outlined above are non-issues in your situation, I highly recommend forking `tracing-appender` and implementing the functionality that you're looking.

**Comment by Rhysol** [comment]
Could you support an option to choose between UTC time and local time? We would really appreciate it.

**Comment by JSLJ23** [comment]
> Could you support an option to choose between UTC time and local time? We would really appreciate it.

It is quite straightforward to write your own `RollingFileAppender` and pass it to the `tracing_appender`.

Here's a small snippet of a `LocalDailyAppender` that uses the local time from `Local::now().date_naive()` and updates the daily log file name based on the local time.

```rust
use chrono::{Local, NaiveDate};
use std::fs::{File, OpenOptions};
use std::io;
use std::io::Write;
use std::path::{Path, PathBuf};
use tracing_appender::non_blocking;
use tracing_appender::non_blocking::WorkerGuard;
use tracing_subscriber::fmt::time::LocalTime;
use tracing_subscriber::{EnvFilter, fmt};

fn open_log_file(dir: &Path, name: &str, date: NaiveDate) -> io::Result<File> {
    let filename = format!("{}_{}.log", name, date.format("%Y-%m-%d"));
    OpenOptions::new()
        .create(true)
        .append(true)
        .open(dir.join(filename))
}

struct LocalDailyAppender {
    directory: PathBuf,
    name: String,
    current_date: NaiveDate,
    file: File,
}

impl LocalDailyAppender {
    fn new(directory: impl AsRef<Path>, name: impl Into<String>) -> io::Result<Self> {
        let directory = directory.as_ref().to_path_buf();
        std::fs::create_dir_all(&directory)?;
        let name = name.into();
        let current_date = Local::now().date_naive();
        let file = open_log_file(&directory, &name, current_date)?;
        Ok(Self {
            directory,
            name,
            current_date,
            file,
        })
    }

    fn rotate_if_needed(&mut self) -> io::Result<()> {
        let today = Local::now().date_naive();
        if today != self.current_date {
            self.file.flush()?;
            self.current_date = today;
            self.file = open_log_file(&self.directory, &self.name, today)?;
        }

        Ok(())
    }
}

impl Write for LocalDailyAppender {
    fn write(&mut self, buf: &[u8]) -> io::Result<usize> {
        self.rotate_if_needed()?;
        self.file.write(buf)
    }

    fn flush(&mut self) -> io::Result<()> {
        self.file.flush()
    }
}

pub fn initialise() -> WorkerGuard {
    let file_appender = LocalDailyAppender::new("logs", "app")
        .expect("Failed to create log file appender.");
    let (writer, guard) = non_blocking(file_appender);
    let filter = EnvFilter::try_from_default_env().unwrap_or_else(|_| EnvFilter::new("info"));
    fmt()
        .compact()
        .with_timer(LocalTime::rfc_3339())
        .with_env_filter(filter)
        .with_writer(writer)
        .with_ansi(false)
        .with_target(false)
        .with_file(true)
        .with_line_number(true)
        .init();

    guard
}
```
