### ISSUE TITLE
tracing: bug in message-less event macro calls

### ISSUE THREAD

**Issue by yaahallo** [tokio-rs/tracing#165]
```
scale/src/settings.rs|86 col 27 error| expected expression, found `?`
||    |
|| 86 |                     warn!(?e);
||    |                           ^ expected expression
```

where e is a `std::boxed::Box<(dyn std::error::Error + std::marker::Send + std::marker::Sync + 'static)>`

**Comment by hawkw** [comment]
Looks like this is specifically a bug with _single_ shorthand fields in macros due to the way we handle trailing commas. Fixing it!
