### ISSUE TITLE
`LevelFilter` documents its comparison logic as the opposite of reality

### ISSUE THREAD

**Issue by lilyball** [tokio-rs/tracing#1669]
### Version

Current published `tracing-core` and `tracing`, as well as the version currently documented on tracing.rs.

### Crates

tracing-core

### Description

The [documentation for `LevelFilter`](https://docs.rs/tracing-core/0.1.21/tracing_core/struct.LevelFilter.html) states

> If a `Level` is considered less than a `LevelFilter`, it should be considered disabled; if greater than or equal to the `LevelFilter`, that level is enabled.

This is the exact opposite of how it works. `LevelFilter` compares the same way `Level` does, where `ERROR` is the lowest level and `TRACE` is the highest, with the addition of `OFF` as comparing less than `ERROR`. So the intended logic here is "if a `Level` is less than or equal to a `LevelFilter` it should be considered enabled; if greater than the `LevelFilter`, that level is disabled". Thankfully the `LevelFilter::current()` documentation is correct.

It would also be lovely to have a code sample added that demonstrates comparing a level against `LevelFilter::current()`, to help demonstrate how such comparisons work.

Side note: the `LevelFilter::current()` docs have a stray `` ` `` at the end.

**Comment by juumixx** [comment]
I noticed that this was probably not intentional, due to a mistake in the underlying comparison functions (see #2367). Wouldn't it be better to fix the implementation than to adjust the documentation to the unexpected behavior?

**Comment by davidbarsky** [comment]
@juumixx (responding here for any readers who might be following along)

I explained why this is intentional on https://github.com/tokio-rs/tracing/issues/2367#issuecomment-1303863389. The documentation issue was unfortunate, but that's because there are several moving parts.

**Comment by juumixx** [comment]
Thanks, I guess whoever wrote the documentation was likewise confused by the behavior as I was.
