### ISSUE TITLE
tracing-journald release

### ISSUE THREAD

**Issue by imbolc** [tokio-rs/tracing#1707]
Could you please release and publish the current `tracing-journald` version? The v0.2 was published more than a year ago and isn't compatible with the current subscriber. I can't just use the git version as I want to implement `tower-http::MakeSpan::make_span() -> Span` and it wants a published `Span`.

**Comment by hawkw** [comment]
The current `master` branch of this repository is the development branch for the upcoming v0.2 version of `tracing`. The currently released v0.1.x ecosystem can be found on the [`v0.1.x` branch](https://github.com/tokio-rs/tracing/tree/v0.1.x). If you need to take a Git dependency on a crate in this repository, you should depend on the `v0.1.x` branch, not the `master` branch.

The only unreleased change in the version of `tracing-journald` on `master` that isn't in the currently released version is that the version on `master` depends on `tracing-core` 0.2, which isn't released yet. So, the `master` version can't be released. Instead, new releases will be published from the `v0.1.x` branch. I don't believe the `v0.1.x` `tracing-journald` currently has any changes that aren't present in the `tracing-journald` 0.2 that's currently published.
