### ISSUE TITLE
journald: Do not log additional string data in Debug representation

### ISSUE THREAD

**Issue by lunaryorn** [tokio-rs/tracing#1710]
## Bug Report

Follow up from https://github.com/tokio-rs/tracing/pull/1709#discussion_r743202676

### Description

`tracing-journald` currently logs additional string fields in their `Debug` representation, i.e. this code

```
info!(foo="foo", "test")
```

writes `FOO="foo"` to the journal, i.e. with extra quotes from `format!("{:?}")`.

I expected `FOO=foo`, i.e. a regular string.

**Comment by lunaryorn** [comment]
@Ralith You've said over in the merge request that this is intended because it helps distinguish between 1 as a number, and 1 as a string, which one couldn't if strings were logged directly.

I understand the motivation, but my concern is that this effectively requires downstream consumers of the journal to "unparse" Rust's `Debug` representation in order to get the original string back out. 

It also seems rather unusual to add extra formatting to field values, as far as I can see: The [slog implementation](https://github.com/slog-rs/journald/blob/master/src/lib.rs#L156) uses `Display`, not `Debug`, and I superficially (my C's a bit rusty :wink: ) checked Glib's structured logging code, and it seems to treat all fields as strings upfront, unless they contain internal NULs.

**Comment by Ralith** [comment]
On review I think I agree; the common case (especially in idiomatic journald clients) of working with strings trumps the rather weird case of meaningfully dynamically-typed fields. I'd be happy to approve a fix.

**Comment by lunaryorn** [comment]
I'll make a MR after the tests are merged.

We can also have a flag, similar to the field prefix, to toggle between the literal and the debug representation of strings, if you like 🙂

**Comment by Ralith** [comment]
Eh, I'd rather avoid the complexity.

**Comment by lunaryorn** [comment]
Absolutely fine with me :slightly_smiling_face: I'll make a merge request after #1709 

@Ralith Thanks for your great support and your help :pray:

**Comment by Ralith** [comment]
Thanks for the contributions!
