### ISSUE TITLE
core: consider adding `Dispatch::default`

### ISSUE THREAD

**Issue by hawkw** [tokio-rs/tracing#172]
### Crates

`tracing-core`

### Motivation

`tracing-core` currently exposes access to the default dispatcher through the `get_default` function. This allows users to provide a closure that's executed with a reference to the default dispatcher. The dispatcher can then be cloned if an owned `Dispatch` is needed:
```rust
let dispatch = dispatcher::get_default(|default| default.clone());
```
This is a bit awkward to use.

### Proposal

We could have a `Default` impl for `Dispatch` that calls `get_default` and clones the default dispatcher. This is similar to the approach used by `tokio-executor` and `tokio-timer`.

### Alternatives

Alternatively, we could...not do that. These are lower-level APIs that users of `tracing` should, in most cases, not have to interact with. Although adding convenience APIs for getting the dispatcher might make it easier to work with, in practice, this API should be consumed primarily by the instrumentation API. 

If users find themselves cloning the current default dispatcher often, that's probably a sign of missing higher-level functionality in `tracing`.

**Comment by LucioFranco** [comment]
Yes.

I think this is worth it I've had to do it many times to manually propagate the sub.

Example: https://github.com/timberio/vector/blob/master/src/sources/file.rs#L96

**Comment by hawkw** [comment]
Okay, I think this should be fairly easy to add if anyone is interested, and it sounds like there's desire for this.

We would essentially just add a `Default` implementation for `Dispatch` that calls `dispatcher::get_default` and clones the default.

**Comment by lunchboxav** [comment]
@hawkw I'm wondering, whether or not this piece of code sufficient for this issue

```
    pub fn default(&self){
        get_default(|default| default.clone());
    }
```

**Comment by hawkw** [comment]
@lunchboxav yeah, that's basically it, although your function is missing a return type and takes an argument that it doesn't need (it should be `fn default() -> Self`). However, rather than adding a new inherent method to `Dispatch`, we'd want to add this in an implementation of the standard library's [`Default` trait](https://doc.rust-lang.org/std/default/trait.Default.html). 

If you're interested in making this change, that should hopefully be enough for you to get started, but let me know if you have any more questions!

**Comment by lunchboxav** [comment]
like so @hawkw 

```
impl Default for Dispatch {
    // Creates default dispatcher
    fn default() -> Self {
        get_default(|default| default.clone())
    }
}
```

also, what kind of test do I need to supply?

**Comment by lunchboxav** [comment]
is this kind of test enough to test that the Dispatcher is created with default config?

```rust
 #[test]
    fn create_default_dispatcher() {
        let default_dispatcher = Dispatch::default();
        assert!(default_dispatcher.is::<NoSubscriber>());
    }
```
