### ISSUE TITLE
meta: move CI to Azure Pipelines

### ISSUE THREAD

**Issue by hawkw** [tokio-rs/tracing#177]
### Motivation

The rest of Tokio uses Azure Pipelines rather than Travis for CI. I believe Azure Pipelines builds tend to be much faster than Travis, and the integration with GitHub's status checks is nicer.

### Proposal

It would be nice to replace our Travis build with Azure Pipelines. We'll have to bear in mind that our CI build is currently a bit more complex than just `cargo build --all`; we also have:
+ A job that runs separate builds for the feature-flag test crates in `tracing`:
https://github.com/tokio-rs/tracing/blob/ebacde012f2ebe33664b6592127d1cf5562ff810/.travis.yml#L17-L21
+ A `rustfmt` check:
https://github.com/tokio-rs/tracing/blob/ebacde012f2ebe33664b6592127d1cf5562ff810/.travis.yml#L22-L25
+ A job that tests the README examples:
https://github.com/tokio-rs/tracing/blob/ebacde012f2ebe33664b6592127d1cf5562ff810/.travis.yml#L26-L28

We'll want to make sure that a new Azure Pipelines builds runs these checks as well.

There are also some things we're currently _not_ doing on CI that would be nice to add:
+ Publish docs on master builds to GitHub pages? 
+ Code coverage?
+ Benchmarks??

**Comment by hawkw** [comment]
@jonhoo I believe you have a big Azure Pipelines template that you've been using in `tracing-timing`? Is this something you're interested to help with?

**Comment by jonhoo** [comment]
Sure, yeah! I think this is all very doable. You should be able to get quite far by building on top of https://github.com/jonhoo/tracing-timing/blob/master/azure-pipelines.yml. The one drawback currently is [this issue](https://developercommunity.visualstudio.com/content/problem/633563/multi-stage-pipelines-show-in-progress-github-chec.html), but apparently they're working on fixing it.
