### ISSUE TITLE
Tracing's log feature should not cause code that would otherwise compile to break

### ISSUE THREAD

**Issue by Noah-Kennedy** [tokio-rs/tracing#1793]
Currently, enabling the log feature in tracing can break code that would otherwise compile, which is a problem, as features are generally supposed to be additive. This leads to situations such as projects breaking when trying to use console, as Tonic enables the default features in tower, which enables this feature in tracing.

There has already been some discussion about this in the discord server.

Thread 1: https://discord.com/channels/500028886025895936/838895414455435335/905519088934211584
Thread 2: https://discord.com/channels/500028886025895936/838895414455435335/921838120788459561

**Comment by Noah-Kennedy** [comment]
Bumping this, it's been long enough and its a very easy problem to hit nowadays, especially with `console-subscriber`.

**Comment by hawkw** [comment]
I thought this issue was fixed in #1823? Are you still seeing errors with an up-to-date `tracing` dependency?

**Comment by Noah-Kennedy** [comment]
Yes, I am sadly seeing this in 1.33

**Comment by hawkw** [comment]
Can you share the error you're seeing? The issue fixed by #1823 is the only one I'm aware of, so I'd like to see if this is the same problem or a different one.

**Comment by Noah-Kennedy** [comment]
@hawkw I'll get an mcre up shortly

**Comment by Noah-Kennedy** [comment]
@hawkw I have an MCRE here: https://github.com/Noah-Kennedy/another-tracing-mcre

In a nutshell:
```rust
#[tokio::main(flavor = "current_thread")]
async fn main() {
    tracing_subscriber::fmt().init();
    tokio::spawn(do_request()).await.unwrap();
}

async fn do_request() {
    let response = reqwest::get("https://google.com").await.unwrap();
    tracing::info!("{}", response.text().await.unwrap());
}
```

This fails with `tracing/log` enabled because the future returned by `do_request` is no longer `Send`, but works without that feature. I suspect that this would work with any await held in that position. I shall attempt to minify further.

**Comment by Noah-Kennedy** [comment]
Got it working without reqwest:
```
#[tokio::main(flavor = "current_thread")]
async fn main() {
    tokio::spawn(do_request()).await.unwrap();
}

async fn do_request() {
    tracing::info!("{}", std::future::ready("test").await);
}
```

The `tokio::spawn` is basically just there to assert that the resulting future is `Send`.
