### ISSUE TITLE
can't compile tracing-subscriber with `--cfg unsound_local_offset` in macos because time still doesn't release patch

### ISSUE THREAD

**Issue by ulwlu** [tokio-rs/tracing#1805]
## Bug Report

can't compile tracing-subscriber with `--cfg unsound_local_offset` in macos because time still doesn't release patch

### Version

```
│   │   │   └── tracing v0.1.29
│   │   │       ├── tracing-attributes v0.1.18 (proc-macro)
│   │   │       └── tracing-core v0.1.21
│   │   ├── tracing v0.1.29 (*)
├── tracing v0.1.29 (*)
├── tracing v0.1.29 (*)
│   │   └── tracing v0.1.29 (*)
│   │   └── tracing v0.1.29 (*)
├── tracing v0.1.29 (*)
├── tracing-subscriber v0.3.4
│   ├── tracing v0.1.29 (*)
│   ├── tracing-core v0.1.21 (*)
│   ├── tracing-log v0.1.2
│   │   └── tracing-core v0.1.21 (*)
│   └── tracing-serde v0.1.2
│       └── tracing-core v0.1.21 (*)
```

### Platform

```
Darwin C02FK4Y8MD6R 20.6.0 Darwin Kernel Version 20.6.0: Tue Oct 12 18:33:42 PDT 2021; root:xnu-7195.141.8~1/RELEASE_X86_64 x86_64
```

### Crates

tracing-subscriber

### Description

tried to `RUSTFLAGS="--cfg unsound_local_offset" RUST_LOG=DEBUG cargo build` but failed on macos.
because time doesn't support it until v3.5 (master is fixed, but not released)

https://github.com/time-rs/time/blob/6b8cdd3d9ec07c027e3aa6b9c8a69f4e6fd568dd/src/sys/local_offset_at/unix.rs#L111-L129

So what i wonder is there any useful workaround without `RUSTFLAGS=**`  to use localtime timestamp?

**Comment by hawkw** [comment]
> So what i wonder is there any useful workaround without `RUSTFLAGS=**` to use localtime timestamp?

I just merged PR #1772, which adds an `OffsetLocalTime` API. This can be used to emit local timestamps with a _fixed_ offset determined when the program starts, without requiring the `unsound_local_offset` cfg flag. I'm hoping to publish a new `tracing-subscriber` release containing that API today.

Does that solve your problem?

**Comment by ulwlu** [comment]
wow today?! it's really great, thank you very much!
yes that sounds really good and solves my problem.

thank you for this great project as well.

**Comment by hawkw** [comment]
https://github.com/tokio-rs/tracing/releases/tag/tracing-subscriber-0.3.5 includes the new API :)
