### ISSUE TITLE
Support Global/Constant Metadata

### ISSUE THREAD

**Issue by kevincox** [tokio-rs/tracing#1815]
### Motivation

It is often helpful to include metadata such as code version, execution environment (production, development...). This would ideally be included in every event and span without needing to be explicitly attached throughout the application.

### Proposal

Some global function to set the global metadata. These would be attached to every span.

Alternatively some subscriber framework so that these attributes are attached just before the subscriber sees the events.

A possible downside is the cost, but the feature would be optional.

**Comment by davidbarsky** [comment]
I suggest creating a top-level span that lives as long as your application does that contains the data you're interested in as fields. Most subscribers (fmt, opentelemetry) will pull or render that top-level span's metadata, resulting in that data being _effectively_ attached to every span and event.

If you've got any additional questions, feel free to ask on Discord or open a GitHub discussion.
