### ISSUE TITLE
Tracking issue for updating tracing-opentelemetry to opentelemetry 0.17

### ISSUE THREAD

**Issue by djc** [tokio-rs/tracing#1824]
@jtescher I looked at this but I'm not getting very far. Are you sure the changes you made with regards to `parent_context()` in the `SpanBuilder` are compatible with how tracing-opentelemetry wants to do things?

**Comment by jtescher** [comment]
@djc looks simple enough to have a new struct that contains a builder and a context for a given tracing span. Something along the lines of https://github.com/tokio-rs/tracing/commit/3f04c628220069e32a755f46995423fb2cd6f4ab. Performance looks the same.

**Comment by djc** [comment]
Oh, good. Sorry, I guess I don't understand this code very well... it seems pretty complex.

**Comment by jtescher** [comment]
@djc so https://github.com/tokio-rs/tracing/pull/1853 does update to 0.17, but now we have an msrv mismatch (otel supports 1.46+, but compiles with 1.44, tracing requires 1.42). The only changes to support 1.42 would be making the functions that call `(to/from)_be_bytes` not const. e.g. [these](https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry/src/trace/span_context.rs#L110-L117).

**Comment by djc** [comment]
Seems like a straightforward fix then? Unless @hawkw is up for requiring 1.46 at this point, which seems reasonable.

**Comment by djc** [comment]
This work is done.
