### ISSUE TITLE
fmt: support `tracing-log` `log.XXX` fields nicely

### ISSUE THREAD

**Issue by hawkw** [tokio-rs/tracing#185]
`tracing-fmt` should format the `log.module`, `log.target`, `log.file`, and `log.line` fields the way it formats the same metadata on `tracing` events. The output will look nicer this way.

This should be pretty simple, and I'm happy to provide coaching if anyone is interested.

**Comment by amousset** [comment]
I'm interested in implementing this! I'm trying to figure out how this could be implemented and have a few questions. Why does the `Event` created from a log by `LogTracer` has empty `module_path`, `file` and `line`  and an hardcoded target in their `Metadata` but provides these values from the source log as fields instead? Do you think `tracing-fmt` should have a special case for logs coming from `LogTracer`?

**Comment by hawkw** [comment]
> Why does the `Event` created from a log by `LogTracer` has empty `module_path`, `file` and `line` and an hardcoded target in their `Metadata` but provides these values from the source log as fields instead? 

This is a workaround for a bit of an impedance mismatch between `log`'s API and `tracing`'s --- `log::Record`s have a generic `'a` lifetime, while `tracing::Metadata` is guaranteed to be `'static`. For context around this, there was some discussion in issue #78.

> Do you think `tracing-fmt` should have a special case for logs coming from `LogTracer`?

Yes, we can expect these field names to remain stable by convention.

**Comment by hawkw** [comment]
@amousset I've been thinking about this a bit, and I have some ideas for how I might recommend you implement this. This approach is a bit more complex than some of the alternatives, but is probably worth it in the long run, as it'll make working with `tracing-log` events easier for all subscriber implementations.

I think `tracing-log` should export an extension trait for events that has a method like
```rust
fn log_metadata(&self) -> &tracing::Metadata
```
(name TBD). We'd have a implementation of this for `Event`s. To implement this method, we would first check the event originates from one of `tracing-log`'s callsites. If it does not, we would just return the event's actual metadata. However, if the `Event` _is_ a `log` event, we would call `event.record` on it, with a visitor that collects the `log.module_path`, `log.file`, and `log.line` fields if they are present. We would expect the string fields to be recorded with `record_str` and the `log.line` field to be recorded with `record_u64`; if they aren't, we would ignore them. Once we've visited the event's fields and collected any `log` metadata values, we would use the fields stored on the visitor to construct a new `tracing::Metadata` with a shorter-lived lifetime.

Crates that implement `Subscriber`s, such as `tracing-fmt`, could then depend on `tracing-log`, and use this trait when recording event metadata. We would want to feature-flag this in `tracing-fmt` (although it could probably be on by default), so that users who are not using `tracing-log` can opt out of it. If the feature flag is not set, we would just always use the event's actual metadata.

What do you think?

**Comment by amousset** [comment]
Looks better than an special case in `tracing-fmt` indeed. Would you consider acceptable to completely ignore the fields of an `Event` from `tracing-log` in this case (as there can only be `log.module_path`, `log.file`, and `log.line` which would already be in the normalized Medatata anyway)?

**Comment by hawkw** [comment]
> Could this compatibility trait also have a kind of `normalized_record` method to allow filtering the fields that are already used in the normalized `Metadata`?

Yes, although perhaps we should add that later, as I want to write some utilities for filtering fields in `record` easier (#73), and that could be done using those tools. 

> Also, how to properly identify tracing-log's callsites from the `Event`?

The event's metadata has a [`Metadata::callsite`](https://docs.rs/tracing-core/0.1.2/tracing_core/metadata/struct.Metadata.html#method.callsite) method that returns an opaque `callsite::Identifier` type implementing `Eq`, which uniquely identifies the callsite that the metadata originated from. We can compare that `Identifier` with the identifier of the `tracing-log` callsite [that corresponds to the `Event`'s level](https://github.com/tokio-rs/tracing/blob/2cfc5130b64242a22b085ca06aa40e74c429a784/tracing-log/src/lib.rs#L54-L60); if they are equal, it's a `tracing-log` event, otherwise, it is not.

**Comment by amousset** [comment]
I started working on this, but have trouble implementing the proposed interface. As we need to create a new `Metadata` to hold the data extracted from the fields, we cannot simply return a reference to it. Similarly, collecting log metadata from fields requires storing them somewhere. I'm trying to push a minimal version soon.

**Comment by hawkw** [comment]
Fixed by #193.
