### ISSUE TITLE
Documentation for `Compact` and `Full` formats is wrong

### ISSUE THREAD

**Issue by lilyball** [tokio-rs/tracing#1880]
### Version

tracing-subscriber v0.3.7

### Crates

tracing-subscriber

### Description

The [documentation for `Compact`](https://docs.rs/tracing-subscriber/0.3.7/tracing_subscriber/fmt/format/struct.Compact.html) says

> The compact format only includes the fields from the most recently entered span.

The [documentation for `Full`](https://docs.rs/tracing-subscriber/0.3.7/tracing_subscriber/fmt/format/struct.Full.html) says

> The full format includes fields from all entered spans.

This distinction here is wrong. `Compact` in fact includes fields from all spans. It just moves the fields to the end of the event, after the event's kv pairs.

**Comment by hawkw** [comment]
Thanks for catching that --- those docs are clearly outdated! #1893 should fix this.
