### ISSUE TITLE
Release a new version of `tracing-log` with logging fix?

### ISSUE THREAD

**Issue by bnjbvr** [tokio-rs/tracing#1884]
Hi! Seeing that the latest version of tracing-log in Cargo.toml is marked to be 0.2.0, but the latest published version is less than that and is only 0.1.2 on crates.io.

[This commit](https://github.com/tokio-rs/tracing/commit/5fdbcbf61da27ec3e600678121d8c00d2b9b5cb1) contains an interesting performance fix that never made it to a release, and we would really like to be able to use it in our code base. Any chance a new version of this particular crate including that fix could be published, please? (Either as the 0.2.0 version, or as a 0.1.3 patch version, if the goal is to synchronize a release of 0.2.0 along other 0.2.0 crates)

**Comment by bnjbvr** [comment]
Gentle ping on this topic, is there any way I can help with this? Helping writing release notes, maybe?

**Comment by mati865** [comment]
I think this change should backported to branch 0.1 instead. 0.2 is still in the development.

**Comment by hawkw** [comment]
Fixed by #2086
