### ISSUE TITLE
Support Display trait for Level

### ISSUE THREAD

**Issue by singpolyma-shopify** [tokio-rs/tracing#189]
### Motivation

For simple logging cases, I just want to get the string `INFO` etc.  Currently there is a very verbose Debug but no Display.

### Proposal

Add impl of Display trait for Level.

**Comment by hawkw** [comment]
👍 this would be good to have. Should be pretty simple to implement if anyone is interested in contributing.

**Comment by hawkw** [comment]
(as a side note: it would also be nice to have a `FromStr` implementation for `Level`, based on [the impl in `tracing-fmt`](https://github.com/tokio-rs/tracing/blob/2cfc5130b64242a22b085ca06aa40e74c429a784/tracing-fmt/src/filter/env.rs#L301-L325), but I think that ought to be a separate issue)
