### ISSUE TITLE
tracing_subscriber::fmt().init() does not trace debug (does print info)

### ISSUE THREAD

**Issue by EdmundsEcho** [tokio-rs/tracing#1908]
## Bug Report

When the tracer is built using
```rust
tracing_subscriber::fmt().init();
// or
tracing_subscriber::fmt().pretty().init(); 
```
... the debug tracing does not show up.

### Version
tracing-subscriber = { version="0.3", features = ["env-filter", "fmt", "std"] }

```fish
cargo tree | grep tracing
│   │   │   └── tracing v0.1.29
│   │   │       ├── tracing-attributes v0.1.18 (proc-macro)
│   │   │       └── tracing-core v0.1.21
│   │   ├── tracing v0.1.29 (*)
│   │   └── tracing v0.1.29 (*)
│   │   └── tracing v0.1.29 (*)
├── tracing v0.1.29 (*)
├── tracing-subscriber v0.3.7
│   ├── tracing v0.1.29 (*)
│   ├── tracing-core v0.1.21 (*)
│   └── tracing-log v0.1.2
│       └── tracing-core v0.1.21 (*)
```

### Platform

MacOS 12.1 on M1

### Description

The following generates output 
```rust
✅  tracing::info!("\n 🔑 cookie: {:?}", cookie);
```

Whereas the following does not
```rust
🚫  tracing::debug!("\n 🔑 cookie: {:?}", cookie);
```

... only when I stop using the `fmt()` function, does the debug trace information show-up.
```rust
✅  tracing_subscriber::fmt::init();
```

\- E

**Comment by davidbarsky** [comment]
This is a known issue which is tracked in https://github.com/tokio-rs/tracing/issues/1697. I'll close this issue can ask that you follow that one instead.
