### ISSUE TITLE
Documentation for `Compact` format incorrectly states span names are not shown

### ISSUE THREAD

**Issue by lilyball** [tokio-rs/tracing#1909]
### Version

tracing-subscriber v0.3.8

### Crates

tracing-subscriber

### Description

In tracing-subscriber v0.3.8 (#1893) the [documentation on `Compact`](https://docs.rs/tracing-subscriber/0.3.8/tracing_subscriber/fmt/format/struct.Compact.html) was updated to say

> Span fields are not grouped by span, and span names are not shown.

The first half of this is true, but the second half is not, it does indeed show span names, it just doesn't group the fields with them. There's not even an option to hide them (`SubscriberBuilder::with_span_list()` exists but is only callable when formatting as JSON).

**Comment by hawkw** [comment]
Closed by #1926

**Comment by spking11** [comment]
0.3.23 still has this problem
