### ISSUE TITLE
Wrong log level in tracing macro warn

### ISSUE THREAD

**Issue by nicolaasg** [tokio-rs/tracing#1929]
https://github.com/tokio-rs/tracing/blob/4e65750b13721fee7a7ac05b053e1b9c3d21244f/tracing/src/macros.rs#L1698

I was scrolling through the code in tracing/src/macros.rs and noticed a possibly wrong log level in the warn macro.

**Comment by hawkw** [comment]
Whoops, that definitely looks wrong! Would you be interested in opening a pull request to fix that?
