### ISSUE TITLE
`tracing-opentelemetry 0.17.1` does not compile with `default-features = false`

### ISSUE THREAD

**Issue by yusdacra** [tokio-rs/tracing#1944]
### Version

`tracing 0.1`
`tracing-opentelemetry 0.17.1`
`opentelemetry 0.17`

### Platform

`Linux lungmen 5.16.7 #1-NixOS SMP PREEMPT Sat Feb 5 18:22:06 UTC 2022 x86_64 GNU/Linux`

### Crates

`tracing-opentelemetry` is affected.

### Description

`tracing-opentelemetry 0.17.1` with `default-features = false` fails to compile with:
```
error[E0282]: type annotations needed for `Option<T>`
   --> /home/patriot/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-opentelemetry-0.17.1/src/layer.rs:590:25
    |
588 |                     let normalized_meta = None;
    |                         --------------- consider giving `normalized_meta` the explicit type `Option<T>`, where the type parameter `T` is specified
589 |                     let (file, module) = match &normalized_meta {
590 |                         Some(meta) => (
    |                         ^^^^^^^^^^ cannot infer type for type parameter `T` declared on the enum `Option`
    |
    = note: type must be known at this point
```

**Comment by Yatekii** [comment]
I am having the same issue. It's obvious why it wont work, but it's absolutely not obvious to me how `cargo publish` worked with this in.

**Comment by hawkw** [comment]
I am also kind of surprised that `cargo publish` allowed this to happen. I think we should make sure that there's a CI job that builds with default features.
