### ISSUE TITLE
tracing-subscriber: please log that there was an error serializing an event

### ISSUE THREAD

**Issue by jaskij** [tokio-rs/tracing#1965]
## Feature Request

https://github.com/tokio-rs/valuable/issues/88 came because I realized that `tracing-subscriber`, specifically the json formatter, missed some of the logged events.

### Crates

`tracing-subscriber`

### Motivation

Logs, and traces, carry information. It is good to know that some of it was lost. In my case what failed to serialize was the error which caused abnormal termination.

### Proposal

If an event fails to serialize (whether in json or a different formatter), I'd like to see a new event generated, informing me about it. Best would be if this was optional, as I'm sure not everyone would want it.

### Alternatives

The other alternatives are to either silently ignore the failed event (what happens now), or panic. Panic seems unreasonably harsh, especially since `tracing` is used by long running services.

**Comment by bryangarza** [comment]
Resolved by https://github.com/tokio-rs/tracing/pull/2102
