### ISSUE TITLE
Do you use LevelFilter with `<` or `<=`?

### ISSUE THREAD

**Issue by CAD97** [tokio-rs/tracing#1993]
### Version

```
│   └── tracing v0.1.32
│       ├── tracing-attributes v0.1.20 (proc-macro)
│       └── tracing-core v0.1.23
├── tracing v0.1.32 (*)
├── tracing-appender v0.2.1
│   └── tracing-subscriber v0.3.9
│       ├── tracing-core v0.1.23 (*)
│       └── tracing-log v0.1.2
│           └── tracing-core v0.1.23 (*)
└── tracing-subscriber v0.3.9 (*)
```

### Platform

Microsoft Windows Version 21H2 (OS Build 19044.1586)

### Crates

tracing-core

### Description

When checking if a level is (statically) _enabled_, is it `Level::TRACE < STATIC_MAX_LEVEL` or `Level::TRACE <= STATIC_MAX_LEVEL`?

[`LevelFilter` docs](https://docs.rs/tracing-core/latest/tracing_core/struct.LevelFilter.html#):

> If a [`Level`](https://docs.rs/tracing-core/latest/tracing_core/struct.Level.html) is considered less than a `LevelFilter`, it should be considered enabled; if greater than or equal to the `LevelFilter`, that level is disabled. See [`LevelFilter::current`](https://docs.rs/tracing-core/latest/tracing_core/struct.LevelFilter.html#method.current) for more details.

[`LevelFilter::current` docs](https://docs.rs/tracing-core/latest/tracing_core/struct.LevelFilter.html#method.current):

> If a given span or event has a level _higher_ than the returned `LevelFilter`, it will not be enabled. However, if the level is less than or equal to this value, the span or event is _not_ guaranteed to be enabled; the subscriber will still filter each callsite individually.

The type docs seem to say that `is_enabled = level < filter` and `is_disabled = level >= filter`.

The method docs seem to say that `is_disabled = level > filter` and `is_enabled = level <= filter`.

Which one is it?

**Comment by juumixx** [comment]
Unfortunately, the whole `PartialOrd` for `Level` is implemented the wrong way:
https://github.com/tokio-rs/tracing/blob/68f830d392b3b2fc07704d107d223414a1291da4/tracing-core/src/metadata.rs#L949

Thus, `Level.ERROR < Level.TRACE`, even though `Error = 4` and `Trace = 0`.
It was "fixed" in the documentation here: https://github.com/tokio-rs/tracing/issues/1669
To fix the logic behind it existing code has to be broken, so it should only happen in a major release.

I created an issue, let's see how the response is: https://github.com/tokio-rs/tracing/issues/2367

**Comment by djc** [comment]
FWIW, I also got mighty confused with the docuemntation for `LevelFilter`. Would be nice if that was fixed.

**Comment by loganmzz** [comment]
Just few notes:

* `level` word is little bit confusing, but still catchable, here. May be `effective`, `actual`, `current` or `recorded` would have been better. And I also have changed from `filter` to `filtering` :)

* Having `recorded <= filtering  = enabled` seems too much close to internal representation (I suppose, not checked). In common opinion, levels are sorted from "criticity": `TRACE` (smallest) to `ERROR` (highest). `ALL` and `OFF` are just special meanings. It could be interpreted as negative  and positive infinities (aka unreachable, aka uninstantiable).

**Comment by loganmzz** [comment]
Ok, I haven't checked `PartialOrd` impl. I agree with @nerosnm !

**Comment by steven807** [comment]
Is the issue that PartialOrd is implemented backwards? E.g. 
```
impl PartialOrd for LevelFilter {
    ...

    #[inline(always)]
    fn lt(&self, other: &LevelFilter) -> bool {
        filter_as_usize(&other.0) < filter_as_usize(&self.0)
    }
    ....
}
```
Shouldn't it be `self < other`, not `other < self`?
