### ISSUE TITLE
Better support for using tracing-log with the `log` feature

### ISSUE THREAD

**Issue by samscott89** [tokio-rs/tracing#204]
### Crates

`tracing`, `tracing-log`

### Motivation

People writing libraries using tracing may wish to expose regular `log` support via the `tracing/log` feature. At the same time, to get tracing support for crates using `log`, users may turn to `tracing_log::LogTracer`. Enabling both means logging events twice.

### Proposal

Some way to pass knowledge of the `tracing/log` feature to `LogTracer` so it can skip those events?

### Alternatives

Hope that everybody exposes `tracing/log` via a feature flag from their crates, so that it can be disabled with `default-features = false`.

**Comment by hawkw** [comment]
Of the potential solutions, the simplest might just be to have a global boolean flag indicating whether `tracing`'s log support should be enabled, and have the `LogTracer` disable that flag when set as the global logger. This feels like a gross hack, though.

Alternatively, we could re-introduce more complex filtering to `LogTracer`, and have _it_ disable log records that come from `tracing`.

**Comment by samscott89** [comment]
10,000,000 thanks for getting something working in #215! This already makes a huge difference
