### ISSUE TITLE
[doc] What is the default level of the instrument macro?

### ISSUE THREAD

**Issue by matthiasbeyer** [tokio-rs/tracing#2117]
## Bug Report

The documentation says

> // The span's level will be TRACE rather than INFO.
> #[instrument(level = "trace")]

in ["Overriding span attributes"](https://docs.rs/tracing/latest/tracing/attr.instrument.html#overriding-span-attributes)

but

> The return value event will have the same level as the span generated by #[instrument]. By default, this will be TRACE, but if the level is overridden, the event will be at the same level.

in ["Examples"](https://docs.rs/tracing/latest/tracing/attr.instrument.html#examples-2).

### Version

0.1.34

**Comment by hawkw** [comment]
If no level is provided, the default level is `INFO`:
https://github.com/tokio-rs/tracing/blob/fbfef9c9ca121cd972bed8ddfb9b5fdc17e62f00/tracing-attributes/src/attr.rs#L61

The documentation in the "Examples" section is incorrect and should be corrected --- thanks for catching that. I'll fix the docs right away!

**Comment by hawkw** [comment]
Closed by #2119
