### ISSUE TITLE
log: `LogTrace` requires the `log/std` feature

### ISSUE THREAD

**Issue by samscott89** [tokio-rs/tracing#216]
### Version

tracing-log from git (https://github.com/tokio-rs/tracing#7e6cbf73)

### Crates

tracing-log 

### Description

Per the title:
```
error[E0425]: cannot find function `set_boxed_logger` in module `log`
   --> /home/sam/.cargo/git/checkouts/tracing-e9bbb56ea31f0c18/7e6cbf7/tracing-log/src/log_tracer.rs:219:14
    |
219 |         log::set_boxed_logger(logger)?;
    |              ^^^^^^^^^^^^^^^^ not found in `log`

error: aborting due to previous error
```

**Comment by hawkw** [comment]
Huh, I think the `log/std` feature is enabled by default. Are you using `default-features = false` somewhere?

**Comment by samscott89** [comment]
Nope... I just did a `cargo update` so I could try out the `ignore_crate` bits :)

**Comment by samscott89** [comment]
So perhaps something else removed it from the default features. But it doesn't seem to be in `log`s default features, at least not in 0.4.7

**Comment by samscott89** [comment]
I assume with `cargo check --all`, it pulls in some other dependency which has `log/std` enabled.
