### ISSUE TITLE
tracing-subscriber: JSON formatter

### ISSUE THREAD

**Issue by hawkw** [tokio-rs/tracing#218]
### Crates

`tracing-subscruber`

### Motivation

Logging trace events as JSON is a common use-case, and I've heard interest from users in supporting this.

### Proposal

I think we should add a JSON formatter to the `tracing-subscruber` crate. We can use the `tracing-serde` crate to serialize `tracing` types such as `Metadata` to JSON. The JSON support should probably be feature-flagged, so that users who don't want JSON output and don't already depend on `serde` can avoid pulling in an additional dependency.

### Alternatives

Alternatively, we could add a new crate for JSON formatting. However, I don't think this is the best choice, as `tracing-fmt` already has a great deal of common functionality for formatting line output to the console, including performance optimizations. A new crate would have to reimplement all of this.

It's worth noting, though, that code currently in `tracing-fmt`, such as the filter implementations and the span slab, may soon be generalized and moved to the `tracing-subscriber` crate. In that case, it might be more reasonable to implement the JSON formatter in a separate crate.

## Note

This isn't a small issue, but it's probably pretty straightforward. If a new contributor is interested in taking this one, I'd be happy to provide some mentoring.

**Comment by bIgBV** [comment]
@hawkw I'd like to pick this up. @davidbarsky pointed me to this as a good first issue.

**Comment by hawkw** [comment]
@bIgBV great! here's a rough overview of what you'll probably want to do:

- Add an implementation of the [`FormatEvent` trait](https://github.com/tokio-rs/tracing/blob/449550bf0785499265ee7a446347583059135af0/tracing-fmt/src/format.rs#L23-L31)
that formats events to JSON
- Add an implementation of the [`NewVisitor` trait](https://github.com/tokio-rs/tracing/blob/449550bf0785499265ee7a446347583059135af0/tracing-fmt/src/lib.rs#L192-L196) that returns a [`SerdeMapVisitor`](https://github.com/tokio-rs/tracing/blob/449550bf0785499265ee7a446347583059135af0/tracing-serde/src/lib.rs#L168-L171) from `tracing-serde`, which writes out the field values as JSON to the provided writer (`SerdeMapVisitor` will have to be made publicly accessible).
- Add a function to the [`Builder`](https://github.com/tokio-rs/tracing/blob/449550bf0785499265ee7a446347583059135af0/tracing-fmt/src/lib.rs#L211) in `tracing-fmt` that configures the built subscriber to use the JSON `FormatEvent` and `NewVisitor`.
- Add a "json" feature flag in `tracing-fmt`'s `Cargo.toml` that controls whether all the new code is enabled. It can probably be on by default.

Let me know if you have any questions!

**Comment by hawkw** [comment]
#241 has been merged, which should hopefully unblock this.

**Comment by pimeys** [comment]
Is somebody else working on this? I kind of need the feature and did my first try today. Looks like it outputs JSON and I only implemented the full context for now. This is my first look into tracing codebase, so...

Output looks like

```json
{
  "event": {
    "message": "some json test",
    "metadata": {
      "fields": [
        "message"
      ],
      "file": "tracing-subscriber/src/fmt/format.rs",
      "is_event": true,
      "is_span": false,
      "level": "INFO",
      "line": 843,
      "module_path": "tracing_subscriber::fmt::format::test",
      "name": "event tracing-subscriber/src/fmt/format.rs:843",
      "target": "tracing_subscriber::fmt::format::test"
    }
  },
  "timestamp": "Oct 09 16:24:16.133"
}
```

Is there any ideas how the resulting JSON should look like? At least the timestamp handling here is not ideal...

**Comment by davidbarsky** [comment]
@pimeys I think @bIgBV was gonna try it, but I'm not sure if he has the bandwidth. Feel free to open a pull request with those changes and we can discuss the formatting there.

As for the formatting you have, I think that's a reasonable start, but we can work on setting a reasonable default in that PR + subsequent ones.

**Comment by pimeys** [comment]
I'm kind of stuck understanding how the visitor pattern works in here. I would like to format the fields I have to the JSON structure, but the other implementations in the formatters pass along the writer, where now I'd like to just iterate over the fields, copying the keys as moving the values...

**Comment by davidbarsky** [comment]
We'd be able to offer better support and explanations if we can see your code :). Don't worry about the PR not being complete; this is a collaborative process.

**Comment by davidbarsky** [comment]
Ah, sorry! Found your code: https://github.com/pimeys/tracing/commit/a7e7fbd1c32d618a78e124f10bb23d0944710413

**Comment by pimeys** [comment]
Oh yeah, been just writing all of this down and cleaning stuff. Here's the WIP PR: https://github.com/tokio-rs/tracing/pull/377
