### ISSUE TITLE
Uses ANSI escape codes in dumb terminal in Sublime Text

### ISSUE THREAD

**Issue by kornelski** [tokio-rs/tracing#2214]
## Bug Report

Sublime Text 4 has a "Build" feature which can launch Rust/Cargo programs and redirect their output to its internal log viewer. This log is only in plain text, without any support for ANSI escape codes. It prints escape codes literally, making log output look messy.

```rust
fn main() {
    tracing_subscriber::fmt::init();
    tracing::info!("hello");
}
```

in Sublime's log looks like:

```text
<0x1b>[2m2022-07-09T21:11:30.802562Z<0x1b>[0m <0x1b>[32m INFO<0x1b>[0m <0x1b>[2mtraa<0x1b>[0m<0x1b>[2m:<0x1b>[0m hello
```

Sublime does not set any env variables. There's no `TERM`. It has `__CFBundleIdentifier` env var set to `com.sublimetext.4`.

It would be nice if `tracing_subscriber` could detect if the terminal supports color before using ANSI codes, or at least detect that it's Sublime and it doesn't support them.

### Version
tracing v0.1.35
tracing-subscriber v0.3.14
ansi_term v0.12.1

### Platform

macOS 12.5

**Comment by DesmondWillowbrook** [comment]
Huh, it seems that `tracing_subscriber` doesn't conduct any checks if the stream it's writing to actually supports color, which seems like an oversight. It just directly uses the `ansi_term` crate directly. Something like
- [`owo_colors`](https://docs.rs/owo-colors/latest/owo_colors/) 
- [`colored`](https://docs.rs/colored/latest/colored/) (which depends on `ansi_term`) 
-  [`supports_color`](https://docs.rs/supports-color/1.3.0/supports_color/) (which `owo_colors` depends upon)

could remedy the situation.

**Comment by DesmondWillowbrook** [comment]
[`termcolor`](https://docs.rs/termcolor/latest/termcolor/) explicitly states that it makes no effort to check whether the stream it's printing to is a TTY or not. It recommends `atty` for the same. `supports_color` is a wrapper over `atty` that also checks the `NO_COLOR` env variable.

**Comment by davidbarsky** [comment]
Given that we now do these checks, this issue can be safely closed.

**Comment by nazar-pc** [comment]
@davidbarsky what is the PR where this was fixed? I don't see this issue being referenced by a PR and was not able to find the exact PR myself (tried searching with "ansi" keyword).
