### ISSUE TITLE
core: Consider adding `&dyn std::error::Error` as a Value primitive

### ISSUE THREAD

**Issue by hawkw** [tokio-rs/tracing#222]
### Crates

`tracing-core`

### Motivation

Currently, errors are typically recorded using their `fmt::Display` or `fmt::Debug` implementations. This doesn't give the subscriber much control over how the error is recorded --- in particular, it cannot decide whether to format the error using `Display` or `Debug`, and it cannot access the error's `source` or downcast it to another error type. The `std::error::Error` type is implemented by a majority of errors in both the standard library and in most crates, so its use is fairly widespread.

### Proposal

We could consider adding a `record_error` method to the `Visit` trait in `tracing-core` that takes a `&(dyn std::error::Error + 'static)`, and implement `Value` for `Error`. There would be a default implementation of this method that calls `self.visit_debug`, so this would not require a breaking change.

### Alternatives

Alternatively, we could _not_ do this, and continue with the status quo. There are some compelling reasons we might not want to make this change:
- It adds another value type to the `-core` API, which goes against the goal of keeping `-core` minimal
- The `std::error::Error` type does not exist in `libcore`. If we want to support `no_std` + `alloc` (see #213), we would need to feature flag the new `Visit` method. This means that libraries implementing `Visit` (primarily subscriber implementations) would _also_ need to feature-flag that method if they wish to support `no_std` + `alloc` users. If we want to make supporting `no_std` easy for subscriber authors, it's probably best to avoid that kind of speed bump except when absolutely necessary.

**Comment by carllerche** [comment]
This seems fine at a high level.

**Comment by LucioFranco** [comment]
I'm maybe missing something but why can't you just use `info!(%error)`?

**Comment by hawkw** [comment]
@LucioFranco:
> I'm maybe missing something but why can't you just use `info!(%error)`?

You totally can. The difference is just that recording an error that way records _only_ the `fmt::Display` output. If we recorded the error _as_ an instance of `std::error::Error`, subscriber implementations could:
 - choose to use either the `fmt::Display` _or_ `fmt::Debug` implementations
 - downcast the error to a concrete type
 - call `Error::source`

The latter two might be useful for subscribers that want to implement an error counter of different error types.

**Comment by KodrAus** [comment]
This seems worthwhile for subscribers that might want to treat the content of an error separately from its backtrace (which will [find its way onto `std::error::Error`](https://github.com/rust-lang/rust/issues/53487) eventually).
