### ISSUE TITLE
Make `tracing_subscriber::fmt::format::Writer::new` public

### ISSUE THREAD

**Issue by TmLev** [tokio-rs/tracing#2223]
### Crates

https://github.com/tokio-rs/tracing
https://github.com/davidbarsky/tracing-tree

### Motivation

I'm using `tracing-tree`, but it lacks timestamps. I opened an [issue](https://github.com/davidbarsky/tracing-tree/issues/48) in `tracing-tree` about it and @davidbarsky [suggested](https://github.com/davidbarsky/tracing-tree/issues/48#issuecomment-1185568357) that `FormatTime` can be used as part of the implementation.

When trying to add support for it, I stumbled upon [`Writer`](https://docs.rs/tracing-subscriber/latest/tracing_subscriber/fmt/format/struct.Writer.html) which is needed for calling `FormatTime::format_time`. However, `Writer` has only [one private constructor](https://github.com/tokio-rs/tracing/blob/968dd0d0ee0ee1e55061c72a7572c0541d54775e/tracing-subscriber/src/fmt/format/mod.rs#L421-L426) and cannot be instantiated outside the `tracing-subscriber` crate, which is quite limiting.

### Proposal

Simple solution would be to make constructor entirely public, as suggested in TODO by @hawkw.

### Alternatives

Another solution is to (maybe) add custom constructor that accepts `String`, for instance. This eliminates the need for making existing constructor public, but `Writer::new(&'writer mut impl fmt::Write)` seems to be more flexible.

**Comment by Fuuzetsu** [comment]
I also wanted this when investigating https://github.com/tokio-rs/tracing/issues/2334 , ended up with bunch of copy-paste...

**Comment by kaifastromai** [comment]
I am somewhat confused as to why this issue has not been moved forward at all? The change itself is trivial (code wise, I am not sure what the wider reaching effects may be/other plans that might conflict with such a change), but there is already a PR. Are the maintainers backing off?
