### ISSUE TITLE
ansi_term dependency is unmaintained in tracing-subscriber crate

### ISSUE THREAD

**Issue by metaclips** [tokio-rs/tracing#2281]
[ansi_term](https://github.com/ogham/rust-ansi-term/issues/72) crate is reported as unmaintained by [cargo-deny](https://github.com/EmbarkStudios/cargo-deny), this dependency is used in `tracing-subscriber` crate. RUSTSEC report can be found [here](https://rustsec.org/advisories/RUSTSEC-2021-0139).

**Comment by matschaffer** [comment]
Looks like https://github.com/tokio-rs/tracing/issues/2282 might be the main issue to track for this. I found https://github.com/tokio-rs/tracing/pull/2287 via that issue which removes the dependency. As far as I can tell it's not yet released.
