### ISSUE TITLE
futures: pre-release naming review

### ISSUE THREAD

**Issue by hawkw** [tokio-rs/tracing#229]
Before releasing `tracing-futures` on crates.io, we should give the naming of API functions and types a review to make sure they are as clear and descriptive as possible. 

In particular, here are some things I'd like input on:
 - The `Instrument` combinator method: 
https://github.com/tokio-rs/tracing/blob/c1a9b6cfbbc5650e18102f57beb8df140a09c5e5/tracing-futures/src/lib.rs#L42
  While I think the name is fairly descriptive, I'm not a huge fan of how _long_ it is. The current API has users call this method fairly frequently, and a shorter name (`span`?) might be easier to type. If anyone has suggestions that are equally descriptive but less wordy, I'd be happy to hear them.
-  `WithSubscriber` and `WithDispatch`: It's a little weird that the `WithSubscriber::with_subscriber` method returns a type called `WithDispatch`:
  https://github.com/tokio-rs/tracing/blob/c1a9b6cfbbc5650e18102f57beb8df140a09c5e5/tracing-futures/src/lib.rs#L47-L48
  Perhaps the returned type ought to be renamed.

**Comment by hawkw** [comment]
Would be great to get input on this from @davidbarsky, @LucioFranco, @tobz, and @jonhoo (if it's still open when you get back from vacation).

**Comment by LucioFranco** [comment]
I am ok on renaming instrument to span. For the second one why not call WithSub -> WithDispatcher?

**Comment by hawkw** [comment]
@LucioFranco 
> For the second one why not call WithSub -> WithDispatcher?

I thought `with_subscriber` was better because the method takes a type `S: Into<Dispatch>`, which can be a `Dispatch` _or_ a type implementing `Subscriber`.

**Comment by LucioFranco** [comment]
I think that is still fine to call it `with_dispatch` even if it still is `Into<Dispatch>`

**Comment by davidbarsky** [comment]
I really haven’t used these APIs in any serious capacity, so I can’t really comment on `WithSubscriber`/`WithDispatcher`, but they seem to be a very minor aspect of this API. We can always rename if its problematic.

**Comment by MSleepyPanda** [comment]
@hawkw 
>    * The `Instrument` combinator method:
>      https://github.com/tokio-rs/tracing/blob/c1a9b6cfbbc5650e18102f57beb8df140a09c5e5/tracing-futures/src/lib.rs#L42
>      
>      While I think the name is fairly descriptive, I'm not a huge fan of how _long_ it is. The current API has users call this method fairly frequently, and a shorter name (`span`?) might be easier to type. If anyone has suggestions that are equally descriptive but less wordy, I'd be happy to hear them.
> 
Maybe
 - to meter, metered
 - overload `record` once more, or `record_in`
 - spanned
 - or simply `within`? I like the semantic, `future.within(span)`, as it also expresses the span enter/exit

**Comment by hawkw** [comment]
@MSleepyPanda thanks for the suggestions!
> > * The `Instrument` combinator method:
> >   https://github.com/tokio-rs/tracing/blob/c1a9b6cfbbc5650e18102f57beb8df140a09c5e5/tracing-futures/src/lib.rs#L42
> >   
> >   While I think the name is fairly descriptive, I'm not a huge fan of how _long_ it is. The current API has users call this method fairly frequently, and a shorter name (`span`?) might be easier to type. If anyone has suggestions that are equally descriptive but less wordy, I'd be happy to hear them.
> 
> Maybe
> 
>  * to meter, metered

Hmm, this implies timing strongly while not suggesting other aspects of being in a span, to me?

>  * overload `record` once more, or `record_in`

I'd prefer not to introduce yet another thing called `record`, and I'm not sure if that really describes the semantics of this operation either?

>  * spanned
> 
>     * or simply `within`? I like the semantic, `future.within(span)`, as it also expresses the span enter/exit

Building off of both of these: what about `in_span`? I think it definitely conveys what the result of the operation is, and fits in fairly well with the other future combinators, which tend to have names like `and_then`, `or_else`, etc.

As an alternative, I think `trace` would be good, in an ideal world, but I think that incorrectly suggests the `TRACE` verbosity level, so I'd prefer not to overload it.

**Comment by MSleepyPanda** [comment]
`in_span` sounds good to me! Also, it doesn't sound nearly as expensive/magical as `trace` does.
