### ISSUE TITLE
`Layered` is not suitable for completely independent layers, Layer impl for tuples?

### ISSUE THREAD

**Issue by tfreiberg-fastly** [tokio-rs/tracing#2352]
## Feature Request

I need a combinator for two layers that calls each completely independently in `max_level_hint` (and probably `enabled` and `register_callsite`, but for now I only encountered issues with `max_level_hint`).
This is a continuation of [this discord conversation](https://discord.com/channels/500028886025895936/627649734592561152/1004425346952736848).

### Crates

tracing-subscriber

### Motivation

At work we use two tracing layers that operate independently from one another.
One prints to stdout, with a reloadable filter.
The second prints to a unix stream, when one is attached, with a different filter.
This is initialized to `reload::Layer::new(None)`

I replicated the crux of the issue [here](https://github.com/tfreiberg-fastly/tracing-repro/blob/c9051f1ba0c82b104aff50e60b6b7462fe2e858a/src/main.rs#L14).

Since 0.3.15, `max_level_hint`s were more correctly propagated.
This exposed the issue that nesting these two layers with `Layered` is not really correct, since [`register_callsite`](https://github.com/tokio-rs/tracing/blob/196e83e1f3d6d55fa55a5b82e7d36104d56ab4fd/tracing-subscriber/src/subscribe/layered.rs#L258)/[`enabled`](https://github.com/tokio-rs/tracing/blob/196e83e1f3d6d55fa55a5b82e7d36104d56ab4fd/tracing-subscriber/src/subscribe/layered.rs#L264)/[`max_level_hint`](https://github.com/tokio-rs/tracing/blob/196e83e1f3d6d55fa55a5b82e7d36104d56ab4fd/tracing-subscriber/src/subscribe/layered.rs#L274) handle the two layers hierarchically.
All of them have some special handling for still calling the inner layer if there's per-layer filtering involved, but in my case

### Proposal

How about either an `impl<A,B,S> Layer<S> for (A,B) where ...`, or a `TupleLayer<A,B>` [like in the linked repo](https://github.com/tfreiberg-fastly/tracing-repro/blob/c9051f1ba0c82b104aff50e60b6b7462fe2e858a/src/tuple_layer.rs#L6)?

I copied the `impl Layer for Vec` code and it seems to fix my issue, but I'm not sure if I'm missing more complex interactions.

### Alternatives

`Vec<Box<dyn Layer<Registry> + Send + Sync>>` also seems to work.
Not sure if I should just use that?
I think tracing is good with not even calling the layer methods if a level is disabled right? so dynamic dispatch should probably not happen in a hot loop unless I'm logging that loop anyway

**Comment by tfreiberg-fastly** [comment]
so, i bumped into this again and for some reason tried out `SubscriberExt::with` instead of `Layer::and_then` to combine the layers.
And for some reason,
```
    Registry::default().with(layer_a.and_then(layer_b)).init();
```
doesn't work, but
```
    Registry::default().with(layer_a).with(layer_b).init();
```
does.

I haven't understood why, but I'm pretty sure the results are accurate.

**Comment by hawkw** [comment]
> so, i bumped into this again and for some reason tried out `SubscriberExt::with` instead of `Layer::and_then` to combine the layers. And for some reason,
> 
> ```
>     Registry::default().with(layer_a.and_then(layer_b)).init();
> ```
> 
> doesn't work, but
> 
> ```
>     Registry::default().with(layer_a).with(layer_b).init();
> ```
> 
> does.
> 
> I haven't understood why, but I'm pretty sure the results are accurate.

This is by design. `and_then` combines two layers into a single layer, which ill only enable a span or event if _both_ layers enable it. This allows constructing a tree structure. Calling `with` multiple times instead adds two separate layers to the registry.

**Comment by tfreiberg-fastly** [comment]
Thanks for explaining! Seems like I really misunderstood this part. I think this can be closed
