### ISSUE TITLE
`tracing-core` referring to documentation for an old version 

### ISSUE THREAD

**Issue by LukeMathWalker** [tokio-rs/tracing#2383]
While working on some cursed projects, this [line](https://github.com/tokio-rs/tracing/blob/138b9377f592a4d1c4ade31b89bf46bc2d0e5964/tracing-core/src/lib.rs#L135) in `tracing-core` came to my attention.

Is there a reason why we pin the HTML root for the docs to the documentation generated for `0.1.17`, while the current latest is `0.1.30`?

**Comment by hawkw** [comment]
No reason, I think I just forgot to update that. In fact, I believe that attribute is no longer necessary and can be removed entirely.

**Comment by LukeMathWalker** [comment]
Awesome - I have opened two PRs to rip them out then 🙇🏻
