### ISSUE TITLE
subscriber: generalized NewVisitor abstraction

### ISSUE THREAD

**Issue by hawkw** [tokio-rs/tracing#240]
### Crates

- `tracing-subscriber`
- `tracing-fmt`

### Motivation

The `tracing-fmt` crate crate currently uses a `NewVisitor` trait to abstract over constructing field visitors of different types or with different configurations: 
https://github.com/tokio-rs/tracing/blob/d51d4d69d81ce2e4c6c7166fe70c58a1f881d668/tracing-fmt/src/lib.rs#L192-L196

There have been other use-cases where having this abstraction seems valuable. For example, issue #73 is a proposal for adding utilities for wrapping a visitor to skip a set of excluded field names. A `NewVisitor` abstraction would allow us to provide much more ergonomic APIs for composing this kind of visitor behaviour.

Additionally, the current trait in `tracing-fmt` is tied pretty closely to `tracing-fmt- specific behaviour. A generalized version of this trait should be generic over the input type used to build the visitor.

### Proposal

I propose the following:

- Add a `field` or `visitor` module to `tracing-subscriber` to contain field visitor utilities.
- Add a trait like
  ```rust
  pub trait NewVisitor<T> {
      type Visitor: Visit;
  
      fn new_visitor(&self, target: T) -> Self::Visitor;
  }
  ```
  in that module.
- Update `tracing-fmt` to use the new trait.

### Alternatives

There are some potential design points that ought to be discussed:

- `tracing-fmt`'s `NewVisitor` trait takes a boolean parameter indicating whether or not the provided `fmt::Write` instance has already been written to. This is used to determine whether or not to insert delimiters. With the trait proposed above, we would use a target type that includes this parameter, like `NewVisitor<(&'a dyn fmt::Write, bool)>` (or, preferably, a struct with a named field) to provide this information. 

  Alternatively, if there is a common set of parameters that most `NewVisitor` implementations might expect, we could change the `new_visitor` method to something like 
  ```rust
   fn new_visitor(&self, target: T, params: NewVisitorParams) - > Self::Visitor;
   ```
   where `NewVisitorParams` is an "args struct" that contains common parameters such as whether fields have already been recorded. Using a struct rather than a method parameter specifically for `is_empty` allows us to reserve the ability to add more arguments without a breaking API change, and would prevent the method parameters list from growing unreasonably long if we add more parameters in the future.

- I'm not dead-set on the name `NewVisitor`. In a more OO language, we might call the same pattern a `VisitorFactory`, but that naming is not commonly used in Rust. `tower` has similar traits [`MakeService`](https://docs.rs/tower/0.1.1/tower/trait.MakeService.html) and [`MakeConnection`](https://docs.rs/tower/0.1.1/tower/trait.MakeConnection.html). The rationale for using `Make...` rather than `New...` is given in https://github.com/tower-rs/tower/issues/108#issuecomment-430362089. We could use this naming scheme instead.

**Comment by hawkw** [comment]
cc @bIgBV and @kleimkuhler, this might concern issues you're working on.

**Comment by bIgBV** [comment]
I'm in favor of the name `MakeVisitor` as it specifies the intent pretty well. I also like the idea of having the `NewVisitorParams` type, as it would be a more forwards compatible change. Having to go in and refactor types later on is additional work which could be avoided by adopting the struct pattern early on.

**Comment by hawkw** [comment]
here's a rough draft: https://github.com/tokio-rs/tracing/pull/241/files

**Comment by bIgBV** [comment]
I left a few comments (which are questions more than anything), but I really like the change. Makes things a lot clearer.
