### ISSUE TITLE
Status of 0.2?

### ISSUE THREAD

**Issue by arssher** [tokio-rs/tracing#2420]
For a long time, master is on v0.2 branch which is not released. I see that's a huge work (kudos to you!) and it is desired to avoid changing API more than once, but what is the current status of 0.2:
- Are there foreseeable plans to release it?
- Neglecting backward compatibility, can it be used currently or this is discouraged? Raw or something?

Here are some related issues, but this question doesn't fully fit into any of these, so I posted a new one.
https://github.com/tokio-rs/tracing/issues/922
https://github.com/tokio-rs/tracing/issues/923
https://github.com/tokio-rs/tracing/issues/1520

**Comment by davidbarsky** [comment]
> Are there foreseeable plans to release it?

Personally, I have plans/time for H1 2023 to work on releasing tracing 0.2. 

> Neglecting backward compatibility, can it be used currently or this is discouraged? Raw or something?
No, please do not use tracing 0.2 yet: you will have a poor experience, and most of the ecosystem is not using it.
