### ISSUE TITLE
Calling SpanTrace::capture() before creating a dispatcher prevents further events from being logged

### ISSUE THREAD

**Issue by alcroito** [tokio-rs/tracing#2436]
### Version

├── tracing v0.1.37
│   ├── tracing-attributes v0.1.23 (proc-macro)
│   └── tracing-core v0.1.30
├── tracing-error v0.2.0
│   ├── tracing v0.1.37 (*)
│   └── tracing-subscriber v0.3.16
│       ├── tracing-core v0.1.30 (*)
│       └── tracing-log v0.1.3
│           └── tracing-core v0.1.30 (*)
├── tracing-log v0.1.3 (*)
└── tracing-subscriber v0.3.16 (*)
### Platform
macos 12.4
Darwin xyz 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 x86_64

### Description

As described in the subject, calling `SpanTrace::capture()` before creating a dispatcher prevents further events from being logged after installing a global subscriber.

Repro

```rust
fn main() {
    tracing_error::SpanTrace::capture();
    tracing_subscriber::fmt::init();
    tracing::event!(tracing::Level::ERROR, "this is not shown");
}
```

This is a minimal repro of an issue in color-eyre which captures span traces 
https://github.com/yaahc/color-eyre/issues/110#issuecomment-1372406029

As described in the linked comment, the issue appears to be thread-local-caching of a `NoSubscriber` dispatcher which gets used during callsite interest evaluation, instead of using the real subscriber.

**Comment by davidbarsky** [comment]
Oof, thanks for tracking down this issue.

**Comment by hawkw** [comment]
#2359 should fix this (along with a few related issues)
