### ISSUE TITLE
Unable to format the event using tracing in Ubuntu

### ISSUE THREAD

**Issue by photino** [tokio-rs/tracing#2450]
### Version

```toml
[dependencies]
tracing = "0.1.37"
tracing-appender = "0.2.2"

[dependencies.tracing-subscriber]
version = "0.3.16"
features = ["env-filter", "json", "local-time"]
```

### Platform

Ubuntu 22.04 (Windows 10 WSL)

### Description

I'm working on the project [zino](https://github.com/photino/zino), which setups a tracing subscriber [with the json format](https://github.com/photino/zino/blob/main/zino-core/src/application/tracing_subscriber.rs). It works as expected on Windows 10, but cannot format the events on Ubuntu.

```shell
Unable to format the following event. Name: event /home/panzan/git/zino/zino/src/cluster/axum_cluster.rs:167; Fields: Iter { idxs: 0..2, fields: FieldSet { names: ["message", "env"], callsite: Identifier(0x7ff9b021a908) } }
Unable to format the following event. Name: event /home/panzan/git/zino/zino/src/cluster/axum_cluster.rs:167; Fields: Iter { idxs: 0..2, fields: FieldSet { names: ["message", "env"], callsite: Identifier(0x7ff9b021a908) } }
Unable to format the following event. Name: event /home/panzan/git/zino/zino/src/cluster/axum_cluster.rs:167; Fields: Iter { idxs: 0..2, fields: FieldSet { names: ["message", "env"], callsite: Identifier(0x7ff9b021a908) } }
Unable to format the following event. Name: event /home/panzan/git/zino/zino/src/middleware/tower_tracing.rs:93; Fields: Iter { idxs: 0..1, fields: FieldSet { names: ["message"], callsite: Identifier(0x7ff9b021a770) } }
Unable to format the following event. Name: event /home/panzan/git/zino/zino/src/middleware/tower_tracing.rs:119; Fields: Iter { idxs: 0..1, fields: FieldSet { names: ["message"], callsite: Identifier(0x7ff9b021a788) } }
Unable to format the following event. Name: event /home/panzan/git/zino/zino/src/middleware/tower_tracing.rs:123; Fields: Iter { idxs: 0..1, fields: FieldSet { names: ["message"], callsite: Identifier(0x7ff9b021a7a0) } }
Unable to format the following event. Name: event /home/panzan/git/zino/zino/src/middleware/tower_tracing.rs:93; Fields: Iter { idxs: 0..1, fields: FieldSet { names: ["message"], callsite: Identifier(0x7ff9b021a770) } }
Unable to format the following event. Name: event /home/panzan/git/zino/zino/src/middleware/tower_tracing.rs:119; Fields: Iter { idxs: 0..1, fields: FieldSet { names: ["message"], callsite: Identifier(0x7ff9b021a788) } }
Unable to format the following event. Name: event /home/panzan/git/zino/zino/src/middleware/tower_tracing.rs:141; Fields: Iter { idxs: 0..1, fields: FieldSet { names: ["message"], callsite: Identifier(0x7ff9b021a7d0) } }
Unable to format the following event. Name: event /home/panzan/git/zino/zino/src/middleware/tower_tracing.rs:123; Fields: Iter { idxs: 0..1, fields: FieldSet { names: ["message"], callsite: Identifier(0x7ff9b021a7a0) } }
```

**Comment by photino** [comment]
The problem is that we configured the subscriber `.with_timer(time::LocalTime::rfc_3339())`. If we remove this, it works as expected on Ubuntu as well.

**Comment by davidbarsky** [comment]
If `time::LocalTime::rfc_3339()` is the problematic formatter, can you reproduce this issue with the `time` crate alone? If so, this might be worth reporting to `time` directly.

(I don't have a Debian machine handy to debug/reproduce this.)

**Comment by davidbarsky** [comment]
Hmm, I'm not sure what build of Windows you're on, but it _might_ be related to https://github.com/time-rs/time/issues/192 (haven't been able to dig further, I apologize). I know that clocks on Windows (_especially_ under WSL) are somewhat finicky and break assumptions inside of Rust programs that identify their host OS as Linux.

**Comment by photino** [comment]
I solved my problem by using `OffsetTime::local_rfc_3339()`. The key point is that `OffsetTime` should be initialized before forking threads, but I don't know why the behavior is different on Ubuntu.

**Comment by davidbarsky** [comment]
Ah, I didn't read your code closely enough. That fix makes sense, since getting the local time on most Unix platforms is unsound in Rust.

**Comment by davidbarsky** [comment]
I also forgot to mention that we've documented this behavior in https://docs.rs/tracing-subscriber/latest/tracing_subscriber/fmt/time/struct.LocalTime.html. The [linked documentation](https://docs.rs/time/0.3.4/time/#feature-flags) in the `time` crate discusses why this doesn't work on Ubuntu.
