### ISSUE TITLE
proc-macros: rename `trace` attribute

### ISSUE THREAD

**Issue by hawkw** [tokio-rs/tracing#246]
In order to re-export the `trace` attribute from `tracing-proc-macros` in `tracing` proper, we need to rename the attribute, as the current name conflicts with the `trace!` function-like macro.

**Update**: As per discussion below, I think we've all agreed to rename the attribute to `instrument`.

Here are some potential options, with my thoughts:
- `#[tracing::instrument]`
  * **Pros**: 
    + descriptive
    + doesn't overload a word or term already used in the `tracing` ecosystem
    + doesn't imply a particular verbosity level
  * **Cons:**
    + a bit long to type out
- `#[tracing::traced]`
  * **Pros**: 
    + short
    + also descriptive
  * **Cons:**
    + a single letter away from the `trace!` macro, so potentially easy to typo
    + kind of implies the `TRACE` verbosity level
    + AFAIK, attributes _tend_ to have present-tense rather than past-tense names (e.g., `#[inline]` rather than `#[inlined]`, `#[derive]` rather than `#[derived]`)
- `#[tracing::spanned]`
  * **Pros**: 
    + doesn't overload a word or term already used in the `tracing` ecosystem
    + doesn't imply a particular verbosity level
  * **Cons:**
    + kind of grammatically weird
    + past-tense
    + IMO, not super clear what this means
- `#[tracing::in_span]` or `#[tracing::with_span]`
  * **Pros**: 
    + very clearly communicates the meaning
  * **Cons:**
    + kind of a mouthful IMO

It would be great to hear some opinions on these and/or suggestions of other options.

**Comment by olix0r** [comment]
+1 `tracing::instrument`

is `tracing::span` worth considering as well?

**Comment by carllerche** [comment]
`instrument` is my preferred option as well.

**Comment by hawkw** [comment]
> is `tracing::span` worth considering as well?

`span!` is already the name of a function-like macro in `tracing`, so that would have the same problem as `trace` – attribute and function-like macros occupy the same namespace.

**Comment by davidbarsky** [comment]
+1 to `#[tracing::instrument]`. `span` would be nice, but since that's already a function-like macro in `tracing`, it can't be used. Depending on the trajectory of proc-macros, I can see the value of swapping `instrument` and `span`—I _suspect_ that most spans would be created using the attribute macro instead of the function-like macro.

**Comment by LucioFranco** [comment]
+1 Instrument

**Comment by hawkw** [comment]
I'm also inclined to go with `instrument`, esp. since it seems like folks are converging on it.

@davidbarsky 
> Depending on the trajectory of proc-macros, I can see the value of swapping `instrument` and `span`

I don't think we should do this, even in a world where most people use the attribute macro exclusively: `span!` _returns_ a span, while `instrument` instruments a function. Switching them makes both less clear, IMO. At the very least, it doesn't make sense for the `span!` macro to be renamed `instrument!`.

**Comment by yaahc** [comment]
+1 instrument. Pull the trigga

**Comment by hawkw** [comment]
wow, I really thought this was going to be a prolonged bikeshed...

**Comment by Ralith** [comment]
You could call it `tracing::wrap`! :D

**Comment by hawkw** [comment]
@Ralith we're gonna call it `#[tracing::layer]` now, sorry. because it "layers" a span around the function :P

**Comment by davidbarsky** [comment]
you’re gonna give me heart palpitationss, @hawkw 😅
