### ISSUE TITLE
Const value as `target =` value in `instrument`.

### ISSUE THREAD

**Issue by dpc** [tokio-rs/tracing#2460]
### Crates

`tracing`

### Motivation

We keep the set of tracing targets as a list of `const LOG_SMTH : &str = "smth";`
to avoid typos.

### Proposal

I'd like to:

```
#[instrument(tracing = LOG_SMTH)]
```

**Comment by hawkw** [comment]
Currently, the target value is parsed using the `StrArg` helper: https://github.com/tokio-rs/tracing/blob/264a417b4b13728e7f46383b838668389ea8967e/tracing-attributes/src/attr.rs#L97
This parses the input as a keyword followed by a string literal: https://github.com/tokio-rs/tracing/blob/264a417b4b13728e7f46383b838668389ea8967e/tracing-attributes/src/attr.rs#L206-L216

We could support constants in the attribute if we changed this code to accept a string literal or an identifier. We might  want to do the same for other attribute arguments that are currently only able to accept string literals and not constants, besides the target.

This is probably a pretty straightforward change, if anyone is interested in submitting a PR. I'm happy to provide some guidance!
