### ISSUE TITLE
futures: support tokio-0.2.0 alpha

### ISSUE THREAD

**Issue by hawkw** [tokio-rs/tracing#252]
### Crates
- `tracing-futures`

### Motivation

An alpha release (alpha.1) of `tokio` v0.2 has been released: https://crates.io/crates/tokio/0.2.0-alpha.1

The `tracing-futures` crate should support this version of `tokio`.

### Proposal

Can we conditionally depend on either or both `tokio` versions based on which `futures` feature flags are enabled? If so, we should have implementations for `tokio-0.2` versions of the `tokio` traits we implement in that crate.

### Alternatives

We could issue a breaking change and switch over to `tokio` 0.2, or release a separate alpha from a branch.

**Comment by hwchen** [comment]
Is this the issue that's blocking the use of `#[instrument]` on async fns?

**Comment by hawkw** [comment]
@hwchen nope, `#[instrument]` has supported `async fn`s since the initial release of `tracing-attributes`<sup>1</sup> &mdash; we even have [an example] demonstrating it! 

This issue is just for adding support for using the [`tracing_futures::Instrument`] and [`tracing_futures::WithSubscriber`] combinators on `tokio` 0.2's executor types, the way you currently can with `tokio` 0.1 executors.

Is there documentation or an issue somewhere that states that you can't use `#[instrument]` on `async fn`s? Because if so, that's incorrect & ought to be updated.

[an example]: https://github.com/tokio-rs/tracing/blob/30c62e02a18d50662f05a21863d51849c5fbace3/nightly-examples/examples/async_fn.rs
[`tracing_futures::Instrument`]: https://docs.rs/tracing-futures/0.0.1-alpha.1/tracing_futures/trait.Instrument.html#method.instrument
[`tracing_futures::WithSubscriber`]: https://docs.rs/tracing-futures/0.0.1-alpha.1/tracing_futures/trait.WithSubscriber.html#method.with_subscriber

---

<sup>1</sup>In `tracing-attributes` 0.1.0, it required setting a feature flag, but as of 0.1.1 this is [no longer required](https://github.com/tokio-rs/tracing/commit/44e5e5fca430b986da5453d080fd155ad1e9788e).

**Comment by hwchen** [comment]
ok, so my issue may be unrelated.

Basically, I was (I think) asked to use `tracing-futures` as a dependency, and then I got this error:
```
error[E0277]: the trait bound `tracing_futures::Instrumented<impl std::future::Future>: std::future::Future` is not satisfied
  --> src/main.rs:37:1
   |
37 | / {
38 | |     let res = client.get(url).await?;
39 | |
40 | |     trace!(
...  |
49 | |     Ok(users)
50 | | }
   | |_^ the trait `std::future::Future` is not implemented for `tracing_futures::Instrumented<impl std::future::Future>`
   |
   = note: required by `std::future::poll_with_tls_context`
```
My code (not compiling) is here: https://github.com/hwchen/hyper-async-test/tree/tracing

Thanks for any help, I may have missed something obvious.

**Comment by hawkw** [comment]
I believe #279 closes this.
