### ISSUE TITLE
tracing-opentelemetry: Fails to apply PreSampledTracer to Tracer

### ISSUE THREAD

**Issue by vanhouc** [tokio-rs/tracing#2577]
### Version

```
├── tracing v0.1.38
│   ├── tracing-attributes v0.1.24 (proc-macro)
│   └── tracing-core v0.1.30
├── tracing-opentelemetry v0.18.0
│   ├── tracing v0.1.38 (*)
│   ├── tracing-core v0.1.30 (*)
│   ├── tracing-log v0.1.3
│   │   └── tracing-core v0.1.30 (*)
│   └── tracing-subscriber v0.3.17
│       ├── tracing-core v0.1.30 (*)
│       └── tracing-log v0.1.3 (*)
└── tracing-subscriber v0.3.17 (*)
```

### Platform

```
Darwin camerons-air.lan 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 21:01:02 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T8112 arm64
```

### Crates

- tracing-opentelemetry

### Description

All attempts to use tracing-opentelemetry fail due to PreSampledTracer not being implemented for Tracer structs.

Here is a minimal reproducible [example](https://github.com/vanhouc/oltp_test) with an accompanying github workflow showing it also failing on ubuntu-latest

**Comment by tamasd** [comment]
Downgrading to opentelemetry 0.18.0 makes the error go away.

I dug a bit in the issues, and it seems that tracing-opentelemetry was moved to its own repo. I found two PRs that might be related: tokio-rs/tracing-opentelemetry#9 and tokio-rs/tracing-opentelemetry#12

**Comment by vanhouc** [comment]
Yea you are absolutely correct I just discovered that yesterday and meant to reply. I also had to downgrade a few associated packages as they were pulling in v0.19 transitively.
