### ISSUE TITLE
Release notes is missing feature: tracing-subscriber 0.3.16

### ISSUE THREAD

**Issue by ozgunozerk** [tokio-rs/tracing#2582]
## Bug Report
For this release: https://github.com/tokio-rs/tracing/releases/tag/tracing-subscriber-0.3.16
I think the feature of `keeping max N files` with this PR: https://github.com/tokio-rs/tracing/pull/2323
is missed. 

I just noticed this, because:
I was using `v0.1.x` branch in my cargo.toml, and it's been 8 months, so I've decided to check the release notes once more. After couldn't see the new feature in the release notes, I've decided to check commits, and then found out that with `subscriber-0.3.16`, this feature seems to be in the code for the commit used for this release. However, there are no mention of this feature, nor the contributors in the release notes.

**Comment by hawkw** [comment]
`tracing-appender` and `tracing-subscriber` are separate crates. The `tracing-subscriber` 0.3.16 release will not contain features added to `tracing-appender`.

We need to release a new version of `tracing-appender` before this change will become available.

**Comment by ozgunozerk** [comment]
Thank you for the clarification!
