### ISSUE TITLE
Control FmtSpan from environment

### ISSUE THREAD

**Issue by aviramha** [tokio-rs/tracing#2651]
### Crates

tracing_subscriber

### Motivation

Currently controlling spans is done only on compilation. Sometimes I want `ALL` for using `tokio-console` and sometimes I want just `NEW` and `CLOSE`. I think it makes sense to make it env controlled, like `RUST_LOG`.

### Proposal

Add a new environment variable, `RUST_TRACING_SPAN` that accepts comma delimited values that are the names of the spans - for example:
`RUST_TRACING_SPAN=ALL`
`RUST_TRACING_SPAN=NONE`
`RUST_TRACING_SPAN=ENTER,CLOSE,NEW`

The value would be case insensitive and if the value is `All` or `None` it wouldn't allow any other values.

### Alternatives

Code in my repository to control it or controlling it on compilation time

Happy to implement it when proposal is accepted.

**Comment by davidbarsky** [comment]
Sorry for missing this. The approach that @ajwerner suggested is probably how this would be implemented natively in `tracing-subscriber`. 

We don't really have the bandwidth to accept such a feature, but feel free to open a PR adding this as an example, @aviramha.
