### ISSUE TITLE
Create span for all levels

### ISSUE THREAD

**Issue by zmrocze** [tokio-rs/tracing#2656]
### Crates
`tracing`

### Motivation

It looks like the verbosity level of the span means `applies to all events at this level`, rather than `applies to all events at levels not more verbose`. This means that in my case, where I simply want to prepend the log messages with the list of spans in scope, I need to create 5 spans for all the levels. I assume it's common to do that, isn't it? Maybe I am missing something important here?

### Proposal

I'd like for the library to define a macro `alllevels_span` of semantics, more or less:

```
alllevels_span!(*args).enter() = {
  let span1 = trace_span!(*args);
  ...
  let span5 = error_span!(*args);
  let _enter1 = span1.enter();
  ...
  let _enter5 = span5.enter();  
}
```

**Comment by zmrocze** [comment]
### Implementation

My implementation, bad, implements just one macro expansions. But more or less it's what I'd want. Shouldn't this be a part of the lib? I am missing some way to use just `span`, right?

```
pub struct AllSpans {
  pub trace: tracing::Span,
  pub debug: tracing::Span,
  pub info: tracing::Span,
  pub warn: tracing::Span,
  pub error: tracing::Span,
}

#[macro_export]
macro_rules! allevels_span {
  ($name:expr) => {
    { 
      use utils::logger::AllSpans;
      AllSpans {
        trace: tracing::trace_span!($name),
        debug: tracing::debug_span!($name),
        info: tracing::info_span!($name),
        warn: tracing::warn_span!($name),
        error: tracing::error_span!($name),
      }
    }
  }
}

impl AllSpans {
  pub fn enter<'a>(&'a self) -> AllSpansEntered<'a> {
    AllSpansEntered {
      trace: self.trace.enter(),
      debug: self.debug.enter(),
      info: self.info.enter(),
      warn: self.warn.enter(),
      error: self.error.enter(),
    }
  }
}

pub struct AllSpansEntered<'a> {
  trace: Entered<'a>,
  debug: Entered<'a>,
  info: Entered<'a>,
  warn: Entered<'a>,
  error: Entered<'a>
}
```

**Comment by hawkw** [comment]
> It looks like the verbosity level of the span means `applies to all events at this level`, rather than `applies to all events at levels not more verbose`. This means that in my case, where I simply want to prepend the log messages with the list of spans in scope, I need to create 5 spans for all the levels. I assume it's common to do that, isn't it? Maybe I am missing something important here?

This is incorrect. The level of a span simply determines whether or not that span is enabled, not which events are considered to occur within that span. If a span is enabled, any events that are recorded while the span is entered are considered inside that span. If a span is not enabled, then no events are considered inside that span.

All the span's level does is determine whether or not to enable a span. For example, if a subscriber enables up to the INFO level, then an `info_span!` will be enabled and a `debug_span!` or `trace_span!` will not be enabled. Any enabled events will be considered inside that `INFO` span, regardless of whether they are `ERROR`, `WARN`, or `INFO`. 

Does that make sense? I'm happy to answer any additional questions.

**Comment by zmrocze** [comment]
thanks for clarification!

I got surprised by the `info` level being the default level for `tracing_subscriber::fmt()`. It makes sense, thanks.
