### ISSUE TITLE
tracing-appender: When the keep_last_n_files feature can be released?

### ISSUE THREAD

**Issue by c98** [tokio-rs/tracing#2685]
I've seen the #2323 ,  it's a nice feature and the PR has been already merged, so when it can be released? 🙂

**Comment by hawkw** [comment]
Sorry, my bad, I thought this had already been released. I'll get a release out with this change shortly!

**Comment by yufan022** [comment]
Hi, is there any timeline? Looking forward to this feature.

**Comment by photino** [comment]
Any plan for the release of a new version?

**Comment by davidbarsky** [comment]
i'm working on backporting that feature.

**Comment by yaozongyou** [comment]
looking forward to this feature too~

**Comment by phil-opp** [comment]
I think this can be closed, the release happened in https://github.com/tokio-rs/tracing/pull/2790.
