### ISSUE TITLE
tracing_appender file name without date for rolling logs

### ISSUE THREAD

**Issue by incker** [tokio-rs/tracing#2701]
Hello!

It is more just a question.
Is it possible to write **rolling** logs to file that have name without date. Not `debug.2023-08-29-09-32 ` but just `debug` 

Forward thank you

**Comment by davidbarsky** [comment]
There is no option for this at the moment. Out of curiosity, what behavior would you expect for older files that have since rolled over?

**Comment by incker** [comment]
Older files can have date or other prefixes, it is Ok.
I just would like to customize **current** log file name. So i could read it with external program without loop all directory for searching current file.
Or make `tail -f my_log_file` for current log file without which name..
Mostly for external usage, and only for current log file

**Comment by ptdecker** [comment]
I'll second this request. One of our key clients (a major institution) expects the current log to always be named the same so that their log consolidation processes can pick it up nicely and that the older logs have the date postfix.  Further, they would like them grouped by month and compressed (the older logs that is).  The later is obviously a second request.

**Comment by SpeedReach** [comment]
@davidbarsky this sounds pretty nice! I could help implement it when the sketch is out.

**Comment by SpeedReach** [comment]
@davidbarsky  Or I could open an issue and  write a simple sketch first?

**Comment by incker** [comment]
You could easilly write your implementation of write to file,
then wrap it into NonBlocking struct from tracing_appender and that will work pretty good
For me it was the best solution. I think I will close this issue, as I have opened it

**Comment by ptdecker** [comment]
That's a one approach that would work @incker , but perhaps not as clean as what @davidbarsky proposed and @SpeedReach offerred to help with.  I would have kept this open for them to work under but perhaps they will create their own ticket now for their approach.

**Comment by glindstedt** [comment]
@davidbarsky was the issue ever opened?
