### ISSUE TITLE
Feature request: Ineffective `.with_regex(false)` when parsing in `EnvFilter::builder` in build

### ISSUE THREAD

**Issue by SajjadPourali** [tokio-rs/tracing#2702]
https://github.com/tokio-rs/tracing/blob/bf05c61b7234eb1a196ef8d30f773d3ea6b60ce9/tracing-subscriber/src/filter/env/directive.rs#L122

The `parse` method internally calls all the methods of `EnvFilter::builder`, and since it checks the `regex` during runtime, its dependency will remain in the code.

```rust
    let cmd = EnvFilter::builder()
        .with_regex(false)
        .with_default_directive(LevelFilter::INFO.into())
        .parse(var)
        .unwrap();
```

```bash
 File  .text     Size Crate
 7.5%  25.1% 326.6KiB std
 4.1%  13.7% 177.5KiB regex_automata
 2.9%   9.7% 125.4KiB [Unknown]
 2.3%   7.7%  99.9KiB regex_syntax
 1.6%   5.3%  68.3KiB ...
....
```

```toml
tracing-subscriber = "0.3.17"
```
It would be really nice to have a feature to disable it during code compilation to reduce the binary size.

**Comment by hawkw** [comment]
`with_regex(false)` simply disables the support for matching regular expressions in the filter. However, `env_filter` also uses regular expressions to parse _the filter_ from an input string, so `EnvFilter` would not be available at all without a `regex` dependency.

If you're concerned about the binary size impact of `regex`, and you're not relying on `EnvFilter` features like matching on field values, you may want to consider using the [`Targets` filter](https://docs.rs/tracing-subscriber/latest/tracing_subscriber/filter/targets/index.html) instead. `Targets` implements a subset of the filtering syntax supported by `EnvFilter`: it can match on events and spans based on their target/module path. 

Essentially, the `Targets` filter implements the parts of `EnvFilter` that can easily be implemented without a dependency on `regex`. So, in a sense, the feature flag for disabling `regex` already exists: just disable the `env_filter` feature and use the `Targets` filter, instead.

Hope that's helpful!

**Comment by SajjadPourali** [comment]
Perfect, that's exactly what I was looking for.
