### ISSUE TITLE
tokio-tracing span/instrument not working for tauri command

### ISSUE THREAD

**Issue by youginil** [tokio-rs/tracing#2706]
### Describe the bug

span/instrument not working for command, but `info!` works.

### Reproduction

```
#[instrument]
#[command]
pub fn hello(){
// do async things
}
```
Code above print nothing, but `println!` or `info!` works well

### Platform and versions

```text
[✔] Environment
    - OS: Mac OS 10.15.7 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.72.0 (5680fa18f 2023-08-23)
    ✔ Cargo: 1.72.0 (103a7ff2e 2023-08-15)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-apple-darwin (default)
    - node: 20.5.0
    - pnpm: 8.7.0
    - yarn: 1.22.19
    - npm: 9.8.0

[-] Packages
    - tauri [RUST]: 1.4.1
    - tauri-build [RUST]: 1.4.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: 1.4.0
    - @tauri-apps/cli [NPM]: 1.4.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:3000/
    - framework: SolidJS
    - bundler: Vite
```

[issue at tauri project](https://github.com/tauri-apps/tauri/issues/7716)

**Comment by hawkw** [comment]
Presumably this is because the `#[tauri::command]` attribute also performs code generation, like `#[tracing::instrument]`, and the codegen it performs results in the `tracing` span not being entered. I don't know anything about `tauri` or what its `#[command]` attributed does, so figuring out whether it's possible to support `#[instrument]` on `tauri` commands will require input from someone with more familiarity with `tauri`.

In the meantime, a potential workaround could be to move the implementation of your `command` to a separate `async fn` which can be `#[instrument]`ed, and have the function annotated with `#[tauri::command]` call that function. For example:
```rust
#[command]
pub fn hello() {
    hello_command().await;
}

#[instrument]
async fn hello_command() {
    // do async things
}
```
Would something like that work?

**Comment by youginil** [comment]
> Presumably this is because the `#[tauri::command]` attribute also performs code generation, like `#[tracing::instrument]`, and the codegen it performs results in the `tracing` span not being entered. I don't know anything about `tauri` or what its `#[command]` attributed does, so figuring out whether it's possible to support `#[instrument]` on `tauri` commands will require input from someone with more familiarity with `tauri`.
> 
> In the meantime, a potential workaround could be to move the implementation of your `command` to a separate `async fn` which can be `#[instrument]`ed, and have the function annotated with `#[tauri::command]` call that function. For example:
> 
> ```rust
> #[command]
> pub fn hello() {
>     hello_command().await;
> }
> 
> #[instrument]
> async fn hello_command() {
>     // do async things
> }
> ```
> 
> Would something like that work?

```
#[instrument]
fn hello() {
    println!("hello");
}
```

Unfortunately, it does not work either. The terminal only outputs "hello"

**Comment by hawkw** [comment]
Is the span being shown as context for events that occur within the `#[instrument]`ed function? How is your `Subscriber` configured?

**Comment by youginil** [comment]
```
    let subscriber = tracing_subscriber::fmt()
        .with_max_level(tracing::Level::TRACE)
        .with_file(true)
        .with_line_number(true);
        subscriber.with_writer(io::stderr).init();
```
```
#[instrument]
#[command]
pub async fn project_info() -> Result<Option<ProjectInfo>, AppError> {
    info!("this is info")
    ...
}
```
Output
```
2023-08-31T01:14:43.091987Z TRACE tao::platform_impl::platform::app_delegate: /Users/lg/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tao-0.16.2/src/platform_impl/macos/app_delegate.rs:89: Triggered `applicationDidFinishLaunching`    
2023-08-31T01:14:43.099253Z TRACE tao::platform_impl::platform::app_state: /Users/lg/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tao-0.16.2/src/platform_impl/macos/app_state.rs:435: Activating visible window    
2023-08-31T01:14:43.131706Z TRACE tao::platform_impl::platform::app_delegate: /Users/lg/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tao-0.16.2/src/platform_impl/macos/app_delegate.rs:91: Completed `applicationDidFinishLaunching`    
2023-08-31T01:14:43.236052Z TRACE tao::platform_impl::platform::window_delegate: /Users/lg/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tao-0.16.2/src/platform_impl/macos/window_delegate.rs:370: Triggered `windowDidBecomeKey:`    
2023-08-31T01:14:43.236185Z TRACE tao::platform_impl::platform::window_delegate: /Users/lg/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tao-0.16.2/src/platform_impl/macos/window_delegate.rs:376: Completed `windowDidBecomeKey:`    
2023-08-31T01:14:45.730048Z  INFO project_info: app::handlers: src/handlers.rs:23: this is info
2023-08-31T01:14:49.122551Z TRACE tao::platform_impl::platform::window_delegate: /Users/lg/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tao-0.16.2/src/platform_impl/macos/window_delegate.rs:380: Triggered `windowDidResignKey:`    
2023-08-31T01:14:49.122622Z TRACE tao::platform_impl::platform::window_delegate: /Users/lg/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tao-0.16.2/src/platform_impl/macos/window_delegate.rs:407: Completed `windowDidResignKey:`  
```
then I tried
```
#[command]
pub async fn project_info() -> Result<Option<ProjectInfo>, AppError> {
    let span = span!(Level::TRACE, "project_info");
    let _enter = span.enter();
    info!("this is info")
    ...
}
```
got the same result above.

**Comment by hawkw** [comment]
Looking at your logs, it looks like everything is actually working correctly. Note that the log line 
```log
2023-08-31T01:14:45.730048Z  INFO project_info: app::handlers: src/handlers.rs:23: this is info
```
says `project_info:` after the level (INFO) and before the module path (`app::handlers`). This is the name of the span. Your function is called `project_info`, and by default, the `#[instrument]` attribute generates a span with the same name as the instrumented function, so in this case, the span is called `project_info`.

It seems like the source of confusion is that nothing is printed when calling the `#[instrument]`ed function. This is `tracing_subscriber::fmt`'s default behavior: spans are shown as _context_ when logging events. If an event is logged, the log messagewill include all the spans that were entered when that event was recorded, including any fields recorded by those spans. You can see that, looking at your logs, the `TRACE` logs from `tao::platform_impl` have only a module path, while the `INFO` log has both the name of the span *and* a module path.

The default behavior for `fmt` is to only use spans as context for events, and not to print a log message when a span is entered. This is intended to make the logs more concise and readable, as logging every span enter and exit is potentially quite noisy in a system with a large number of spans. However, if you would prefer to see something printed in your log every time an `#[instrument]`ed function is called, regardless of whether any events are recorded inside that span, you can use [`SubscriberBuilder::with_span_events`](https://docs.rs/tracing-subscriber/latest/tracing_subscriber/fmt/struct.SubscriberBuilder.html#method.with_span_events) to configure the `fmt` subscriber to print messages when a span is created, entered, exited, or dropped. 

For example, if you changed your subscriber configuration to
```rust
use tracing_subscriber::fmt::format::FmtSpan;

let subscriber = tracing_subscriber::fmt()
    .with_max_level(tracing::Level::TRACE)
    .with_file(true)
    .with_line_number(true)
    .with_span_events(FmtSpan::NEW | FmtSpan::CLOSE);
 subscriber.with_writer(io::stderr).init();
```
or similar, you should see a log line generated when your `tauri` command is called, and another one when the call completes.

Hope that helps!

**Comment by youginil** [comment]
@hawkw Your explanation is very clear, thanks a lot.

**Comment by hawkw** [comment]
Great, glad I could help! :)
