### ISSUE TITLE
Value is not Implemented for Option<T>

### ISSUE THREAD

**Issue by AmoleR** [tokio-rs/tracing#2745]
#1585 added `impl Value for Option<T>` so we weren't writing cumbersome code, but this code is not implemented in the master branch (upcoming release).

I don't think there should be any reason to _not_ include this in the master, and it would help greatly.

If you would like, I could tackle this.

**Comment by safinaskar** [comment]
See `valuable` branch. It makes `impl Value for Option` not needed. But I disagree with how they solved the problem, my arguments are here: https://github.com/tokio-rs/tracing/issues/2777

**Comment by davidbarsky** [comment]
We'll be removing the `Value` trait in 0.2 and replacing it with `valuable`, so while it is kind of you to offer to implement this, it's not necessary :)
