### ISSUE TITLE
unable to get LocalTime on OpenBSD

### ISSUE THREAD

**Issue by brahin2** [tokio-rs/tracing#2764]
### Version

```
tracing = "0.1.39"
tracing-subscriber = { version = "0.3.17", features = ["local-time"] }
time = { version = "0.3.30", features = ["local-offset", "macros"] }
```

### Platform

```
% uname -a
OpenBSD myhostname.my.domain 7.4 GENERIC.MP#1397 amd64
```

### Crates

`tracing_subscriber`

### Description

with the following code from the examples of LocalTime i get `<unknown time>` on Openbsd. wasnt sure if a time specific issue so started here since im doing it via this crate for logging. if i do `date` at the cli otherwise i do get a correct local time.

a similar was found seen at https://github.com/Drakulix/simplelog.rs/issues/138 except there is a crash where this is just `<unknown time>` as i researched the error. 

without a localtime the logs are less useful and need more human processing to convert timestamps.

```
% cat src/main.rs
use tracing_subscriber;
use tracing_subscriber::fmt::time::LocalTime;

mod cli;

fn main() {
    tracing_subscriber::fmt()
        .compact()
        .with_timer(LocalTime::rfc_3339())
        .with_max_level(tracing::Level::DEBUG)
        .with_target(false)
        .init();
    tracing::info!("test");
}
```

```
 % cargo run
   Compiling MYCRATE v0.1.0 (/home/MYUSER/MYCRATE)
    Finished dev [unoptimized + debuginfo] target(s) in 1.57s
     Running `target/debug/MYCRATE`
<unknown time>  INFO test
```

cc @botovq

**Comment by davidbarsky** [comment]
This is an issue with the `time` crate.  Please consider opening an issue there: https://github.com/time-rs/time
