### ISSUE TITLE
subscriber: Rewrite the subscriber-util crate

### ISSUE THREAD

**Issue by hawkw** [tokio-rs/tracing#28]
This is a tracking issue for getting the `subscriber` crate into an actually usable state.
- [ ] generalize the `Store`/`Context` types from the `fmt` crate into something reusable
- [ ] better registry/context trait, and have the store impl it
- [ ] update the teeable traits (currently `Observe`) to be compatible with the current API
- [ ] update the filtering traits to be more like the ones in `fmt`
- [x] downcasting story (see tokio-rs/tokio#974)

**Comment by davidbarsky** [comment]
@hawkw noted that subscriber layering + low contention span structures would handle something like 90% of fanout-related usecases.

**Comment by hawkw** [comment]
I've opened a milestone (`tracing-subscriber 0.1`) to track getting the subscriber crate production-ready. I think this issue should be closed in favour of the milestone?

**Comment by hawkw** [comment]
I closed this, as this issue has gotten a bit stale and the roadmap for this crate is pretty well represented elsewhere.
