### ISSUE TITLE
Different timestamps in different outputs

### ISSUE THREAD

**Issue by safinaskar** [tokio-rs/tracing#2801]
### Version
```text
├── tracing v0.1.40
│   ├── tracing-attributes v0.1.27 (proc-macro)
│   └── tracing-core v0.1.32
└── tracing-subscriber v0.3.17
    ├── tracing-core v0.1.32 (*)
    ├── tracing-log v0.1.4
    │   └── tracing-core v0.1.32 (*)
    └── tracing-serde v0.1.3
        └── tracing-core v0.1.32 (*)
```

### Platform
`Linux comp 5.10.0-0.deb9.24-amd64 #1 SMP Debian 5.10.179-5~deb9u1 (2023-09-01) x86_64 GNU/Linux`

### Crates
tracing, tracing-subscriber

### Description
Consider this code:
```rust
fn main() {
    use tracing_subscriber::layer::SubscriberExt;
    use tracing_subscriber::util::SubscriberInitExt;
    use tracing_subscriber::fmt::format::FmtSpan;
    use tracing::info;
    tracing_subscriber::Registry::default()
        .with(tracing_subscriber::fmt::layer()
            .json()
        )
        .with(tracing_subscriber::fmt::layer()
        )
        .init();
    info!("a");
}
```
Output:
```text
{"timestamp":"2023-11-13T16:02:46.422617Z","level":"INFO","fields":{"message":"a"},"target":"ao"}
2023-11-13T16:02:46.422733Z  INFO ao: a
```
As you can see, we got 2 different timestamps. This is bad for my application. I log JSON and human-readable output in the same time. JSON - for automatic processing. And human-readable - for reading it. I want timestamps to be the same, because this will allow me copy timestamp from one output and then search it in the other

**Comment by safinaskar** [comment]
> you can search with lower precision like 2023-11-13T16:02:46.422

This will not work if one output contains timestamp 2023-11-13T23:59:59.999999999Z and another 2023-11-14T00:00:00.000000000Z. I still think current behavior is wrong

**Comment by davidbarsky** [comment]
This isn't an unreasonable request, but I don't know how to accomplish this without putting timestamps into `tracing`/`tracing-core`, which we're not willing to do because that imposes a cost for every layer/subscriber that doesn't care about timestamps or wants a different form of timekeeping.

In any case, I suggest creating some sort of ID and relying on that instead.

**Comment by safinaskar** [comment]
Here is another argument in favor of storing timestamps in `tracing`/`tracing-core`.

It is very easy to create "universal tracing replayer". I. e. small create, which will provide subscriber/layer, which will record everything to some format. And actual replayer, i. e. code that will read that format and replay all these spans and events. This will enable one to store everything and then replay this info to any subscriber/layer, provided by tracing ecosystem. I. e. this crate will enable one to start logging now and decide, which subscriber/layer to use, later. Of course, this likely will be inefficient, but I think this will go for small projects or for prototyping stage.

Unfortunately, this will not work, because timestamps are not stored in `tracing`/`tracing-core`. As well as I understand every subscriber/layer records timestamps on it own using `Instant::now()` or similar. I. e. timestamps will be wrong. So, currently, this "universal tracing replayer" can be implemented by using hacks only, such as `LD_PRELOAD` (to replace `Instant::now()`)

**Comment by davidbarsky** [comment]
While the universal tracing replayer is certainly an interesting capability, we'd like to continue supporting `no_std`. This means that we cannot make `std::time::{SystemTime, Instant}` a requirement.

While this isn't a `no_std` usecase, I was working on a duration-based layer earlier this week that would benefit substantially from using [quanta](https://github.com/metrics-rs/quanta). This layer would not be able to benefit from quanta had `tracing` mandated `std::time::{SystemTime, Instant}`.
