### ISSUE TITLE
Instrument an empty field in a function with multiple layers in subscriber, the log output will contain the empty field multiple times.

### ISSUE THREAD

**Issue by yorkz1994** [tokio-rs/tracing#2811]
### Version

$ cargo tree|grep tracing
├── tracing v0.1.40
│   ├── tracing-attributes v0.1.27 (proc-macro)
│   └── tracing-core v0.1.32
└── tracing-subscriber v0.3.18
    ├── tracing-core v0.1.32 (*)
    └── tracing-log v0.2.0
        └── tracing-core v0.1.32 (*)

### Platform

Both Linux and Windows

### Description

When instrument a function with an empty field `addr`, that field's value is recorded in function body.
When add multiple layers in tracing subscriber and log something inside the function body, then the output will contain the field `addr` as many times as the number of layers.

I tried this code:
```use tracing::{info, instrument};
use tracing_subscriber::{layer::SubscriberExt, util::SubscriberInitExt};

fn main() {
    let registry = tracing_subscriber::registry();
    let layer1 = tracing_subscriber::fmt::layer();
    let layer2 = tracing_subscriber::fmt::layer();
    let layer3 = tracing_subscriber::fmt::layer();
    registry.with(layer1).with(layer2).with(layer3).init();

    foo(1);
}

#[instrument(fields(addr))]
fn foo(a: i32) {
    tracing::Span::current().record("addr", 42);
    info!("in foo");
}```

I expected to see only one `addr` field printed:
2023-11-19T01:18:04.364509Z  INFO foo{a=1 addr=42}: t: in foo
2023-11-19T01:18:04.365495Z  INFO foo{a=1 addr=42}: t: in foo
2023-11-19T01:18:04.366308Z  INFO foo{a=1 addr=42}: t: in foo

Instead many `addr`s field printed:
2023-11-19T01:18:04.364509Z  INFO foo{a=1 addr=42 addr=42 addr=42}: t: in foo
2023-11-19T01:18:04.365495Z  INFO foo{a=1 addr=42 addr=42 addr=42}: t: in foo
2023-11-19T01:18:04.366308Z  INFO foo{a=1 addr=42 addr=42 addr=42}: t: in foo

**Comment by kaffarell** [comment]
Hmm this seems to be some error inside the "pretty" and "compact" fmt layers (or formatters). The event doesn't really have the "addr" field three times, and when using the `.json()` formatter/layer it works as expected.

It seems that the `json()` layer gets the current span (`lookup_current()`), then iterates through all the parent spans using the iterator `scope().from_root()` (tracing-subscriber/src/fmt/format/json.rs:135).
The `pretty()` layer though gets them from `current_span.extensions()`.
Any reason there is a difference between these @hawkw?

**Comment by yorkz1994** [comment]
Since this is duplicate issue, close it.
