### ISSUE TITLE
tracing-journald in source does not match published crate

### ISSUE THREAD

**Issue by bouk** [tokio-rs/tracing#2835]
Hi, I'm using `tracing-journald` version 0.3.0 as published on crates.io, but this doesn't seem to match what's available [in this repo](https://github.com/tokio-rs/tracing/tree/master/tracing-journald), which is version 0.2.0. Could GitHub be updated with the latest code?

**Comment by kaffarell** [comment]
Checkout the `v1.x` branch here: https://github.com/tokio-rs/tracing/tree/v0.1.x/tracing-journald
