### ISSUE TITLE
multiple app instances, same log file

### ISSUE THREAD

**Issue by estnml** [tokio-rs/tracing#2919]
## Feature Request
ability to log events to same file coming from multiple instances of the application. 
### Crates
- tracing
- tracing-subscriber
- tracing-appender

### Motivation
sometimes the application we wrote (e.g. webapi written in axum) work as multiple instances in the server. It would be great if we could configure the tracing behaviour to same log file or log files for each instance.

### Alternatives
- different log file for every instance. ~(however i couldnt figure out how to configure it tracing-appender)~ 
    - using RollingFileAppender::builder().filename_prefix(log_file_prefix) and 
    - let log_file_prefix = format!("instance_{args.port}_backend");

**Comment by mladedav** [comment]
Writing from multiple processes to the same file would involve some inter-process synchronization which I don't think should be handled by `tracing`.

Personally, I do believe your best course of action would be to either use a file per instance or something designed for this kind of thing like `journald`.

**Comment by davidbarsky** [comment]
yeah, you'd want something like `journald` here.
