### ISSUE TITLE
Add trait `StreamInstrument `

### ISSUE THREAD

**Issue by cjwcommuny** [tokio-rs/tracing#2939]
### Motivation

For [`Future`](https://doc.rust-lang.org/std/future/trait.Future.html), tracing has the [`Instrument`](https://docs.rs/tracing/latest/tracing/trait.Instrument.html) trait. But for [`Stream`](https://docs.rs/futures/latest/futures/stream/trait.Stream.html), tracing doesn't have similar trait to use.

### Proposal

Add `StreamInstrument` trait similar to the current `Instrument` trait.

**Comment by mladedav** [comment]
This is already implemented, but `tracing` does not depend on `futures` so you'll have to use `tracing-futures` with the `futures-03` feature.

Then it should work out of the box the same way as with `Future`, you just call `instrument` on your `Stream` and then use the resulting object as if it was the original.
