### ISSUE TITLE
make local time not need unsound feature

### ISSUE THREAD

**Issue by sedan-cell** [tokio-rs/tracing#2974]
### Crates

tracing-subscriber (at least)

### Motivation

allow using of localtime without excess features or scaring users with unsound

### Proposal

allow time LocalOffset to be used without a feature marked unsound. the soundness has been fixed long ago and no longer found in rustsec. the chrono dependency also uses a version of time which was fixed so both crates would be at parity in tracing subscriber features

### Alternatives

log not in localtime, this isnt user friendly though if they check the log.

chrono is explicitly banned in my applications from many past issues and lack of maintenance, releases, and ignored vulnerabilities. i could use this crate but really prefer not to since time is fixed and does the same.

other alternative is to use some other logging crate instead of tracing, but this seems the most maintained and recommended.

**Comment by davidbarsky** [comment]
I'd recommend using Chrono's local time: it is maintained and we'll probably make chrono the primary library in the future.
