### ISSUE TITLE
attributes: support overriding the name of the generated span

### ISSUE THREAD

**Issue by hawkw** [tokio-rs/tracing#298]
### Crates

- `tracing-attributes`

### Motivation

Currently, the `#[instrument]` attribute allows overriding the level and target of the generated span, like so:
```rust
#[tracing::instrument(level = "debug", target = "my_great_target")]
fn my_cool_function(foo: &str, bar: usize) -> bool {
    // ...
}
```
However, the name cannot be overridden &mdash; in the above example, the generated span's name will always be `my_cool_function`. Typically, using the function's name as the span name is fine. However, in some cases, it would be better to rename the span. 

A major example of this is trait methods. Since the procedural macro generates the name by looking at the ident token in the function definition, it will always just be the name of the function, rather than the path to the function (which might include the type that it's a method on, the trait defining the method, etc). So, if I use the `#[instrument]` attribute on the `Future::poll` method for a number of types implementing `Future` (for example), all the spans created by the macro will be named `poll`. To make it clearer _which_ type implementing `Future` the span represents. I might prefer to have spans with names like `ConnectFuture::poll` and `RequestFuture::poll` (for example).

### Proposal

We add a `name` key to the `instrument` macro's arguments, like this

```rust
impl Future for ConnectFuture {
    // ...
    #[tracing::instrument(name = "ConnectFuture::poll")]`
    fn poll(self: Pin<&mut Self>, cx: &mut Context) -> Poll<Self::Output> {
        // ...
    }
}

impl Future for RequestFuture {
    // ...
    #[tracing::instrument(name = "RequestFuture::poll")]`
    fn poll(self: Pin<&mut Self>, cx: &mut Context) -> Poll<Self::Output> {
        // ...
    }
}
```

The `name` argument would be optional. When it is provided, the generated span's name will be the provided string literal. If the `name` argument is not present, it will be the name of the function, as normal.

I think adding this should be pretty straightforward: we can base it off of the existing macro fields that accept string literals, like the `level` argument:

https://github.com/tokio-rs/tracing/blob/561c0c8353ebf6e04292b2531630e7fec30748a7/tracing-attributes/src/lib.rs#L259-L284

Then, if a `name` argument was found, we can use it instead of `ident_str` (the name of the function) here:
https://github.com/tokio-rs/tracing/blob/561c0c8353ebf6e04292b2531630e7fec30748a7/tracing-attributes/src/lib.rs#L196

When the name is overridden, we _might_ want to consider including the function's name as a span field (@davidbarsky will like hearing this). If we do, I suggest we call that field `fn.name`. However, I think that typically the name will still include the function's name, and will just be adding more information to it (such as the name of the type that a method is defined on), so I'm not sure if this will be necessary.

### Alternatives

It would be very cool if we could automatically get the name of a type defining a method. However, given that proc-macros are expanded in the parsing stage, I don't think this information would be available when the macro is run.

**Comment by davidbarsky** [comment]
I’m glad this change is happening! I think tests should include https://github.com/dtolnay/async-trait as well, if this issue is interesting in catching uses with trait functions + dynamic dispatch.

(Also, the function name in the span was incompetence, not a statement of how things should be done. I should not be seen as competent, under any circumstances.)

**Comment by hawkw** [comment]
> I’m glad this change is happening! I think tests should include https://github.com/dtolnay/async-trait as well, if this issue is interesting in catching uses with trait functions + dynamic dispatch.

I think that sounds like a separate ticket, IMHO? We should also try to make `#[instrument]` work with other attributes like `#[tokio::main]` and `#[tokio::test]` --- currently, it may not play well with others.
