### ISSUE TITLE
fmt: `with_ansi(false)` doesn't affect time output

### ISSUE THREAD

**Issue by jarrodldavis** [tokio-rs/tracing#300]
### Version

Latest `master` (commit `561c0c8353ebf6e04292b2531630e7fec30748a7`)

### Platform

```bash
$ uname -a
Darwin Rods-MacBook-Pro.local 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64
```

Target triple: `x86_64-apple-darwin`

### Crates

`tracing-fmt`

### Description

When using `FmtSubscriber::builder().with_ansi(false)`, the time output still contains ANSI color codes.

From my [unit test] in #299:

```rust
let subscriber = FmtSubscriber::builder()
    .with_writer(new_writer)
    .without_time()
    .with_ansi(false)
    .finish();
let dispatch = Dispatch::from(subscriber);

fn event() {
    error!("my customized writer error");
}

dispatcher::with_default(&dispatch, || {
    event();
});
```

Currently, the assertion in that unit test needs to be against this string for the test to pass:

```rust
let expected = "\u{1b}[2m\u{1b}[0mERROR tracing_fmt::test: my customized writer error\n";
```

I expected to be able to use this string:

```rust
let expected = "ERROR tracing_fmt::test: my customized writer error\n";
```

This appears to be an issue because the `time` module only uses static feature flagging to enable/disable ANSI:

https://github.com/tokio-rs/tracing/blob/561c0c8353ebf6e04292b2531630e7fec30748a7/tracing-fmt/src/time.rs#L99-L119

[unit test]: https://github.com/tokio-rs/tracing/pull/299/commits/d3cd76f829e83c488827ebcd48f7a81aa85a5001

**Comment by hawkw** [comment]
Thanks for catching this, that definitely ought to be fixed!

**Comment by SnoozeTime** [comment]
I'd like to tackle this issue :).

One way is to add the `ansi` bool to the time::write function's signature:
https://github.com/tokio-rs/tracing/blob/2520f97964f00ff6c0129e6c1ca0af15776ae5da/tracing-subscriber/src/fmt/time.rs#L99-L104

Then, in format.rs, the `Format` struct can just pass its `self.ansi`:
https://github.com/tokio-rs/tracing/blob/2b7d082d9326496c95847e531c1e9250e5dce861/tracing-subscriber/src/fmt/format.rs#L132-L149

The feature flag would stay, the same way it currently works for `FullCtx` for example.

Any opinion on this?

**Comment by hawkw** [comment]
> I'd like to tackle this issue :).

Great, thanks!

> One way is to add the `ansi` bool to the time::write function's signature:
> 
> > ...
> 
> Then, in format.rs, the `Format` struct can just pass its `self.ansi`:
> 
> > ...
> 
> The feature flag would stay, the same way it currently works for `FullCtx` for example.
> 
> Any opinion on this?

Since the `write` function is crate-private, that seems like a fine approach, as long as we don't make changes to the public `FormatTime` interface. 👍
