### ISSUE TITLE
Broken link on docs.rs

### ISSUE THREAD

**Issue by c-git** [tokio-rs/tracing#3003]
### Version

0.1.40

### Platform

Using Firefox.

### Description

I was reviewing the documentation  on docs.rs and was reading the page for the [instrument](https://docs.rs/tracing/latest/tracing/attr.instrument.html) macro and clicked on the link for the `Value trait`. It has an extra `.` at the end of the link but I'm not sure why. I cloned the repo on my local machine and couldn't reproduce the problem so I wasn't able to send a PR to fix it. I'm not sure if I should have created the issue on docs.rs instead but wasn't even sure where I would do that. So creating this and hoping someone can help or point me in the right direction for how to fix it. (Or just occurred to me maybe it's already been fixed which is why I can't reproduce it.)

Actual link on docs.rs that doesn't work <https://docs.rs/tracing/latest/tracing/field/trait.Value.html.>
Link that works (similar to what I get locally) <https://docs.rs/tracing/latest/tracing/field/trait.Value.html>

Screenshot of what I get from the first (not working) link is below

![screenshot](https://github.com/tokio-rs/tracing/assets/43485962/d8b55f40-2320-4de4-8f61-7d629105cf96)

**Comment by kaffarell** [comment]
Yep, this has been fixed on master:  #2780

**Comment by c-git** [comment]
Ok thanks for the confirmation.
