### ISSUE TITLE
non_blocking writer do not work

### ISSUE THREAD

**Issue by misumisery** [tokio-rs/tracing#3008]
### Version

tracing v0.1.40 
tracing-appender v0.2.3
tracing-subscriber v0.3.18

### Platform

Darwin Kernel Version 23.5.0

### Description

I try to use non_blocking writer to log my application, but it does not work. the log file has no contents.
here is my code:

    let stdout_layer = Layer::new()
        .with_level(true)
        .with_thread_ids(true)
        .with_thread_names(true)
        .with_timer(timer.clone())
        .with_writer(io::stdout.with_max_level(level));
    
    // default log
    let log_file = RollingFileAppender::builder()
        .rotation(Rotation::DAILY)
        .filename_prefix("prefix.log")
        .max_log_files(size)
        .build(log_config.get_path())
        .expect("initializing default rolling file appender failed");
    let (default, _guard) = tracing_appender::non_blocking(log_file);
    let default_file_layer = Layer::new()
        .with_level(true)
        .with_thread_ids(true)
        .with_thread_names(true)
        .with_timer(timer.clone())
        .with_writer(default.with_max_level(level));

    // error log
    let error_log_file = RollingFileAppender::builder()
        .rotation(Rotation::DAILY)
        .filename_prefix("prefix.error.log")
        .max_log_files(size)
        .build(log_config.get_path())
        .expect("initializing error rolling file appender failed");
    let (error, _guard) = tracing_appender::non_blocking(error_log_file);
    let error_file_layer = Layer::new()
        .with_level(true)
        .with_thread_ids(true)
        .with_thread_names(true)
        .with_timer(timer)
        .with_writer(error.with_max_level(Level::ERROR));

    let subscriber = tracing_subscriber::registry()
        .with(stdout_layer)
        .with(default_file_layer)
        .with(error_file_layer);
    set_global_default(subscriber)?;

if i change code to blocking writer, it works well
here is the code:

    let stdout_layer = Layer::new()
        .with_level(true)
        .with_thread_ids(true)
        .with_thread_names(true)
        .with_timer(timer.clone())
        .with_writer(io::stdout.with_max_level(level));
    
    // default log
    let log_file = RollingFileAppender::builder()
        .rotation(Rotation::DAILY)
        .filename_prefix("prefix.log")
        .max_log_files(size)
        .build(log_config.get_path())
        .expect("initializing default rolling file appender failed");

    // change here
    // let (default, _guard) = tracing_appender::non_blocking(log_file);
    let default_file_layer = Layer::new()
        .with_level(true)
        .with_thread_ids(true)
        .with_thread_names(true)
        .with_timer(timer.clone())
        .with_writer(log_file.with_max_level(level));

    // error log
    let error_log_file = RollingFileAppender::builder()
        .rotation(Rotation::DAILY)
        .filename_prefix("prefix.error.log")
        .max_log_files(size)
        .build(log_config.get_path())
        .expect("initializing error rolling file appender failed");

    // change here
    // let (error, _guard) = tracing_appender::non_blocking(error_log_file);
    let error_file_layer = Layer::new()
        .with_level(true)
        .with_thread_ids(true)
        .with_thread_names(true)
        .with_timer(timer)
        .with_writer(error_log_file.with_max_level(Level::ERROR));

    let subscriber = tracing_subscriber::registry()
        .with(stdout_layer)
        .with(default_file_layer)
        .with(error_file_layer);
    set_global_default(subscriber)?;

i don't know why, can someone help?

**Comment by kaffarell** [comment]
For me it works perfectly fine with the provided code although I'm on linux, so maybe there is something darwin-specific that's not working?

**Comment by misumisery** [comment]
thanks for your answer, i will try it on linux later. if it works well, it maybe my mac's problem.

btw, am i using tracing in the right way ?

**Comment by misumisery** [comment]
> For me it works perfectly fine with the provided code although I'm on linux, so maybe there is something darwin-specific that's not working?

thanks for your answer, i will try it on linux later. if it works well, it maybe my mac's problem.

btw, am i using tracing in the right way ?

**Comment by davidbarsky** [comment]
You might be dropping the guard too early, which closes the underlying channel. There isn’t enough information in the code you provided, but generally speaking, the `_guard` needs to live as long as `fn main()`.

**Comment by misumisery** [comment]
> You might be dropping the guard too early, which closes the underlying channel. There isn’t enough information in the code you provided, but generally speaking, the `_guard` needs to live as long as `fn main()`.

yes, that's the problem. the code is in a fn, so it's too early to drop. i changed the code ,it works well.

thanks
