### ISSUE TITLE
Make path clickable

### ISSUE THREAD

**Issue by amab8901** [tokio-rs/tracing#3044]
### Motivation

It's easier to open the file by clicking it in CLI output rather than having to manually look up the file

### Proposal

Change the path format (in error logs, and other event logs) from this:
```
app::dir::subdir::sub_subdir::file: 128
```
to this:
```
app/dir/subdir/file:239
```

Just replace the `::` with `/`, and remove the space before the line number. 

### Alternatives

I haven't considered alternatives. Drawbacks of current approach is that I can't click the path as a means of opening it (at least in VSCode, idk about other IDE:s).

**Comment by mladedav** [comment]
You can turn on logging of filenames explicitly. What you're seeing is not path, but "target" which defaults to module, but it can be overridden in all macros.

So simply changing the colons to slashes wouldn't work. We could change the default, but there's already another way to turn on logging of filenames and I'm not sure it would be an improvement to change the default target to that.

**Comment by amab8901** [comment]
it works, thanks for letting me know how to do it :smile:
