### ISSUE TITLE
Lacking documentation of context propagation through channels

### ISSUE THREAD

**Issue by brunbjerg** [tokio-rs/tracing#3048]
### Crates

tracing

### Motivation

I have two methods that are instrumented and running on separate threads.

The first methods sends a message to the second method.

This generates two spans, and then two trace lines (with event!).

What is the best way of associating these two methods when using spans, so that I will know which message corresponded to which pair of trace events?

### Proposal

I could write the section on the best practice of doing this, if it is actually missing from the documentation.

### Alternatives
At the moment my best idea is the in clue

```rust
struct Message {
    data: Data,
    span: Span,
}
```

**Comment by mladedav** [comment]
Yeah, you have to send the span and then enter it after you receive it.

You could create a wrapper around some channel implementation where it enters the span on receive and exits probably on some kind of drop guard, but I don't think that would work in async and sometimes you want the parent to be the receiving loop.

**Comment by brunbjerg** [comment]
Thank you very much!

I have been searching a lot and have not been able to figure out if there were a best practice approach. 

It seems that for some usecases you will have to mix domain specific types with tracing information to create a robust tracing system.
