### ISSUE TITLE
Allow `Display` formatting of `Option`s in messages

### ISSUE THREAD

**Issue by thomaseizinger** [tokio-rs/tracing#3054]
## Feature Request

It happens many times that I'd like to print an `Option<T>` in a log message using the `Display` implementation of `T`. This isn't possible because `Option` doesn't implement `fmt::Display`. It would be nice if `tracing` would have a way to optionally include a field using its display-formatting when the option is `Some` and omit it when it is `None`.

### Crates

- `tracing`

### Motivation

Concise log messages without duplication.

### Proposal

Perhaps a new sigil could be added? I don't know the internals of `tracing` well enough to propose a good solution.

### Alternatives

The only workarounds I know of are:

- Printing the field in debug mode
- Writing the log message twice, once with and once without the field

**Comment by extremeandy** [comment]
I've been trying to figure out how to get the JSON tracing subscriber to output something like this:

```json
{
    "timestamp": "2024-08-12 14:27:52.454850 UTC",
    "level": "INFO",
    "value": null,
    "target": "hello_world"
}
```

E.g. I tried:

```rust
let value: Option<i32> = None;
info!(value);
```

It doesn't seem to be possible to get it to output `"value": null`, only `"value": "null"`.

However, I did notice that passing `None` caused `value` to be omitted from the output.

So it seems like what you're saying is possible already by using `Option<DisplayValue<T>>`.

E.g.

```rust
let t: T = ...; // where T: std::fmt::Display
let value = Some(tracing::field::display(t)); // or None to omit
info!(value);
```

If `value` is `None` it will be omitted.

**Comment by thomaseizinger** [comment]
Oh you are right! I didn't think of _omitting_ the `%` sigil.
