### ISSUE TITLE
The `%` sigil cannot output `json string`

### ISSUE THREAD

**Issue by zemelLeong** [tokio-rs/tracing#3168]
### Version

cargo-tree.txt:59:│   │   └── tracing v0.1.41
cargo-tree.txt:62:│   │       ├── tracing-attributes v0.1.28 (proc-macro)
cargo-tree.txt:66:│   │       └── tracing-core v0.1.33
cargo-tree.txt:119:│   │   └── tracing v0.1.41 (*)
cargo-tree.txt:169:│   │   └── tracing v0.1.41 (*)
cargo-tree.txt:172:│   └── tracing v0.1.41 (*)
cargo-tree.txt:497:│   │   │   │   └── tracing v0.1.41 (*)
cargo-tree.txt:541:│   │   │   │   │   │   ├── tracing v0.1.41 (*)
cargo-tree.txt:549:│   │   │   │   │   ├── tracing v0.1.41 (*)
cargo-tree.txt:624:│   │   │   └── tracing v0.1.41 (*)
cargo-tree.txt:627:│   │   ├── tracing v0.1.41 (*)
cargo-tree.txt:974:│   └── tracing v0.1.41 (*)
cargo-tree.txt:975:├── tracing v0.1.41 (*)
cargo-tree.txt:976:├── tracing-subscriber v0.3.19
cargo-tree.txt:999:│   ├── tracing v0.1.41 (*)
cargo-tree.txt:1000:│   ├── tracing-core v0.1.33 (*)
cargo-tree.txt:1001:│   └── tracing-log v0.2.0
cargo-tree.txt:1004:│       └── tracing-core v0.1.33 (*)
### Platform

64-bit (Windows) Windows11
### Description

```rust
        let normal_str = "\"147999369\": 147999369".to_string();
        let wrong_json = "{\"147999369\": 147999369".to_string();
        let correct_json = "{\"147999369\": 147999369}".to_string();
        tracing::info!(%normal_str);
        tracing::info!(%wrong_json);
        tracing::info!(%correct_json);
```
output
```
src\domain\dto\tg_bot.rs:168: normal_str="147999369": 147999369
src\domain\dto\tg_bot.rs:169: wrong_json={"147999369": 147999369
src\domain\dto\tg_bot.rs:170: correct_json=
```

**Comment by Rustin170506** [comment]
It works well on my MacOS:

```rs
fn main() {
    tracing_subscriber::fmt::init();

    let normal_str = "\"147999369\": 147999369".to_string();
    let wrong_json = "{\"147999369\": 147999369".to_string();
    let correct_json = "{\"147999369\": 147999369}".to_string();
    tracing::info!(%normal_str);
    tracing::info!(%wrong_json);
    tracing::info!(%correct_json);
}
```


Output: 
```console
     Running `target/debug/test-tracing`
2024-12-02T15:20:35.248538Z  INFO test_tracing: normal_str="147999369": 147999369
2024-12-02T15:20:35.248679Z  INFO test_tracing: wrong_json={"147999369": 147999369
2024-12-02T15:20:35.248696Z  INFO test_tracing: correct_json={"147999369": 147999369}
 *  Terminal will be reused by tasks, press any key to close it. 
```


My tracing version:
```console
cargo tree -p tracing --invert
tracing v0.1.41
└── test-tracing v0.1.0 (/Volumes/t7/code/test-tracing)
cargo tree -p tracing-subscriber --invert
tracing-subscriber v0.3.19
└── test-tracing v0.1.0 (/Volumes/t7/code/test-tracing)
```

**Comment by zemelLeong** [comment]
I can run this code in the terminal and get the correct output, but in RustRover, the JSON doesn't output. It should be an IDE issue.
