### ISSUE TITLE
subscriber: more intuitive FmtSubscriber default filtering

### ISSUE THREAD

**Issue by hawkw** [tokio-rs/tracing#331]
### Crates

 -  tracing-subscriber

### Motivation

Currently, the tracing-subscriber FmtSubscriber::default implementation defaults to no filtering. This means that all instrumentation, including extremely verbose trace-level diagnostics from crates like tokio are enabled by default.

This is because the subscriber itself does not implement filtering, in order to allow it to be composed with filters implemented by Layers. However, defaulting to no filtering at all is definitely a surprising behavior. I didn't want to conditionally return a different type based on whether or not filtering was enabled by the filter feature flag, but this is probably not worth the confusion introduced by this behavior. We should make this more intuitive.

### Proposal

We should change the default impl and builders for FmtSubscriber to use Filter::from_default_env when the filter feature flag is enabled, and layer::Identity when it isn't. We may also want to consider hiding the concrete layered type behind an alias or newtype so that the return type does not change based on feature flags.

### Alternatives

We could continue with the current behavior, but (IMO) this is not ideal.

**Comment by hawkw** [comment]
cc @Ralith this is based on some of your comments on Gitter yesterday

**Comment by Ralith** [comment]
What about defaulting to hiding `trace`-level diagnostics, but allowing another filter (be that `Filter` with env_logger semantics, or `Identity`, or something custom) to be specified in the builder? I think this would be the most intuitive behavior, and wouldn't require breaking env_logger's interface in `Filter`.

**Comment by hawkw** [comment]
@Ralith ah, yeah, I suppose we could just provide different defaults in `FmtSubscriber::default` and `Filter::from_default_env`. That seems a little surprising to me (different `Default` constructors having different defaults), but it would definitely get the most reasonable out-of-the-box behavior in both cases.

**Comment by Ralith** [comment]
My thinking is that `Filter` retains its exactly `env_logger`-like behavior, whereas some other default when no filter is explicitly specified (i.e. the typical case for someone trying out the library for the first time) displays everything `info` and higher. There shouldn't be any surprising differences, because you get the "`info` and higher" behavior in all cases unless you explicitly supply a `Filter`.
