### ISSUE TITLE
subscriber: consider enabling more levels by default

### ISSUE THREAD

**Issue by hawkw** [tokio-rs/tracing#332]
### Crates

- `tracing-subscriber`

### Motivation

Currently, when no `RUST_LOG` environment variable is set, the `tracing-subscriber::Filter` defaults to enabling only the `error` level. This was chosen as it's the [the same behavior as `env_logger`](https://docs.rs/env_logger/0.6.2/env_logger/#enabling-logging). However, disabling almost all diagnostics by default is probably surprising. 

### Proposal

Here are some potential options:
 - We could default to `info` rather than `error`. This means that all spans and events with the `info`, `warn`, and `error` levels would be enabled by default, from both the crate configuring the subscriber _and_ from any dependencies.
- Similarly, we could default to `warn`. 
- Another option is to set a default filter that enables `info` for the crate _that constructs the subscriber_, and `error` or `warn` for all other crates. This would have the nice benefit of including `info`-level diagnostics from applications using `tracing`, but skip potentially more verbose events from library dependencies. The downside is that (as far as I know) the only way to do this without user intervention is through a macro (since we'd need to know the name of the current crate where the subscriber is being constructed). 

Regardless of what we do here, we should make sure it's documented (it isn't currently T_T)

### Alternatives

 We could also leave this as-is.

**Comment by hawkw** [comment]
cc @Ralith any thoughts?

**Comment by davidbarsky** [comment]
As a default behavior, I like the first option best:

> We could default to info rather than error. This means that all spans and events with the info, warn, and error levels would be enabled by default, from both the crate configuring the subscriber and from any dependencies.

From my personal experience, and some experience helping people debug Rust & Tokio applications, opting for _more_ logged spans/events out-of-the-box and providing mechanisms to filter them down to what they actually need is probably a better getting started experience.

Additionally, I think the options you've proposed could be made associated constants in `tracing_subscriber` that enable each described option. While a user could just write the filter directive themselves, reducing as many obstacles as possible to using `tracing` successfully is valuable.

**Comment by Ralith** [comment]
Could we have both a reasonable default *and* strict env_logger compliance, by defaulting to something other than the env_logger compliant filter?

**Comment by yaahc** [comment]
:+1: for defaulting to info, that's a sane default imo.
