### ISSUE TITLE
New Crates: tracing-coz and tracing-flame

### ISSUE THREAD

**Issue by yaahc** [tokio-rs/tracing#357]
### Motivation

Tracing is uniquely positioned to integrate with scoped profilers and to allow trivial instrumentation of your program. https://github.com/alexcrichton/coz-rs and https://github.com/TyOverby/flame would both be great tools to add integration with.

**Comment by GregBowyer** [comment]
Tracing-coz: (Untested might eat your children) https://crates.io/crates/tracing-coz

I basically have a tracing enabled program that I want to coz profile so I built this out

**Comment by hawkw** [comment]
I believe both of these crates have been implemented, so this feature request can be closed! :)
