### ISSUE TITLE
deadlock in TraceLogger

### ISSUE THREAD

**Issue by udoprog** [tokio-rs/tracing#369]
## Bug Report

`TraceLogger` deadlocks on most non-trivial operations.

### Crates

* `tracing-log`

### Description

Most operations on `TraceLogger` locks `self.spans` and tries to call [`current_id`](https://github.com/tokio-rs/tracing/blob/cd83212a9a1e68db6b0011e76c39a0210a653226/tracing-log/src/trace_logger.rs#L415). `current_id` in turns tries to clone the span using [`clone_span`](https://github.com/tokio-rs/tracing/blob/cd83212a9a1e68db6b0011e76c39a0210a653226/tracing-log/src/trace_logger.rs#L388), which also tries to lock `self.spans`. Since the std `Mutex` is not re-entrant, this results in a deadlock for most operations.

**Comment by udoprog** [comment]
I don't know what the correct solution is because I can't wrap my head around what the `ref_count` on `SpanLineBuilder` is trying to accomplish. I've solved this by cloning the `Id` directly without modifying `ref_count` of the appropriate `SpanLineBuilder`, but I also don't seem to be seeing any `close` logs happening (which should be handled here: https://github.com/tokio-rs/tracing/blob/cd83212a9a1e68db6b0011e76c39a0210a653226/tracing-log/src/trace_logger.rs#L402).

The solution is also further complicated by most of the time holding a reference into `self.spans`, like is done here:
https://github.com/tokio-rs/tracing/blob/cd83212a9a1e68db6b0011e76c39a0210a653226/tracing-log/src/trace_logger.rs#L280
In effect: it's not possible to get a mutable reference at this point.

A universal solution would be to simply store all span line builders as `Arc<Mutex<SpanLineBuilder>>`, and clone them every time they are accessed, but this would obviously lead to _much more_ locking. Maybe trying to get rid of the ref_count or making it atomic would be better.

**Comment by hawkw** [comment]
I think it should be possible to just move the calls to `current_span` to before the lock on `self.spans` is acquired. 

Ideally, though, the solution is to move away from the global mutex; I'm working on a general-purpose data structure for storing spans where a global lock is unnecessary (see #157).

**Comment by hawkw** [comment]
The best solution to this issue might just be to deprecate and remove `TraceLogger`. It was written before the "log" feature flag, which causes all the `tracing` macros and structs to emit `log::Record`s as well as traces, was added. Using the feature flag is probably a better solution for most use-cases where recording `tracing` data with a `log::Logger` is desired.

If there are any reasons why folks _need_ `TraceLogger` and cannot use the "tracing/log" feature flag, I'm happy to hear them!

**Comment by wngr** [comment]
I'd encourage you to put this deprecation hint into this repo's README and also rm the reference to this crate at https://docs.rs/tracing/0.1.9/tracing/#related-crates.

**Comment by hawkw** [comment]
@wngr FWIW, the `tracing-log` crate itself is definitely _not_ deprecated; it also provides a translation layer from `log` records _to_ `tracing` events that is commonly used. It's specifically the `TraceLogger` type that should be deprecated. 

I'll mark it as deprecated in the next release.

**Comment by wngr** [comment]
Alright, thanks for the clarification! Marking `Tracelogger` sounds reasonable.
