### ISSUE TITLE
subscriber: Add more timestamp formatting options

### ISSUE THREAD

**Issue by davidbarsky** [tokio-rs/tracing#379]
In the [`time` module in tracing-subscriber](https://github.com/tokio-rs/tracing/blob/master/tracing-subscriber/src/fmt/time.rs), we have _either_ human-readable timestamps _or_ custom formatting options. We should support several named formats that make it easy to for end-users to pick the right format for their use-case. To start with, we can support:
- a "for humans" time format, as we do now.
- an [ISO 8601 timestamp](https://en.wikipedia.org/wiki/ISO_8601). This can be exposed via [chrono](https://docs.rs/chrono/0.4.9/chrono/)'s various formatting options.

**Comment by hawkw** [comment]
I'm not sure why the title of this issue is "Revisit the usage of `fmt::Result`"? But other than that, +1.

**Comment by hawkw** [comment]
> In the [`time` module in tracing-subscriber](https://github.com/tokio-rs/tracing/blob/master/tracing-subscriber/src/fmt/time.rs), we have _either_ human-readable timestamps _or_ custom formatting options. 

FWIW, we also have an `Uptime` option: https://github.com/tokio-rs/tracing/blob/06daa9512b250e2d73e8722f7f15dfcb9d95f3be/tracing-subscriber/src/fmt/time.rs#L57-L63

**Comment by hawkw** [comment]
Also, whether a `SystemTime` is printed in a human-readable format or using `SystemTime`'s `fmt::Debug` impl is currently only controlled by a feature flag:
https://github.com/tokio-rs/tracing/blob/06daa9512b250e2d73e8722f7f15dfcb9d95f3be/tracing-subscriber/src/fmt/time.rs#L79-L90

This is probably not idea — if a dependency enables the `"chrono"` feature, the timestamp will _always_ be printed with the human-readable format, regardless of what the user wants. There should maybe be different constructors or something.

**Comment by hawkw** [comment]
When `chrono` is in use, we could probably allow passing in a custom format string. Also, I think the `SystemTime` timestamp implementation should probably _always_ use `std::time::SystemTime`, and we should add a separate `Chrono` timestamp formatter that's enabled when `chrono` is enabled?

**Comment by davidbarsky** [comment]
I mostly was inattentive, sorry. I meant to say that we can’t really capture serde errors in the writer.

**Comment by hawkw** [comment]
@davidbarsky yeah, can we have a separate issue for that please?
