### ISSUE TITLE
core: add `dispatcher::set_default`

### ISSUE THREAD

**Issue by hawkw** [tokio-rs/tracing#383]
### Crates

- `tracing-core`

### Motivation

Currently, the only ways to set the default subscriber are `set_global_default` and `with_default`. The `with_default` function takes a closure, and sets the default subscriber for the duration of that closure, while `set_global_default` sets a default for the entire lifetime of the program, and fails if called more than once.

The current API surface makes some use-cases difficult. For example, if I wanted to use a fresh subscriber in each of my tests, I would need to use `with_default`, requiring indenting the entire test into a closure. When adding `tracing` to an existing codebase, this can result in unnecessarily large diffs. 

### Proposal

@Ralith suggested that we add a method for setting the default subscriber, returning an RAII drop guard that unsets the subscriber when dropped. This could be used to set the subscriber only for the duration of a scope, without having to indent the entire scope as with `with_default`.

I'll add that the current implementation of `with_default` uses a drop guard _anyway_: https://github.com/tokio-rs/tracing/blob/06daa9512b250e2d73e8722f7f15dfcb9d95f3be/tracing-core/src/dispatcher.rs#L201-L226

This is in order to unset the default subscriber on panics. We could simply make this existing code public API.

### Alternatives

Alternatively, we could not add a drop guard for setting the default subscriber. The existing API was chosen for consistency with existing `tokio` APIs, and adding a new way to set the default subscriber could introduce confusion.

**Comment by hawkw** [comment]
@carllerche any thoughts on whether we should do this?

**Comment by Ralith** [comment]
> For example, if I wanted to use a fresh subscriber in each of my tests

To be clear, there doesn't seem to be a simple way to set a single global subscriber for tests, so this use case isn't niche. You could start every test with a call that locks a global mutex and installs a global subscriber if one does not yet exist, but that's both uglier and requires more code than the proposed solution.

**Comment by hawkw** [comment]
> You could start every test with a call that locks a global mutex and installs a global subscriber if one does not yet exist, but that's both uglier and requires more code than the proposed solution.

@Ralith AFAICT this is the state of the art for logging in tests in the `log` world, so I hadn't really considered it _that_ bad — I've seen a lot of code where every test begins with a call to `my_custom_init_env_logger()` or whatever. But, I agree that this could be more ergonomic! 

And, since `tracing` (unlike `log`) has a notion of scoped subscribers, we can do really nice stuff like separating the output from each test, as well.

**Comment by hawkw** [comment]
FWIW, the `tokio_reactor::with_default` and `tokio_timer::with_default` functions have been replaced with [`set_default`][1] functions][2] that return a drop guard in the 0.2 alpha branch of `tokio`. Therefore, the "consistency with `tokio`" argument against adding a drop-guard-based API is pretty much moot, and I think we should probably go ahead and add `set_default` to `tracing` as well. 

Here's what I think we should do: 
1. Rename this type
   https://github.com/tokio-rs/tracing/blob/06daa9512b250e2d73e8722f7f15dfcb9d95f3be/tracing-core/src/dispatcher.rs#L201-L204
  to `DefaultGuard` (for consistency with `tokio`'s APIs), and make it `pub`.
2. Add a `dispatcher::set_default` function that uses the existing code to set the default dispatcher, returning a guard. This is basically already implemented here: 
   https://github.com/tokio-rs/tracing/blob/06daa9512b250e2d73e8722f7f15dfcb9d95f3be/tracing-core/src/dispatcher.rs#L636-L645
3. Change `dispatcher::with_default` to use the new `set_default`. _Don't_ remove it, since that would be a breaking change.
4. Update the `tracing-core` version.
5. Update `tracing` to use the new `tracing-core` version (as a path dep, for now) and add a new `tracing::subscriber::set_default` that works identically to `tracing_core::dispatcher::set_default`, but taking a `Subscriber` instead of a `Dispatch`.

This should be fairly straightforward, so I'm marking this as a "good first issue" — if anyone wants to work on this, please feel free to ask me any additional questions that come up.

[1]: https://docs.rs/tokio-net/0.2.0-alpha.6/tokio_net/driver/fn.set_default.html
[2]: https://docs.rs/tokio-timer/0.3.0-alpha.5/tokio_timer/fn.set_default.html
