### ISSUE TITLE
subscriber: don't escape field values in JSON

### ISSUE THREAD

**Issue by hawkw** [tokio-rs/tracing#391]
### Crates

- tracing-subscriber

### Motivation

Follow-up from #377. Currently, field values of spans in `tracing-subscriber::fmt` JSON output are escaped strings. This should be fixed (see https://github.com/tokio-rs/tracing/pull/377#discussion_r335311790).

**Comment by davidbarsky** [comment]
This is fixed in https://github.com/tokio-rs/tracing/pull/412/commits/9dc540207cdde7168cb5bdfbfe627919d055ccc4.
