### ISSUE TITLE
futures: make std::future the default

### ISSUE THREAD

**Issue by hawkw** [tokio-rs/tracing#418]
### Crates

`tracing-futures`

### Motivation

Currently, the `tracing-futures` crate enables futures 0.1 support by default. This is because until quite recently, async/await was not stable, and most `std::future`-based projects require async/await. Now, however, async/await is available on stable Rust, so we should move to make it the default for the `tracing-futures` crate. 

### Proposal

I think the best solution is to change the default feature flags so that the `std-future` feature is enabled by default. We may also want to enable the `futures-03` feature by default. Compatibility with futures 0.1 and with vintage versions of `tokio` should remain available, but they should be made opt-in.

Since changing the default feature flags is a breaking change, we should publish an 0.2 release of tracing-futures.

**Comment by davidbarsky** [comment]
Should `tokio-alpha` also be enabled by default? I'm somewhat inclined to say "yes", but I don't feel too strongly about that.

**Comment by hawkw** [comment]
> Should `tokio-alpha` also be enabled by default? I'm somewhat inclined to say "yes", but I don't feel too strongly about that.

That would require bumping MSRV to 1.39.0. I'm willing to consider doing a MSRV bump (which would also allow us to take all the async-await examples and tests out of the separate crates they currently have to live in), but I think that is a separate change.

I'm also on the fence about having a dependency on an alpha crate be a default feature, since it would currently be pretty easy to end up with incompatible versions of `tokio` 0.2 in your dependencies by accident.

**Comment by yaahc** [comment]
would you only be bumping the MSRV for the tracing-futures crate? That seems entirely reasonable to me given the context of 1.39

**Comment by hawkw** [comment]
> would you only be bumping the MSRV for the tracing-futures crate? That seems entirely reasonable to me given the context of 1.39

Beyond being able to turn on `tokio` 0.2 by default, the other main motivation for bumping the MSRV is so that we can move the examples that use async-await into the main workspace (and _add_ examples with async-await in RustDoc). Since adding the examples to the root workspace would break the build if they can't be compiled, the build on CI would require Rust 1.39. 

However, it's worth noting that for most `tracing` crates, the crates.io dependency would still work on earlier versions of Rust, since the crates.io package wouldn't include the examples anyway. So, we would _actually_ probably still be compatible in most cases, we just wouldn't be able to _guarantee_ support any longer. Remember, "minimum _supported_ Rust version" != "minimum _compatible_ Rust version" ;)

**Comment by olix0r** [comment]
what does this mean for projects that are unable to move to std::future immediately. Would the 0.1 branch receive bugfixes?

**Comment by hawkw** [comment]
@olix0r it should be possible to change the dependency to
```toml
[dependencies.tracing-futures]
version = "0.2"
default-features = false
features = ["futures_01", "tokio_01"]
```
and there shouldn't be any code that requires Rust 1.39 or `std::future`. 

This is why I'm a bit more hesitant about also bumping MSRV, and I think it should be considered separately from releasing a `tracing-futures` 0.2.

**Comment by hawkw** [comment]
(i'm happy to also backport changes to 0.1 if there's a reason to, I just think it likely won't be necessary if dependent projects are willing to switch feature flags around to pick up 0.2)
