### ISSUE TITLE
subscriber: Provide Examples for `fmt::Layer` and `fmt::LayerBuilder`.

### ISSUE THREAD

**Issue by davidbarsky** [tokio-rs/tracing#430]
(This is followup from #420)

`tracing` should provide examples of building and composing `fmt::Layer` in the style that the examples directory does with `fmt::Subscriber`. Basic examples can be seen in the unit tests for `fmt::Layer`:

https://github.com/tokio-rs/tracing/blob/773c44054aed7f072ff03ee5dc64391f799dc02d/tracing-subscriber/src/fmt/fmt_layer.rs#L487-L502

In general, examples should follow the form of:

```rust
use tracing::subscriber;
use tracing_subscriber::{
    fmt::{self, format},
    registry::Registry, Layer
};

let f = format::Format::default();
let fmt = fmt::Layer::builder().event_format(f).finish();
let subscriber = fmt.with_subscriber(Registry::default());
subscriber::set_global_default(subscriber).expect("Unstable to set global subscriber");
```

**Comment by hawkw** [comment]
@yaahc any progress on this?
