### ISSUE TITLE
tracing-fmt: example out of date

### ISSUE THREAD

**Issue by EverlastingBugstopper** [tokio-rs/tracing#444]
### Version

```
├── tracing v0.1.10
│   ├── tracing-attributes v0.1.5
│   └── tracing-core v0.1.7
└── tracing-subscriber v0.2.0-alpha.1
    ├── tracing-core v0.1.7 (*)
    ├── tracing-log v0.1.1
    │   └── tracing-core v0.1.7 (*)
    └── tracing-serde v0.1.0
        └── tracing-core v0.1.7 (*)
    └── tracing-log v0.1.1 (*)
```

### Platform

Darwin C02VM0JPHTDD 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64

### Crates

`tracing-fmt`
`tracing-subscriber`

### Description

I tried copy and pasting [this file](https://github.com/tokio-rs/tracing/blob/master/tracing-fmt/examples/custom_visitor.rs) into a new cargo project and adding `tracing`, `tracing-subscriber` and `tracing-fmt` to my `Cargo.toml` but it would not compile. 

#### Existing example use statements
---

```rust
use tracing_fmt::format;
use tracing_subscriber::prelude::*;
```

#### Proposed use statements
---

```rust
use tracing_subscriber::fmt::format;
use tracing_subscriber::prelude::*;
use tracing_subscriber::FmtSubscriber;
```

**Comment by hawkw** [comment]
Thanks! I think the example should also be moved to https://github.com/tokio-rs/tracing/tree/master/examples/examples
