### ISSUE TITLE
fmt: add SpanBacktrace API

### ISSUE THREAD

**Issue by yaahc** [tokio-rs/tracing#464]
## Feature Request

This feature is currently available in the experimental `tracing-error` crate Eliza has been working on. The goal is to get this moved into fmt proper. 

### Crates

tracing-subscriber

### Motivation

I would like to be able to get the SpanBacktrace itself to shove into other error types or format into strings or w/e for creating nice rich user facing errors.

### Additional Questions

* Does it make sense to export the same API as std::backtrace::Backtrace https://doc.rust-lang.org/nightly/std/backtrace/index.html? The main issue here being should we allow for conditional capture of backtraces.
  * If we do want to conditionally capture SpanBacktraces, do we want to be able to conditionally capture backtraces independently of the mechanism used by std? Do we just capture if `RUST_LIB_BACKTRACE=1` like std or do we use some different value in the `RUST_LIB_BACKTRACE` variable like color-backtrace with `RUST_BACKTRACE=full` or do we use an entirely different env variable?

**Comment by hawkw** [comment]
I'm down for adding something along the lines of this, but I think we can have a significantly more general API. We could have a free function that exposes something like the `Context::scope` iterator https://github.com/tokio-rs/tracing/blob/8308d53ac6a8b7632aa73a809e7b05b22332f43c/tracing-subscriber/src/layer.rs#L822-L840

but through downcasting the current subscriber.

Then, on top of that, we can build-batteries included APIs for things like getting a formatted trace from that iterator (in the `fmt` module).
