### ISSUE TITLE
tracing: add a `Span` method for getting the dispatcher

### ISSUE THREAD

**Issue by hawkw** [tokio-rs/tracing#473]
### Crates

`tracing`

### Motivation

The `Span` type internally stores a `Dispatch`:
https://github.com/tokio-rs/tracing/blob/8308d53ac6a8b7632aa73a809e7b05b22332f43c/tracing/src/span.rs#L366-L370

This `Dispatch` always forwards to the `Subscriber` that assigned the span's ID, and will receive notifications when it's entered, exited, or closed. 

However, there's no way for user code to access this `Dispatch`. This might be useful in cases where "out of band" APIs are implemented to allow recording subscriber-specific data about a span. Currently, libraries implementing those APIs have to write code like this:

```rust
fn record_third_party_data(span: &Span, tpd: ThirdPartyData) {
    let mut tpd = Some(tpd);
    tracing::dispatcher::get_default(|current| {
        if let Some(subscriber) = current.downcast_ref::<SubscriberThatUnderstandsThirdPartyData>() {
            let tpd = tpd.take().expect("called twice!");
            subscriber.record_third_party_data(span.id(), );
        }
    })
}
```

This has two disadvantages:
1. we have to do a thread local access to get the current default subscriber
2. we run the risk that the current subscriber _may_ not be the same subscriber that assigned the span's ID. This means that the subscriber may not know about that ID, or may have assigned it to a different span!

### Proposal

We should add some way to access the `Dispatch` stored in a `Span`. This could be either a function that borrows the `Dispatch`, like this:

```rust
impl Span {
    pub fn subscriber(&self) -> Option<&Dispatch> {
         // ...
    }
}
```

or one that invokes a closure _with_ the `Dispatch`, like this:

```rust
impl Span {
    pub fn with_subscriber<T>(&self, f: impl FnOnce((&Id, &Dispatch)) -> T) -> Option<T> {
         // ...
    }
}
```

While the first option is more ergonomic, I think the second is better, for compatibility reasons: returning a ref to a `Dispatch` means that we are committing to `Span`s _always_ having an internal `Dispatch` that we can borrow. If that changes, we can no longer implement that API. In the second API, however, if we were to remove the `Dispatch` field on `Span`s, we could transparently swap out the implementation with one that just gets the current default, and it would still work.

This would allow libraries that integrate with other systems to write some pretty neat code, like this:

```rust
// Assume ElizaTracing is a cool new distributed tracing system.
// This is, of course, just intended as an example.

// ElizaTracing uses 128-bit span IDs and 256-bit trace IDs, because that's 
// twice as many bits as the W3C TraceContext spec, and therefore "twice as good"
type TraceId = [u8; 32];
type SpanId = u128;

pub trait ElizatracingSpanExt {
    /// Associates `self` with an existing `ElizaTracing` trace, with the provided
    /// ID.
    fn in_trace(&self, trace_id: TraceId);

    /// Indicates that `self` corresponds to an `ElizaTracing` span with the
    /// provided ID.
    fn has_span_id(&self, span_id: SpanId);
}

impl ElizatracingSpanExt for tracing::Span {
    fn in_trace(&self, trace_id: TraceId) {
        self.with_subscriber(|id, subscriber| {
            if let Some(s) = subscriber.downcast_ref::<ElizatracingLayer>() {
                s.record_trace_id(id, trace_id);
            }
        })
    }

    fn has_span_id(&self, span_id: SpanId) {
        self.with_subscriber(|id, subscriber| {
            if let Some(s) = subscriber.downcast_ref::<ElizatracingLayer>() {
                s.record_span_id(id, span_id);
            }
        })
    }
}


// ... 

fn handle_http_request(request: http::Request<()>) -> http::Response<()> {
    let span = tracing::info_span!("request", method = req.method(), uri = req.uri());
    
    // Try to unpack the ElizaTracing context from the received headers, if one exists.
    let (et_trace, et_span) = unpack_elizatracing_context(&req.headers());
    if let Some(trace_id) = et_trace {
        span.in_trace(trace_id);

        if let Some(span_id) = et_span {
            span.has_span_id(span_id);
        } else {
            span.has_span_id(elizatracing::new_span_id());
        }
    } else {
        span.in_trace(elizatracing::new_trace_id());
        span.has_span_id(elizatracing::new_span_id());
    }

    let _guard = span.enter();
    
    // ... handle http request ...
}
```

**Comment by hawkw** [comment]
cc @davidbarsky, @jtescher, @pkinsky

**Comment by jtescher** [comment]
I like this approach :+1:. `ElizaTracing` layer implementations would need to be able to update span/trace ids after creation, but they could do that with their own Span extension that recorded the necessary data.

**Comment by pkinsky** [comment]
I really like this, a lot of that code that'd be simplified looks suspiciously familiar ;)

I think you're right that option 2 makes the most sense. Mind if I take a crack at implementing it?

**Comment by hawkw** [comment]
> I think you're right that option 2 makes the most sense. Mind if I take a crack at implementing it?

Go for it — it should be fairly straightforward, but please feel free to ping me if you need any advice!

**Comment by pkinsky** [comment]
Sorry, I've been offline for a while b/c holidays. This was fairly easy to implement (I think I was assuming it'd be harder based on the difficulty of finding a workaround). I just need to write up a rustdoc comment for the function and then I'll file a PR

**Comment by hawkw** [comment]
@pkinsky any updates?

**Comment by pkinsky** [comment]
@hawkw PR here: https://github.com/tokio-rs/tracing/pull/503/files
