### ISSUE TITLE
chore: make "nightly-examples" the default

### ISSUE THREAD

**Issue by hawkw** [tokio-rs/tracing#479]
### Motivation

Currently, there's separate "nightly-examples" and "nightly-tests" directories for examples and tests using async-await. This was necessary when the minimum supported Rust version didn't have async-await syntax. However, this is no longer necessary, since we now require Rust 1.39.0+.

### Proposal

We should move these examples and tests into the regular "examples" and "tests" dirs. When and where these examples are duplicates of previous old-futures examples, we should delete the legacy examples.

Additionally, it would also be good to add RustDoc examples using async-await, now that it's okay to do that.

**Comment by toidiu** [comment]
I would like to help with this.

**Comment by toidiu** [comment]
I am hitting the following error when trying to compile the nightly test. I think I have narrowed the cause to [`tower-macros` dependency](https://github.com/toidiu/tracing/blob/ak-479/examples/Cargo.toml#L40). Oddly enough though this doesn't happen when I run cargo test in the nightly-examples directory.

```
error: recursion limit reached while expanding the macro `$crate::__mk_format_args`
   --> examples/examples/proxy_server.rs:130:9
```

**To reproduce** run `cargo test` in the following branch https://github.com/toidiu/tracing/blob/ak-479. You can also run the following command to get more info about whats happening during macro expansion: `RUSTFLAGS="-Z external-macro-backtrace" cargo +nightly test`

**Comment by davidbarsky** [comment]
Try bumping the recursion limit if you haven’t already: https://doc.rust-lang.org/reference/attributes/limits.html

**Comment by toidiu** [comment]
bumped it up to 2048 with no luck

**Comment by toidiu** [comment]
Btw I am running stable rustc 1.40 on darwin.

**Comment by hawkw** [comment]
This is probably a bug in the `log` compatibility macros. I can take a look at it. Would you mind opening a separate issue for this? Thanks!

**Comment by toidiu** [comment]
Will do. Thanks for the quick response times!

**Comment by hawkw** [comment]
This has been done for a while.
