### ISSUE TITLE
registry::DataInner may not be dropped if child spans are dropped out of order

### ISSUE THREAD

**Issue by cjlucas** [tokio-rs/tracing#511]
### Version

`tracing-subscriber 0.2.0-alpha2`

### Platform

macOS 10.14.4
```
Darwin hack.cjlucas.net 18.5.0 Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64
```

### Crates

`tracing-subscriber`

### Description

Given a program with nested spans that are dropped out of order:

```rust
fn main() {
    tracing_subscriber::fmt::init();

    let span1 = tracing::error_span!("span1");
    let _enter1 = span1.enter();

    let span2 = tracing::error_span!("span2");
    let _enter2 = span2.enter();

    let span3 = tracing::error_span!("span3");
    let _enter3 = span3.enter();

    drop(_enter1);
    drop(_enter2);
    drop(span2);
}
```

Results in the following scenario:
* The DataInner for `span3` is dropped. `span2` is its parent, so [we attempt to](https://github.com/tokio-rs/tracing/blob/master/tracing-subscriber/src/registry/sharded.rs#L272-L298) `try_close` it using the default dispatcher.
* `span2`'s ref count drops to zero, causing its `DataInner` to be dropped as well and attempts to `try_close` `span1`. When we attempt to get the default dispatcher, it fails because we're currently within the `dispatch::with_default` block from the previous drop. 
  * Per [the docs](https://docs.rs/tracing/0.1.11/tracing/dispatcher/fn.get_default.html) it will return a noop dispatcher.

This prevents `Registry::try_close` from being called on `span1`, keeping its ref count at 1 and resulting in its `DataInner` not being dropped.

**Comment by cjlucas** [comment]
My first inclination was to work around the issue by doing something like:

```rust
    fn drop(&mut self) {
        if self.parent.is_some() {
            dispatcher::get_default(|subscriber| {
                let subscriber = subscriber.downcast_ref::<Registry>().unwrap();

                let mut parent = self.parent.take();
                while parent.is_some() {
                    if let Some(p) = parent {
                        let grandparent = subscriber.spans.get(id_to_idx(&p)).parent;
                        if subscriber.try_close(p) && grandparent.is_some() {
                            parent = grandparent;
                        }
                    }
                }
            }
        }
    }

```

But I don't have a good macro understanding of this project to say whether or or not the default dispatcher will be a `Registry`.

**Comment by hawkw** [comment]
Hmm. I think perhaps the right thing to do would just be to change `tracing-core` so that the current default dispatcher is only disabled in `new_span` and `event`, which is sufficient to avoid infinite dispatch loops but lets us freely call into our own `try_close` implementation. Come to think of it, I _thought_ we already made that change...
