### ISSUE TITLE
EnvFilter::from_default_env() acts differently to env_logger

### ISSUE THREAD

**Issue by sazzer** [tokio-rs/tracing#512]
### Version

tracing = "0.1.11"
tracing-log = "0.1.1"
tracing-subscriber = "0.1.6"

### Platform

Darwin xxxxx.local 18.7.0 Darwin Kernel Version 18.7.0: Sat Oct 12 00:02:19 PDT 2019; root:xnu-4903.278.12~1/RELEASE_X86_64 x86_64

### Crates

tracing-subscriber

### Description

I've just migrated from `log` and `env_logger` to use tracing instead, and I've found that the way RUST_LOG is parsed is *not* the same between the two.

Specifically, the following:
```
RUST_LOG=debug,tokio_postgres=info,hyper::server::response=info
```

Means:
* With `env_logger` - treat all loggers as DEBUG *except* for `tokio_postgres` and `hyper::server::response`
* With `EnvFilter::from_default_env()` - treat all loggers as DEBUG. This then overrides the explicit setting of INFO for the other two, so they are DEBUG as well.

**Comment by hawkw** [comment]
Hmm, I think this is a bug. The filter _should_ pick the longest filtering directive first. Thanks for the report!
