### ISSUE TITLE
tracing-subscriber 0.2.0-alpha.3 contains dbg macros, spamming console.

### ISSUE THREAD

**Issue by LaylConway** [tokio-rs/tracing#532]
## Bug Report
As mentioned, version 0.2.0-alpha.3 of tracing-subscriber contains `dbg!` macro usage.
This is currently slowing my application down to unusable levels, and spamming the console, drowning out useful information.

### Version
tracing-subscriber 0.2.0-alpha.3

### Platform
64-bit Windows

### Crates
tracing-subscriber

**Comment by davidbarsky** [comment]
We released [`tracing-subscriber 0.2.0-alpha.4`](https://crates.io/crates/tracing-subscriber/0.2.0-alpha.4) that fixed this bug and yanked `tracing-subscriber 0.2.0-alpha.3`. Thanks for the report and sorry about the inconvenience.
