### ISSUE TITLE
Re-export necessary log types from `tracing-log`

### ISSUE THREAD

**Issue by thomaseizinger** [tokio-rs/tracing#552]
### Crates

tracing-log

### Motivation

In a project that uses tracing, a dedicated dependency on `log` should not be needed.

1. Not having the dependency avoids developers from accidentally using `log` instead of `tracing`.
2. `tracing-log` depends on a certain version of `log`. In order to call the fn `LogTracer::init_with_filter`, these dependencies need to match.

### Proposal

Re-export either the whole `log` crate from `tracing-log` or at the very minimum, all types that appear in public APIs.

### Alternatives

Leave everything as it is, requiring users to explicitly depend on `log`.

**Comment by hawkw** [comment]
This seems like it could be a good idea. The one downside is that if `log` issues a breaking change, we may have to issue a breaking change for `tracing-log` as well...although, if we change the version we depend on to one with a breaking change, that's kind of already the case...

@tokio-rs/tracing any thoughts on this?

**Comment by davidbarsky** [comment]
Yeah, I think this is a good idea.

> The one downside is that if log issues a breaking change, we may have to issue a breaking change for tracing-log as well...although, if we change the version we depend on to one with a breaking change, that's kind of already the case...

Given how conservative `log` is in cutting _any_ releases, I'm not too worried about a mismatch in release cadence.

**Comment by thomaseizinger** [comment]
> ...although, if we change the version we depend on to one with a 

@hawkw that is the point yes :)

Slightly off-topic: I would really wish, [this lint](https://github.com/rust-lang/rust-clippy/issues/3553) would get more attention.
IMO, it is a huge issue in the Rust ecosystem: Too many crates have external types in their public API and don't reexport them, forcing downstream users to manually add a dependency on the crate and keeping the version in sync as those dependencies are upgraded.

**Comment by hawkw** [comment]
@thomaseizinger that motivation makes sense — I'm definitely on board with this. If you're interested in opening a PR to add the re-exports, I'd happily merge it. Otherwise, I'm fine with adding it when I get around to it.
