### ISSUE TITLE
Check existence of arguments to tracing::instrument's skip attribute

### ISSUE THREAD

**Issue by d-e-s-o** [tokio-rs/tracing#562]
## Feature Request

The arguments to `tracing::instrument`'s `skip` attribute are prone to get out of date, because there is no checking that a parameter of the provided name actually exists.

For example,
```rust
#[instrument(level = "info", skip(XYZ))]
pub async fn handler(foo: u32) {
  unimplemented!()
}
```

There is no argument called `XYZ`, but there is no error or warning indicating that. So whenever there is a rename of an argument chances are that an adjustment of the `skip` list is forgotten.

### Crates

tracing 0.1.12

**Comment by hawkw** [comment]
This is a great idea, thanks for the suggestion! I think it ought to be fairly simple to implement.
