### ISSUE TITLE
Fix typo in crate README

### ISSUE THREAD

**Issue by brokenthorn** [tokio-rs/tracing#577]
## Bug Report

There is a typo `defualt` in the crate's description (visible on [crates.io](https://crates.io/crates/tracing), as well as the github README):
```
tracing::subscriber::set_global_default(subscriber)
        .expect("setting defualt subscriber failed");
```

### Version

```
├── tracing v0.1.12
│   ├── tracing-attributes v0.1.6
│   └── tracing-core v0.1.9
├── tracing-subscriber v0.2.0
│   ├── tracing-core v0.1.9 (*)
│   ├── tracing-log v0.1.1
│   │   └── tracing-core v0.1.9 (*)
│   └── tracing-serde v0.1.0
│       └── tracing-core v0.1.9 (*)
```

### Platform

`Darwin blackdwarf.local 18.7.0 Darwin Kernel Version 18.7.0: Thu Jan 23 06:52:12 PST 2020; root:xnu-4903.278.25~1/RELEASE_X86_64 x86_64`

### Description

There is a typo in the `README`. Description is at the top.

**Comment by hawkw** [comment]
Thanks for catching the typo! If you're interested in opening a PR to correct it, I'd happily merge one. Otherwise, I'll make sure it gets fixed as soon as possible.

**Comment by brokenthorn** [comment]
Seems too minor to fork just for that. Doesn't feel like a proper contribution from me.

I was thinking you could slip that in the CHANGELOG for a future release, maybe just reference this issue.

But if you want me to open a PR, just say so and I will gladly do so.

**Comment by hawkw** [comment]
Cool, I'll fix it the next time I'm changing the readme.
