### ISSUE TITLE
Support disabling the level in formatted output

### ISSUE THREAD

**Issue by Kobzol** [tokio-rs/tracing#592]
## Feature Request
It would be nice if the level could be disabled in the output, in the same way that the [target](https://github.com/tokio-rs/tracing/issues/219) can be disabled.

### Crates
`tracing-subscriber`

### Motivation
`tracing` is used to log structured data and sometimes you don't need to know the level of the event (the level can serve just for filtering). If you need it on a per-event basis, you can easily include it into the event attributes. It would also achieve better consistency, I was surprised that I could turn off the target, but the level.

The main motivation is to save bytes in the output, the level is included in every event, so if you don't need it it can produce a lot of unnecessary data.

### Proposal
Add `with_level(display_level: bool)` method to `LayerBuilder` and don't output the level if it's set to `False`.

It seems relatively easy to implement, if you agree with this proposal, I will send a PR.

**Comment by hawkw** [comment]
Yup, this seems like a good idea to me! I think it wasn't added previously just because nobody expressed that they wanted it, but it makes sense.

I'd happily merge a PR if you're interested in writing one.
