### ISSUE TITLE
 Ensure #[trace] macro works correctly for async functions.

### ISSUE THREAD

**Issue by hawkw** [tokio-rs/tracing#6]
copied from hawkw/tokio-trace-prototype#54:

>[Original discussion](https://github.com/hawkw/tokio-trace-prototype/pull/16#discussion_r228291890).
>
>@hawkw
>
>> Also for potential future work: it would be cool to allow things that aren't functions to be traced. At the very least, it would be nice to detect if we're annotating a future, and instrument it in the "right way" --- by constructing the span once and wrapping the future in a `tokio_trace_futures::Instrumented` future.
>> The naïve approach—just putting the `#[trace]` macro on the implementation of `Future::poll` for that future—wouldn't do the Right Thing; it would instead create a new span that's entered for every individual time that future is polled. This could potentially be a big enough gotcha that I think it's probably worthwhile to special-case this.
>> We'd probably want to figure out a similar approach for `async fn`s as well...
>> [my comment redacted]
>> Yes, but I think we'd want to make sure we do the right thing for `async fn`s --- namely, I think we'd want to make sure that the future created by that `async fn` is instrumented by that span, rather than just the initial call to the async fn that returns the future. This may require some testing.

**Comment by mbilker** [comment]
I don't know how related this is but it does deal with the `std::future::GenFuture` returned from `async` functions.

I tried to write an `Instrumented` implementation for `std::future::Future`, but ran into issues because `GenFuture` implements `!Unpin` so you can't do `Pin::new(inner)` if you go by the `futures::Future` implementation.

I got around this by adding a `boxed_instrument` method which does `Box::pin(self)` and then I have an `Instrumented<Pin<Box<T>>>` to handle the actual polling of that.

**Comment by hawkw** [comment]
@mbilker this is definitely relevant, thanks! I think having `tokio-trace-futures` support futures 0.3 is definitely a prerequisite for supporting async-await in the proc macros, thanks for looking into it. I'd love to see a branch with your solution!

**Comment by mbilker** [comment]
Since I only have experience with futures 0.1, I took a look at futures 0.3 and `futures::future::Future` appears to be a re-export of `std::future::Future`, which means the code I have should work for futures 0.3.

**Comment by mbilker** [comment]
Put up my changes at https://github.com/mbilker/tokio-trace-nursery/tree/std-future

**Comment by mbilker** [comment]
If tokio-trace-futures is targeting versions before 1.33.0, then `boxed_instrument` needs to have an alternate implementation to use `Box::new` instead `Box::pin` as `Box::pin` was stabilized in 1.33.0.

**Comment by davidbarsky** [comment]
@hawkw and I chatted about instrumenting async functions. Below is a brief summary.

An async function like the one below...

```rust
async fn call(req: Request<Body>) -> Result<Response<Body>, Error>> {
   // function body
} 
```

...desugars to something like:

```rust
fn call(req: Request<Body>) -> impl Future<Output=Result<Response<Body>, Error>>> {
   async move {
         // function body
   }
} 
```

We can use this knowledge and a sprinkling of [syn-mid](https://github.com/taiki-e/syn-mid/) to instrument an async function's _future_. syn-mid exposes two structs: [ItemFn](https://docs.rs/syn-mid/0.3.0/syn_mid/struct.ItemFn.html) and [Block](https://docs.rs/syn-mid/0.3.0/syn_mid/struct.Block.html). The latter is a block whose body is not parsed. We can use this to instrument futures emitted by an `async fn` by writing something similar to:

```rust
use syn_mid::{Block, ItemFn};
use quote::quote;
use proc_macro::TokenStream;

#[proc_macro_attribute]
pub fn instrument(args: TokenStream, function: TokenStream) -> TokenStream {
    let mut function: ItemFn = parse_macro_input!(body);
    let body = function.body;
    *function.body = quote! {
        async move {
           #body
       }.instrument!(span)
    };
    function.into()
}
```

(cc: @yaahallo, this might be of interest to you given your interest in https://github.com/tokio-rs/tokio-trace-nursery/issues/15)

**Comment by yaahallo** [comment]
@davidbarsky yea I'm interested, I'll look into this more in depth tonight :)

**Comment by yaahallo** [comment]
```rust
        async move {
           #body
       }.instrument!(span)```

This isn't a thing right? As in `quote!` doesn't do magic to allow postfix macros?

For context, my interest in proc-macros is based on a desire to learn them, not previous experience.

**Comment by davidbarsky** [comment]
@yaahallo sorry, I didn't mean to do make `.instrument!()` a macro! I mean to use point at something like this: https://github.com/tokio-rs/tokio-trace-nursery/blob/08db36d475c4af28821434f60d4f4ed9748452ee/tokio-trace-futures/examples/proxy_server.rs#L76

**Comment by davidbarsky** [comment]
Erm, the _entire_ block, which looks is:

```rust
let client_to_server = copy(client_reader, server_writer)
    .and_then(|(n, _, server_writer)| {
        info!(size = n);
        shutdown(server_writer).map(move |_| n)
}).instrument(span!(Level::TRACE, "client_to_server"));
```

**Comment by hawkw** [comment]
> ```rust
>         async move {
>            #body
>        }.instrument!(span)
> ```
> 
> This isn't a thing right? As in `quote!` doesn't do magic to allow postfix macros?
> 
Pretty sure that's a typo...
