### ISSUE TITLE
Move `tracing_subscriber::fmt` to a newly-revived `tracing-fmt`

### ISSUE THREAD

**Issue by davidbarsky** [tokio-rs/tracing#640]
### Crates

- `tracing-subscriber`, `tracing-fmt`.

### Motivation

In my view, `tracing-subscriber` is a crate that is _slightly_ overburdened with responsibilities because it has two distinct audiences: application and library authors. 
- For application authors, it provides a `fmt` module and `EnvFilter` to enable `env_logger`-like use-cases.
- For library authors, it offers the rest of the crate.

### Proposal

I propose that we split `tracing-subscriber` into two (or more!) separate crates:

- Utilities for building subscribers/layers should remain in `tracing-subscriber`. This will include the `layer`, `registry`, `field` modules. I'm not sure where `reload` should go, if anywhere.
- `tracing-fmt` should have the existing `tracing_subscriber::fmt` module. This crate will be the crate for application developers needing a `env_logger`/`log4rs` replacement, but it will take a dependency on the now-reduced `tracing-subscriber` crate.

### Alternatives

- Don't do this.
- Opt for a different, more granular, crate partitioning.

**Comment by hawkw** [comment]
>   * For application authors, it provides a `fmt` module and `EnvFilter` to enable `env_logger`-like use-cases.
> 
>   * For library authors, it offers the rest of the crate.

I don't agree with this. I think all modules in `tracing-subscriber` are valuable for application authors as well. Remember that `tracing-subscriber` also contains the traits and types necessary for composing `Layer`s, a task which is more or less exclusively needed by layer _users_ (read: application authors). If I want to use the `fmt` layer in combination with anything else, I will have to import `tracing-subscriber` regardless.

For example, you suggest that the `registry` module remain in `tracing-subscriber`:
>   * Utilities for building subscribers/layers should remain in `tracing-subscriber`. This will include the `layer`, `registry`, `field` modules. I'm not sure where `reload` should go, if anywhere.

However, the concrete `registry::Registry` implementation is used more or less exclusively by applications.

In general, I'd like a clearer picture of what the expected benefits of making this change are. The issue does not really describe what we would actually hope to gain by doing this, and therefore, it's hard to weigh that against the cons of such a change (e.g. more crates to release, more intra-crate dependencies to manage, more crates for users to have to import and therefore to be aware of, etc.).

**Comment by davidbarsky** [comment]
I'm closing this issue because I can't really think of a way to break up `tracing-subscriber`'s traits, formatters, and concrete Subscribers in a way that works nicely. Eliza mentioned that more `Into` implementations would reduce some of the verbosity and I'm inclined to agree.
