### ISSUE TITLE
instrument macro: provide way to include additional fields

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/tracing#650]
It would be nice to have an API for including additional fields with values set by calling methods on `self`.

For example (making up an API that probably isn't possible)

```rust
struct Foo {
    conn: TcpStream,
}

impl Foo {
    #[instrument(fields(local_addr = self.local_addr))]
    fn run(&self) {
    }

    fn local_addr(&self) -> SocketAddr {
        self.conn.local_addr()
    }
}
```

**Comment by hawkw** [comment]
I think the proposed API may actually work as an extension of the existing `fields` API...we could just parse an arbitrary expression that's then evaluated when the span is constructed. Depending on how this works, it _might_ even be possible to get decent diagnostics out of the compiler when these are malformed.
