### ISSUE TITLE
Readme example says it uses set_global_default, but does not do so

### ISSUE THREAD

**Issue by Darksonn** [tokio-rs/tracing#667]
The readme contains the following snippet: ([link][1])

>The simplest way to use a subscriber is to call the `set_global_default` function.
>
>```rust
>use tracing::{info, Level};
>use tracing_subscriber;
>
>fn main() {
>    // a builder for `FmtSubscriber`.
>    let subscriber = tracing_subscriber::fmt()
>        // all spans/events with a level higher than TRACE (e.g, debug, info, warn, etc.)
>        // will be written to stdout.
>        .with_max_level(Level::TRACE)
>        // completes the builder and sets the constructed `Subscriber` as the default.
>        .init();
>
>    let number_of_yaks = 3;
>    // this creates a new event, outside of any spans.
>    info!(number_of_yaks, "preparing to shave yaks");
>
>    let number_shaved = yak_shave::shave_all(number_of_yaks);
>    info!(
>        all_yaks_shaved = number_shaved == number_of_yaks,
>        "yak shaving completed."
>    );
>}
>```

This snippet claims to call a function by the name `set_global_default`, but does not do so — it appears to use `.init()` for that purpose. The `set_global_default` function is also mentioned a bit further down the readme.

[1]: https://github.com/tokio-rs/tracing/blob/master/README.md#in-applications

**Comment by hawkw** [comment]
This is my fault, sorry — I updated the example in #660 to use the new `init` API, but didn't update the surrounding text. Thanks for catching that!
