### ISSUE TITLE
Does .travis.yml have a wrong MSRV?

### ISSUE THREAD

**Issue by 8573** [tokio-rs/tracing#669]
<https://github.com/tokio-rs/tracing/pull/482> seems to make it clear that Tracing's minimum supported Rust version is meant to be 1.39, but the `.travis.yml` file seems to disagree:

https://github.com/tokio-rs/tracing/blob/351ac21809d929c6cdf4d7134ce7e9a70df212eb/.travis.yml#L4-L7

Is the `.travis.yml` file simply outdated and not used anymore? (I note the absence of a Travis CI badge in the README.) If so, would it be better to remove the file lest it risk confusing people (such as I) who read it to check the MSRV, having missed the "requires rustc 1.39+" notes in the documentation?

**Comment by hawkw** [comment]
> Is the `.travis.yml` file simply outdated and not used anymore? (I note the absence of a Travis CI badge in the README.)

Yup, we've switched from Travis to using GitHub Actions for CI. The `.travis.yml` definitely should've been deleted, I think this was just an oversight on my part. Thanks for catching that — I'll remove it.
