### ISSUE TITLE
Docs build fail for versions after 0.2.0

### ISSUE THREAD

**Issue by Renkai** [tokio-rs/tracing#681]
### Version
0.2.3

### Platform
[docs.rs](https://docs.rs/crate/tracing-futures/0.2.3)

### Description
On [docs.rs](https://docs.rs/crate/tracing-futures/0.2.3), all versions after 0.2.0 build failed

**Comment by hawkw** [comment]
This is for `tracing-futures`, right? 

The issue that was causing docs.rs builds to fail has been fixed on master — thanks for the reminder that we need to get a release out.

**Comment by davidbarsky** [comment]
@hawkw We _did_ get a release out, thankfully: https://docs.rs/tracing-futures/0.2.4/tracing_futures/. I'll close this issue.
