### ISSUE TITLE
tracing-appender: add top-level module documentation and examples

### ISSUE THREAD

**Issue by davidbarsky** [tokio-rs/tracing#687]
As noted in https://github.com/tokio-rs/tracing/pull/676#pullrequestreview-398289930, the top-level module documentation for `tracing-appender` is a bit sparse. Before releasing a 0.1, we should have some rich, top-level docs and examples.

**Comment by zekisherif** [comment]
I have it ready for review, but need to merge in #676 first before I can create the PR.

**Comment by zekisherif** [comment]
#692 is addressing this.
