### ISSUE TITLE
"Tried to clone Id(1), but no span exists with that ID" when setting parent span

### ISSUE THREAD

**Issue by asayers** [tokio-rs/tracing#688]
(Not a real issue, just leaving this here to help future searchers.)

The docs tell you to explicitly set a parent span like this:

```rust
let span1 = info_span!("my great span");
let span2 = info_span!(parent: &span1, "child of great span");
```

And this works.  However, if you forget to borrow `span1` and do this...

```rust
let span1 = info_span!("my great span");
let span2 = info_span!(parent: span1, "child of great span");
```

...it will compile fine, but panic at runtime. :disappointed: It's clear what's going on here - `span1` is converted into its ID, but in the process it's dropped and the ID is deregistered from the subscriber.  Still, my brain is used to getting a compile-time errors when I miss an `&` and it took me a while to spot the mistake - so I thought I'd leave this here in hopes of helping the people of the future.

**Comment by hawkw** [comment]
Hmm, thanks for reporting this, that's definitely not great. We should look into potential API changes to stop this from happening.

**Comment by davidbarsky** [comment]
I've re-opened this issue because I think it's an ergonomic papercut and it'd be useful to track this.

**Comment by ctiller** [comment]
Just ran into this converting a bunch of code I maintain to use tracing.

**Comment by hawkw** [comment]
Yeah, we need to fix this. Unfortunately, I think it's going to need to wait until the next API breaking change.
