### ISSUE TITLE
JSON fmt subscriber does not emit events when inside a span with a `record`-ed field

### ISSUE THREAD

**Issue by danburkert** [tokio-rs/tracing#707]
This may be a duplicate of #704, but I'm not familiar enough with the codebase to know for sure.

I created a self contained repro [here](https://github.com/danburkert/tracing-json-fmt-repro/blob/master/src/main.rs).  I expected running that snippet would result in two log messages ('outer' and 'inner'), however only the 'outer' log message is emitted.  If the non-json formatter is used, or if the field is not filled in with `record`, then both log messages are emitted.

**Comment by hawkw** [comment]
I don't _think_ this is related to #704, it looks like a different issue. Thanks for the report!

**Comment by hawkw** [comment]
Quick update: I've figured out what's going on here and will have a fix ready soon. :)

**Comment by neoeinstein** [comment]
Can we roll a release of `tracing-subscriber` which has this fix in it? The latest version was from before this bugfix was included.

**Comment by hawkw** [comment]
Sure, sorry about that!

**Comment by hawkw** [comment]
@neoeinstein It's [published](https://crates.io/crates/tracing-subscriber/0.2.6)! Sorry for the delay.
