### ISSUE TITLE
Span::follows_from has no effect when exporting via OpenTelemetry

### ISSUE THREAD

**Issue by bodymindarts** [tokio-rs/tracing#724]
The [`on_follows_from`](https://tracing.rs/tracing_subscriber/layer/trait.layer#method.on_follows_from) method is not implemented on [OpenTelemetryLayer](https://tracing.rs/src/tracing_opentelemetry/layer.rs.html#377-480) thus it has no effect when exporting traces via OpenTelemetry.

 PR https://github.com/tokio-rs/tracing/pull/723 implements the method and translates it into bi-directional `Links`.

**Comment by jtescher** [comment]
Fixed in #723

**Comment by bodymindarts** [comment]
> PR #723 implements the method and translates it into bi-directional Links.

Incase someone finds this in the future - we decided to go with uni-directional Links.
