### ISSUE TITLE
#[instrument(name = "")] not documented

### ISSUE THREAD

**Issue by jonhoo** [tokio-rs/tracing#725]
The `#[instrument]` parameter `name` to set the name of the generated span is not currently documented anywhere. Silly readers (like myself) may end up setting `target` instead, since it looks most like name, which _definitely_ does not do what you want it to :p

**Comment by hawkw** [comment]
I think this was an oversight on my part, thanks for catching it! Will make sure it gets fixed.

**Comment by LukeMathWalker** [comment]
Just bumped into this myself today :+1:

**Comment by hawkw** [comment]
Fixed by #897!
