### ISSUE TITLE
opentelemetry: support `tracing-log` special values

### ISSUE THREAD

**Issue by hawkw** [tokio-rs/tracing#733]
### Crates

`tracing-opentelemetry`

### Motivation

Currently, when converting `log::Record`s to `tracing::Event`s using `tracing-log`, data from `log`'s metadata is converted to special fields prefixed with `log.`, rather than being recorded as `tracing` metadata. In order to properly display this data from `log`, the `tracing-log` crate provides the [`NormalizeMetadata` trait](https://docs.rs/tracing-log/0.1.1/tracing_log/trait.NormalizeEvent.html). `tracing-opentelemetry` does not currently use this, however, and location data from `log` events is treated as a regular field rather than a source code location in OpenTelemetry logs.

For example, note the difference between the logs from `tower-buffer` (generated from native `tracing` events) and the logs from `h2` (converted from `log` records via `tracing-log`): 
![image](https://user-images.githubusercontent.com/2796466/82760153-9b11fa00-9da6-11ea-95f2-3e23c37a18f4.png)

### Proposal

We should update `tracing-opentelemetry`'s `on_event` implementation to do something similar to what `tracing-subscriber::fmt` does here:
https://github.com/tokio-rs/tracing/blob/954b1b8ab8b7fc577763aac0237c86b10313ae14/tracing-subscriber/src/fmt/format/mod.rs#L376-L381

We may also want to feature-flag the `tracing-log` dependency so that users can opt out.

**Comment by jtescher** [comment]
Sounds good, currently we pull some data form metadata and then visit the event, is there a similar function to normalize the event fields? or what's the best approach for normalizing there?

**Comment by hawkw** [comment]
> Sounds good, currently we pull some data form metadata and then visit the event, is there a similar function to normalize the event fields? or what's the best approach for normalizing there?

If the metadata has been normalized, it will already include the values from `log.` fields, so they should just be skipped when visiting the fields:
https://github.com/tokio-rs/tracing/blob/954b1b8ab8b7fc577763aac0237c86b10313ae14/tracing-subscriber/src/fmt/format/mod.rs#L545-L547
