### ISSUE TITLE
Tokio-trace docs

### ISSUE THREAD

**Issue by kazimuth** [tokio-rs/tracing#76]
It might be helpful to have:

- a link to tokio-trace in the main tokio README
- links to the various tokio-trace subscribers in the tokio-trace README, similar to how [log lists loggers](https://crates.io/crates/log/)
- a README for tokio-trace-nursery and its various subcrates
- docs for how to setup tokio-trace across a whole program, instead of just on a single thread. (I honestly don't know how to do this, e.g. if i'm using `runtime` and want the executor threads instrumented.)

**Comment by hawkw** [comment]
I believe all of the points in this issue except for "a link to tokio-trace in the main tokio README" have been addressed in 36ed35c52c88aa7b737e3502b91075a80a548baa and d1a6eff98d8f74d8017dd1c7cf5e4628615222a8. I think it would definitely be good to mention `tracing` in the `tokio-rs/tokio` readme and on the Tokio website, but that seems like issues against those repositories?
