### ISSUE TITLE
subscriber: default timestamp formatter without `chrono` is `SystemTime`'s `Debug` impl

### ISSUE THREAD

**Issue by hawkw** [tokio-rs/tracing#791]
### Version

`tracing-subscriber` 0.2.7

### Crates

`tracing-subscriber`

### Description

By default, `tracing-subscriber`'s `fmt` module uses the [`chrono`](https://docs.rs/chrono/0.4.13/chrono/) crate for formatting timestamps. However, the chrono dependency is optional and can be disabled independently of `fmt`. This is correct --- users who are using the `Uptime` timestamp formatter, providing their own custom timestamp formatter, or not using timestamps don't need the `chrono` dependency and may want to disable it.

However, when the `chrono` feature flag is disabled, the default formatter still enables `SystemTime` timestamps by default:
https://github.com/tokio-rs/tracing/blob/7dc37dda8fe6c217d6ba2200db13d0d45b9530e4/tracing-subscriber/src/fmt/format/mod.rs#L184-L194
So, the formatter will still emit timestamps unless `without_time(true)` is called. 

What do we do when timestamps are enabled, but we can't use `chrono` to format them because the dependency is not enabled?

It turns out that we fall back to `SystemTime`'s `fmt::Debug` impl:
https://github.com/tokio-rs/tracing/blob/7dc37dda8fe6c217d6ba2200db13d0d45b9530e4/tracing-subscriber/src/fmt/time.rs#L119-L124

The formatted output from this is...not great:
![Screenshot_20200709_092349](https://user-images.githubusercontent.com/2796466/87067817-6c6ea800-c1c9-11ea-8861-91ef5ba29891.png)

I do think it's correct to rely on `chrono` (or arbitrary user-defined timestamp formatters) for complex human-readable formatting. But the `fmt::Debug` implementation is not ideal. It includes the struct's name, field names, and curly braces, which add a lot of noise and make the log lines much longer. It leaks the `SystemTime` type's internal layout, which may be different depending on OS. And, the width of the numeric fields are not padded to a fixed width, so the log lines are not aligned. 

We should try to fall back to something a little nicer when `chrono` isn't present. It doesn't need to be fancy --- we can (and should!) rely on `chrono` for human readable formats. Maybe just the number of seconds since the Unix epoch or something?

**Comment by danburkert** [comment]
In case you want something a little fancier, feel free to copy this: https://github.com/danburkert/kudu-rs/blob/master/src/timestamp.rs#L5-L18 (original attribution should go to musl I believe).
