### ISSUE TITLE
Setting span.kind tag on tracing span does not get through opentelemetry layer correctly and sent to Jaeger.

### ISSUE THREAD

**Issue by glademiller** [tokio-rs/tracing#797]
## Bug Report
Using `tracing::info_span!` and adding the tag `span.kind` I would expect `span.kind` to be sent through the opentelemetry layer and on to Jaeger. It does not appear to happen and instead span.kind is not set.

### Version

├── tracing v0.1.16
│   ├── tracing-attributes v0.1.9
│   └── tracing-core v0.1.11
├── tracing-futures v0.2.4
│   └── tracing v0.1.16 (*)
├── tracing-opentelemetry v0.5.0
│   ├── tracing v0.1.16 (*)
│   ├── tracing-core v0.1.11 (*)
│   ├── tracing-log v0.1.1
│   │   └── tracing-core v0.1.11 (*)
│   └── tracing-subscriber v0.2.7
│       ├── tracing-core v0.1.11 (*)
│       ├── tracing-log v0.1.1 (*)
│       └── tracing-serde v0.1.1
│           └── tracing-core v0.1.11 (*)
├── tracing-subscriber v0.2.7 (*)

### Platform

Linux 110te-ll0000684 5.3.0-62-generic #56~18.04.1-Ubuntu SMP Wed Jun 24 16:17:03 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### Crates

tracing-opentelemetry

### Description

Using `tracing::info_span!` and adding the tag `span.kind` I would expect `span.kind` to be sent through the opentelemetry layer and on to Jaeger. It does not appear to happen and instead span.kind is not set.

**Comment by glademiller** [comment]
Looking closer and running Jaeger locally it looks like both `internal` and `server` are sent through. I am actually working against SignalFX's APM solution which supports Jaeger and apparently it doesn't like having the two `span.kind` tags. In any case I would expect the ability to override that value and not have it add an additional `span.kind`.

**Comment by glademiller** [comment]
One thought that comes to mind would be an additional method on `OpenTelemetrySpanExt` that could change the span kind.

**Comment by hawkw** [comment]
ccing @jtescher, our resident OpenTelemetry expert

**Comment by jtescher** [comment]
@glademiller this has been fixed in https://github.com/open-telemetry/opentelemetry-rust/pull/140, but not yet released. Also heads up that this behavior may change, the spec may make these reserved keywords (https://github.com/open-telemetry/opentelemetry-specification/issues/660) in which case we may need a different solution (a more explicit method as you mentioned, or prefix with `otel.`, or other).

**Comment by glademiller** [comment]
@jtescher just to confirm this fix hasn't been released yet?

**Comment by jtescher** [comment]
It has not (although you could point at that commit if you want the fix now). We can leave this issue open until the next release as a marker.

**Comment by glademiller** [comment]
@jtescher just FYI tracing-opentelemetry at the moment is incompatible with the master branch on the opentelemetry repository. Probably already on your radar.
