### ISSUE TITLE
tokio-trace: how to use Spans to represent concurrency?

### ISSUE THREAD

**Issue by jsgf** [tokio-rs/tracing#80]
I've been reading the code for tokio-trace, and I've got some questions about `Span`s and how they're intended to be used.

It looks like they're pretty good at representing strictly nested time-periods, as you'd get with a function call tree. But its unclear to me if the direct children of a parent `Span` can overlap with each other (ie, representing long-term concurrent operations).

For example, if I have a Future which is managing 10 concurrent connections which it initiates at once and then waits for each of them to produce a result, could I represent that as a parent `Span` with 10 sub-`Span` representing each connection (which in turn may have sub-spans, etc)? It seems like that would't work because there's always a notion of "the" current `Span`.

Or is this not the intended level of granularity? Should I be using `Span` just to track specific calls to `Future`/`Stream::poll` and derive tracing at that level? I can see how that would be possible, but it seems like it would be hard to reconstruct application-level states from that level of granularity.

The example doesn't really help clarify this, because it omits all actual async behaviour.

On a more general level, is there a way to represent a dependency relationship in the trace? For example, if task A is waiting for something from task B, can that be recorded?

**Comment by hawkw** [comment]
I think we've put some work into fixing up the docs so that this is a little clearer. I'm closing this ticket for now.
