### ISSUE TITLE
subscriber: option to add thread names/IDs in `fmt` log lines

### ISSUE THREAD

**Issue by hawkw** [tokio-rs/tracing#809]
### Crates

`tracing-subscriber`

### Motivation

Since `tracing` spans can be entered by multiple threads concurrently, or move across threads freely, it can often be useful to know what thread a particular event within a span occurred on. `tracing-subscriber`'s `fmt` module does not currently record this information.

This would also be nice when `tracing_subscriber::fmt` is used to record output from tests. Since Rust runs each test in its own thread whose name is the name of the test function, this would get test names in logs "for free".
 
### Proposal

We should add a configuration option to `tracing_subscriber::fmt`'s event formatters to include thread names and/or thread IDs in the log lines it emits for events. When formatting an event, if this option is enabled, we would use the [`std::thread::current`](https://doc.rust-lang.org/stable/std/thread/fn.current.html) function to get the current thread and format its name and/or ID somewhere in the log line. The  `Thread` struct returns by `std::thread::current` has [`name`](https://doc.rust-lang.org/stable/std/thread/struct.Thread.html#method.name) and [`id`](https://doc.rust-lang.org/stable/std/thread/struct.Thread.html#method.id) methods to get the thread's name and ID, respectively.

I think ideally, there should be two separate switches for thread IDs and thread names. Something like:
```rust
tracing_subscriber::fmt()
    .with_thread_names(true)
    .with_thread_ids(true)
    // ...
```

Some considerations:
- Threads may not always have a name (note that [`Thread::name`](https://doc.rust-lang.org/stable/std/thread/struct.Thread.html#method.name) returns an `Option`). If thread names are enabled, and the current thread has no name, I think we _probably_ want to fall back to printing its thread ID. If both thread names _and_ IDs are enabled, though, we would want to only print the ID a single time, rather than twice.
- Thread names may often be quite long (e.g. `tokio-runtime-worker-10` might reasonably exist on a machine with a lot of cores!), and their length might differ significantly. Therefore, we probably want to pad them so that log lines from different threads align nicely. The best way to do that _might_ just be to track the longest thread name we've seen so far, and pad them by up to that many characters, so we don't waste a lot of whitespace when all thread names are short. On the other hand, that's a little extra work we'd be doing every time we format a line...so maybe we just want to set a max length and always pad to that. I dunno...

**Comment by Pothulapati** [comment]
I am interested to take this issue! To understand the complexity, I tried replicating the same code as that of `with_level` and I was able to get this working. 

I was able to get the following output for the `tower-load` example
```
Jul 13 17:00:05.362  INFO tokio-runtime-worker ThreadId(9) load_gen{addr=V6([::1]:3000)}:generated_request{remote.addr=[::1]:3000}: gen: sending request
Jul 13 17:00:05.362 DEBUG tokio-runtime-worker ThreadId(9) request{req.method=GET req.path="/"}: tower_load: received request. req.headers={"content-length": "25"} req.version=HTTP/1.1
Jul 13 17:00:05.363 DEBUG tokio-runtime-worker ThreadId(9) request{req.method=GET req.path="/"}: tower_load: received request. req.headers={"content-length": "25", "host": "[::1]:3000"} req.version=HTTP/1.1
Jul 13 17:00:05.363  WARN tokio-runtime-worker ThreadId(9) request{req.method=GET req.path="/"}: tower_load: rsp.status=404
Jul 13 17:00:05.363 ERROR tokio-runtime-worker ThreadId(9) load_gen{addr=V6([::1]:3000)}:generated_request{remote.addr=[::1]:3000}: gen: error received from server! status=404
Jul 13 17:00:05.364  INFO tokio-runtime-worker ThreadId(9) load_gen{addr=V6([::1]:3000)}:generated_request{remote.addr=[::1]:3000}: gen: response complete. rsp.body=path must be a single ASCII character
Jul 13 17:00:05.367  INFO tokio-runtime-worker ThreadId(12) load_gen{addr=V6([::1]:3000)}:generated_request{remote.addr=[::1]:3000}: gen: sending request
Jul 13 17:00:05.368 DEBUG tokio-runtime-worker ThreadId(12) request{req.method=GET req.path="/C"}: tower_load: received request. req.headers={"content-length": "12"} req.version=HTTP/1.1
Jul 13 17:00:05.370 DEBUG tokio-runtime-worker ThreadId(12) request{req.method=GET req.path="/C"}: tower_load: received request. req.headers={"content-length": "12", "host": "[::1]:3000"} req.version=HTTP/1.1
Jul 13 17:00:05.372  INFO tokio-runtime-worker ThreadId(12) load_gen{addr=V6([::1]:3000)}:generated_request{remote.addr=[::1]:3000}: gen: response complete. rsp.body=CCCCCCCCCCCC
```

Now, I will start working on the formatting considerations and will update the issue if I have any questions.

Thanks :)

**Comment by hawkw** [comment]
@Pothulapati this looks great. Let me know if you have any questions about formatting.
