### ISSUE TITLE
Run closure with specified subscriber unless a subscriber has already been set

### ISSUE THREAD

**Issue by mx00s** [tokio-rs/tracing#826]
### Crates

* `tracing`
* `tracing-core`

### Motivation

I'm working on a library and want to see the trace logs of a function I'm testing. This works when I wrap the function's body using `tracing::subscriber::with_default`, but I don't want to override the subscriber that external users of my library be trying to use.

### Proposal

Add a public function to execute a closure with the active subscriber if it's set (not `tracing_core::dispatcher::NoSubscriber`). Otherwise, run the closure using a specified subscriber.

### Alternatives

For my use case this is a viable workaround:

```rust
pub fn run() {
    #[cfg(test)]
    {
        let subscriber = ...;
        tracing::subscriber::with_default(subscriber, run_internal)
    }

    #[cfg(not(test))]
    {
        run_internal()
    }
}

fn run_internal() {
    ...
}
```

Eliza suggested another possibility for the general case: make `NoSubscriber` public. Then `Dispatcher`'s `is` method can be used to branch on whether a subscriber other than that default placeholder is set.

**Comment by hawkw** [comment]
For your specific use-case, have you considered just setting a default subscriber in your tests? That's probably the easiest solution for the problem of a library wanting to see traces in tests without overriding user-provided subscribers in applications.

But, I think we can definitely provide a way to check if a default subscriber (other than `NoSubscriber`) has been set, either by making `NoSubscriber` public, adding a `tracing::subscriber::is_set()` (or something), or adding a `tracing::subscriber::get_default_or_else`-type function.

**Comment by mx00s** [comment]
I considered setting a default global, yes, but couldn't figure out how to do it. Any tips? The test runner doesn't seem to support running some code before all the tests start. I was also trying to avoid manually adding code to the beginning of each test because there's a lot of them, but maybe that's the best option at this point.

Thanks, and congrats on the progress with Tokio task spawn tracing!

**Comment by mx00s** [comment]
I'll close this as it's not so obvious the use case should be addressed by the tracing crates.
