### ISSUE TITLE
tracing docs.rs layout is broken

### ISSUE THREAD

**Issue by mystor** [tokio-rs/tracing#880]
### Version

0.1.16 - 0.1.18

### Crates

tracing

### Description

The layout on docs.rs for the latest `tracing` version (0.1.18) appears to be broken. 

https://docs.rs/tracing/0.1.16/tracing/ https://docs.rs/tracing/0.1.17/tracing/ https://docs.rs/tracing/0.1.18/tracing/

![image](https://user-images.githubusercontent.com/1261662/89214862-954e4700-d595-11ea-844c-631e72bc1761.png)

**Comment by hawkw** [comment]
Ugh.
