### ISSUE TITLE
Proposal: Reorder JSON fields

### ISSUE THREAD

**Issue by bryanburgers** [tokio-rs/tracing#891]
### Crates

* tracing-subscriber

### Motivation

JSON is a structured format, so the order of the fields should be
unimportant.

However, sometimes the JSON output is read in non-structured or
semi-structured contexts, and sometimes the output is truncated. In
those situations, when the spans and the current span are serialized
before the fields and the message, it makes it very difficult to see
what is going on.

For my particular use case, this is annoying on CloudWatch, where I have to click on each log record to see the message.

<img width="1446" alt="image" src="https://user-images.githubusercontent.com/56045/89540932-530a4d00-d7c3-11ea-99c7-5dfc8e67ee4e.png">

### Proposal

By serializing the "fields" key before the "spans" and "span" keys, this
information is more likely visible when the payload is shown raw and
gets truncated.

Systems that parse the JSON as structured data should be unaffected
because of the nature of JSON.

<img width="1446" alt="image" src="https://user-images.githubusercontent.com/56045/89541059-79c88380-d7c3-11ea-8eca-2b19df057aea.png">

### Alternatives

Currently we're solving this problem by only logging the current span and not all spans, and by limiting the amount of context we include in a span. While this works, I'm afraid that in the long term we're going to miss contextual information that we want but isn't as important as the message.

**Comment by hawkw** [comment]
I'd be fine with making this change. IMO, it shouldn't be considered a breaking change, since (as you mentioned above) we only care about not breaking output formats when they are machine readable, and JSON doesn't care about field ordering (@davidbarsky, do you agree?).

I think it _might_ be nice someday to have an API where users can specify an arbitrary ordering, but that seems like overkill, especially for JSON.

**Comment by hawkw** [comment]
@LucioFranco do you have any opinions on whether or not we need to consider this a breaking change? I'm inclined to go ahead and merge #892, but I'd like at least one other maintainer to sign off :)

**Comment by davidbarsky** [comment]
I'm not sure this _is_ a breaking change, but since we just started the tracing-subscriber 0.3 branch, I think it'd be a good time to move the JSON logger into a dedicated crate.

**Comment by hawkw** [comment]
> I'm not sure this _is_ a breaking change, but since we just started the tracing-subscriber 0.3 branch, I think it'd be a good time to move the JSON logger into a dedicated crate.

I'm open to that, but that seems totally orthogonal to this issue. Let's open a new ticket to discuss that. 

If we determine this to be not breaking, I'd prefer to merge it separately from the 0.3 work --- I imagine there will be at least one more 0.2 release before the 0.3 branch is ready.

**Comment by bryanburgers** [comment]
> I'm open to that, but that seems totally orthogonal to this issue. Let's open a new ticket to discuss that.
> 
> If we determine this to be not breaking, I'd prefer to merge it separately from the 0.3 work --- I imagine there will be at least one more 0.2 release before the 0.3 branch is ready.

That would be awesome if this still shipped in 0.2. Thanks for all your help!
