### ISSUE TITLE
Spans are disabled when using WithSubscriber

### ISSUE THREAD

**Issue by jeromegn** [tokio-rs/tracing#904]
### Version

```
├── tracing v0.1.18 (*)
├── tracing-core v0.1.13 (*)
├── tracing-futures v0.2.4
│   └── tracing v0.1.18 (*)
├── tracing-log v0.1.1
│   └── tracing-core v0.1.13 (*)
├── tracing-subscriber v0.2.10
│   ├── tracing-core v0.1.13 (*)
│   ├── tracing-log v0.1.1 (*)
│   └── tracing-serde v0.1.1
│       └── tracing-core v0.1.13 (*)
```

### Platform

Linux 5.7.12-arch1-1

### Description

Spans _appear_ to be disabled when using the `WithSubscriber` trait.

I hesitated before posting this because I can't quite tell what's happening here, but I figured I might as well.

At first I tried:

```rust
my_future.with_subscriber(Registry::default().with(MyLayer))
```

and the spans were always disabled, whatever their level.

I figured this might be a filter problem (no filter == all disabled) so I tried:

```rust
my_future.with_subscriber(Registry::default().with(LevelFilter::TRACE)..with(MyLayer))
```

but I'm still getting disabled spans.

I also tried this in a project where I completely disabled my global subscriber so as to not interfere. Still, spans are disabled.

I'm expecting spans to be enabled unless there's a filter. If there's a filter, I'm expecting spans to be disabled if they are filtered out.

**Comment by hawkw** [comment]
It would be nice to have a relatively small reproduction of this — can you put one together?

**Comment by jeromegn** [comment]
I couldn't reproduce. After chatting we realized this was happening because I was using the span created by `.instrument` which assigned it to the global subscriber registry. Therefore the span was disabled within the context of the subscriber within the future.
