### ISSUE TITLE
docs: use intra-RustDoc links rather than URLs

### ISSUE THREAD

**Issue by hawkw** [tokio-rs/tracing#940]
### Crates

- all

### Motivation

Currently, all `tracing` crates use URL-based links for all RustDoc links, including internal links within the crate. However, switching to [intra-RustDoc links](https://github.com/rust-lang/rfcs/blob/master/text/1946-intra-rustdoc-links.md) has some advantages over URL-based links. In particular, we can now get a compiler warning (or error) when links are broken, using [`#[warn(intra_doc_link_resolution_failure)]`](https://doc.rust-lang.org/rustdoc/lints.html#intra_doc_link_resolution_failure). This would help prevent issues like #935.

### Proposal

Intra-RustDoc links are currently available on nightly only, although they are [planned for stabilization in Rust 1.47](https://github.com/rust-lang/rust/pull/74430). However, we already build docs on nightly on both docs.rs and Netlify, so that we can use other nightly-only features like `doc(cfg)`. We have a special `cfg` attribute that we tell docs.rs to pass when building the documentation
https://github.com/tokio-rs/tracing/blob/b3582013d8810255a870030e34b2c26530684af1/tracing/Cargo.toml#L75-L77
and use it to guard nightly-only RustDoc features:
https://github.com/tokio-rs/tracing/blob/b3582013d8810255a870030e34b2c26530684af1/tracing/src/lib.rs#L819

Therefore, we could add a
```rust
#![cfg_attr(docsrs, deny(intra_doc_link_resolution_failure))]
```
to get nice errors when links are broken, and switch all internal links to use intra-RustDoc links.

### Alternatives

Making this change would have one major downside: it would mean that building the docs locally on a stable compiler would result in none of the links working. This is different from the current use of `doc(cfg)` attributes: when built on stable, the docs are still basically usable, they're just missing some additional information about feature flags. With links broken, the docs are significantly less usable. Therefore, we _might_ want to leave things the way they are currently.

However, the rendered docs on Netlify (for branches) and on docs.rs (for published releases) would be rendered correctly, and these can be used instead in most cases. For the handful of users who do need to be able to build docs locally (such as when working on `tracing` crates offline), we could add a note to the CONTRIBUTING.md documentation on building docs locally, and state that docs should be built using `RUSTDOCFLAGS="--cfg docsrs" cargo +nightly doc ...`.

It's worth noting that a majority of other major crates, [including Tokio](https://github.com/tokio-rs/tokio/issues/1473) have determined that it's acceptable to require nightly for building docs...

**Comment by hawkw** [comment]
@davidbarsky what do you think about this?

**Comment by davidbarsky** [comment]
@hawkw _Highly_, highly in favor of this change. Requiring nightly to build docs isn't a concern for me nor is it a new line to be crossed.

**Comment by hawkw** [comment]
> FYI the lint name has changed to `broken_intra_doc_lints` in recent nightlies: https://doc.rust-lang.org/nightly/rustdoc/lints.html#broken_intra_doc_links. +1 to more intra doc links though :heart:

Oh, thanks for letting us know!

> 
> > #![cfg_attr(docsrs, deny(intra_doc_link_resolution_failure))]
> 
> Not that will only deny the lint on docs.rs, so you won't see it in CI. So your crate might fail to build on docs.rs even though it works locally. Maybe you want `cfg_attr(doc, ...)` instead?

Our CI job for building docs passes the `docsrs` cfg :) It's really just to enable nightly-only RustDoc features (IIRC the `deny` will fail to compile on stable, right?)

**Comment by jyn514** [comment]
It seems that the deny will actually completely be ignored on stable ... that seems like a rustdoc bug, it should warn the same way that rustc does 😅 I'll open an issue.
```
$ cat broken.rs 
#![deny(broken_intra_doc_links)]
/// [oops]
pub fn f() {}
$ rustdoc +nightly broken.rs 
error: unresolved link to `oops`
 --> broken.rs:2:6
  |
2 | /// [oops]
  |      ^^^^ unresolved link
  |
note: the lint level is defined here
 --> broken.rs:1:9
  |
1 | #![deny(broken_intra_doc_links)]
  |         ^^^^^^^^^^^^^^^^^^^^^^
  = help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`
$ rustdoc broken.rs  # no output
$ rustc broken.rs 
warning: unknown lint: `broken_intra_doc_links`
 --> broken.rs:1:9
  |
1 | #![deny(broken_intra_doc_links)]
  |         ^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unknown_lints)]` on by default
```

**Comment by TaKO8Ki** [comment]
Can I tackle this one?

**Comment by jyn514** [comment]
Should this have been closed? https://github.com/tokio-rs/tracing/pull/981 gave warnings for broken intra-doc links, but most of the links are still using URLs.

**Comment by hawkw** [comment]
Whoops, I think you're right --- that PR shouldn't have included a "Closes" header for this issue. Thanks for catching that!

**Comment by jyn514** [comment]
I wrote up mentoring instructions for switching these in the standard library, you should be able to adapt them to tracing without much trouble: https://github.com/rust-lang/rust/issues/75080

In particular, this should bring up most of the links:
```
rg '\[.*\]: .*(trait|struct|enum|fn)\..*\.html*'
```

**Comment by jyn514** [comment]
You can get 80% of the way there with this regex:
```
rg -l '\[.*\]: .*(trait|struct|enum|fn)\..*\.html*' | grep '\.rs$' | xargs sed -i 's#\.\./\(.*\.html\)#super::\1#g; s#\([a-z]\)/\([a-z]\)#\1::\2#g; s#[a-z]\+\.\([a-zA-Z]\+\)\.html#\1#; s/\([a-z]\)#method./\1::/; s/#method./Self::/'
```
