### ISSUE TITLE
Allow `anyhow::Error` to be passed to macros as value

### ISSUE THREAD

**Issue by thomaseizinger** [tokio-rs/tracing#957]
### Crates

`tracing-core`

### Motivation

I would like to pass `anyhow::Error` as value to a macro:

```rust
fn foo() -> anyhow::Result<()> {
	anyhow::bail!("nope")
}

if let (e) = foo() {
	tracing::warn!(e, "foo failed!");
}
```

Currently, this errors with:

```
the trait `tracing_core::field::Value` is not implemented for `anyhow::Error`
```

It is already possible to capture `std::Error` types as values, capturing `anyhow::Error` would allow us to defer the printing of the error cause(s) to the subscriber.

### Proposal

We could add anyhow as an optional dependency and expose this functionality as a feature-flag.

### Alternatives

- Not adding anyhow integration. It might be debatable how much value this feature adds, users can already include the whole error stack in the macro by using `anyhow`'s alternative formatting `{:#}`: https://docs.rs/anyhow/1.0.32/anyhow/struct.Error.html#display-representations

If we choose to add the integration, it would be nice not needing to special-case `anyhow` here. We can't reverse the dependency (anyhow depending on tracing) though because we would also need to extend the `Visit` trait to actually capture the value.

**Comment by hawkw** [comment]
> It is already possible to capture `std::Error` types as values, capturing `anyhow::Error` would allow us to defer the printing of the error cause(s) to the subscriber.

I _believe_ that `anyhow::Error` has an `AsRef` conversion to something that implements `std::error::Error`, right? Does that work?

**Comment by thomaseizinger** [comment]
I didn't know! I guess that should work yes :)
