### ISSUE TITLE
field_filter_spans intermittently fails

### ISSUE THREAD

**Issue by jyn514** [tokio-rs/tracing#993]
### Version

Master branch (currently a8cc977e01ec4e1dce4137e37cfc1bfba7ebbed8).

### Platform

I noticed the failure on MacOS, but it may appear on other platforms.

### Crates

`tracing` and `tracing-subscriber`.

### Description

Occasionally `field_filter_spans` fails with the following error:

```
}
[field_filter_spans] enabled -> true
thread 'field_filter_spans' panicked at '[field_filter_spans] more notifications expected: [Enter(MockSpan { metadata: Expect { name: Some("span3"), level: None, target: None } }), Event(MockEvent { fields: Some(Expect { fields: {"something": Any}, only: false }), parent: None, metadata: Expect { name: None, level: Some(Level(Debug)), target: None } }), Exit(MockSpan { metadata: Expect { name: Some("span3"), level: None, target: None } }), Nothing]', tracing-subscriber/tests/../../tracing/tests/support/subscriber.rs:528:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

See also https://github.com/tokio-rs/tracing/pull/991#issuecomment-699670469

**Comment by hawkw** [comment]
see also #449

**Comment by jyn514** [comment]
Oops, this is a duplicate then.

**Comment by hawkw** [comment]
*Technically* it's not, since #449 is for a different test in the same file :) But, I think the issue is caused by an interaction between the filtering directives for those two tests.
